import NonsoficGroupsExist.Asymptotics
import NonsoficGroupsExist.AlmostAutomorphism
import NonsoficGroupsExist.A2System
import NonsoficGroupsExist.A2ClassTwoOrthogonality
import NonsoficGroupsExist.A2MagicGraph
import NonsoficGroupsExist.A2MagicGraphEstimates
import NonsoficGroupsExist.A2MagicLaplacian
import NonsoficGroupsExist.A2MagicEnergy
import NonsoficGroupsExist.A2MagicHilbert
import NonsoficGroupsExist.PositiveOperatorGap
import NonsoficGroupsExist.FreeAlgebraDegree
import NonsoficGroupsExist.FreeRootFiltration
import NonsoficGroupsExist.FreeRootActions
import NonsoficGroupsExist.FreeRootPlane
import NonsoficGroupsExist.FreeRootPlaneMass
import NonsoficGroupsExist.FreeRootFunctionalValuation
import NonsoficGroupsExist.FreeRootPlaneFourier
import NonsoficGroupsExist.FreeRootCharacterValuation
import NonsoficGroupsExist.FiniteFieldElementaryPropertyT
import NonsoficGroupsExist.FreeElementaryPropertyT
import NonsoficGroupsExist.FiniteTypeCharacteristicTwoPropertyT
import NonsoficGroupsExist.FiniteFieldLeavitt
import NonsoficGroupsExist.A2Kazhdan
import NonsoficGroupsExist.ClassTwoNormalForm
import NonsoficGroupsExist.ClassTwoApproximation
import NonsoficGroupsExist.DirectedCoarea
import NonsoficGroupsExist.KazhdanImprovement
import NonsoficGroupsExist.Kazhdan
import NonsoficGroupsExist.KazhdanFiniteGeneration
import NonsoficGroupsExist.CharacterMass
import NonsoficGroupsExist.RankTwoCompression
import NonsoficGroupsExist.KazhdanControl
import NonsoficGroupsExist.AlmostMinimalDisplacement
import NonsoficGroupsExist.DelormeFixedPoint
import NonsoficGroupsExist.ShalomFinitePresentation
import NonsoficGroupsExist.UltralimitGeometry
import NonsoficGroupsExist.GaussianPositiveDefinite
import NonsoficGroupsExist.HilbertCircumcenter
import NonsoficGroupsExist.KazhdanFixedSpace
import NonsoficGroupsExist.HilbertConvexFixedPoint
import NonsoficGroupsExist.InvolutionSplitting
import NonsoficGroupsExist.FiniteInvolutionDecomposition
import NonsoficGroupsExist.HilbertEpsilonOrthogonality
import NonsoficGroupsExist.FiniteGroupAverage
import NonsoficGroupsExist.FiniteOrbitRepresentation
import NonsoficGroupsExist.FiniteClassTwoOrthogonality
import NonsoficGroupsExist.OrthogonalRepresentationDecomposition
import NonsoficGroupsExist.FiniteClassTwoDecompositionBound
import NonsoficGroupsExist.ClassTwoOrthogonality
import NonsoficGroupsExist.NormalEdgeCodistance
import NonsoficGroupsExist.KazhdanGenerators
import NonsoficGroupsExist.KazhdanOrthogonal
import NonsoficGroupsExist.KazhdanFiniteModel
import NonsoficGroupsExist.KazhdanGNS
import NonsoficGroupsExist.KunFiniteMarkov
import NonsoficGroupsExist.KunBoundary
import NonsoficGroupsExist.KunRounding
import NonsoficGroupsExist.KunThreshold
import NonsoficGroupsExist.KunGeneratorGraph
import NonsoficGroupsExist.KunSupport
import NonsoficGroupsExist.KunIndicatorRounding
import NonsoficGroupsExist.KunQuantitativeRounding
import NonsoficGroupsExist.KunRemoval
import NonsoficGroupsExist.KunAsymptoticRemoval
import NonsoficGroupsExist.KunSmallBoundary
import NonsoficGroupsExist.KunPartition
import NonsoficGroupsExist.KunFinitePartition
import NonsoficGroupsExist.KunDiagonalPartition
import NonsoficGroupsExist.KunDecomposition
import NonsoficGroupsExist.KunFixedDecomposition
import NonsoficGroupsExist.KunThomDiagonal
import NonsoficGroupsExist.KunThomCorrelation
import NonsoficGroupsExist.KunThomFiniteMarkov
import NonsoficGroupsExist.KunThomRounding
import NonsoficGroupsExist.KunThomParameters
import NonsoficGroupsExist.KunThomTheorem
import NonsoficGroupsExist.KunSpectralCounterexample
import NonsoficGroupsExist.MaximalCutRepair
import NonsoficGroupsExist.SoficRestriction
import NonsoficGroupsExist.EssentialExpanderRepair
import NonsoficGroupsExist.KunThomEssential
import NonsoficGroupsExist.KunPartitionBoundary
import NonsoficGroupsExist.KunPartitionCrossing
import NonsoficGroupsExist.KunBlockGraph
import NonsoficGroupsExist.KunRepairGraph
import NonsoficGroupsExist.KunMarkerSelection
import NonsoficGroupsExist.KunLocalNeighborhood
import NonsoficGroupsExist.KunBadBlocks
import NonsoficGroupsExist.KunSelectiveRepairGraph
import NonsoficGroupsExist.KunSelectiveRepairExpansion
import NonsoficGroupsExist.KunRefinedInvariance
import NonsoficGroupsExist.KunRepairExpansion
import NonsoficGroupsExist.KunUniformMovement
import NonsoficGroupsExist.KunUniformRemoval
import NonsoficGroupsExist.KunUniformRounding
import NonsoficGroupsExist.KunUniformDecompositionStep
import NonsoficGroupsExist.CompressionSetup
import NonsoficGroupsExist.LocalCriterion
import NonsoficGroupsExist.LocalizedApproximation
import NonsoficGroupsExist.SelectionOutput
import NonsoficGroupsExist.Pinning
import NonsoficGroupsExist.Refinement
import NonsoficGroupsExist.Selection
import NonsoficGroupsExist.MedianNormalization
import NonsoficGroupsExist.LEF
import NonsoficGroupsExist.ThompsonFObstruction
import NonsoficGroupsExist.Scheme
import NonsoficGroupsExist.Criterion
import NonsoficGroupsExist.BlockEnumeration
import NonsoficGroupsExist.BlockIndex
import NonsoficGroupsExist.ComponentDivergence
import NonsoficGroupsExist.GeneratorWords
import NonsoficGroupsExist.BlockWordCrossing
import NonsoficGroupsExist.BlockTransport
import NonsoficGroupsExist.ComponentRefinement
import NonsoficGroupsExist.DecompositionRefinement
import NonsoficGroupsExist.EdgeEditing
import NonsoficGroupsExist.GeneratorCrossing
import NonsoficGroupsExist.ExternalCompressorCrossing
import NonsoficGroupsExist.CompressionRefinement
import NonsoficGroupsExist.FiniteMedian
import NonsoficGroupsExist.NormalizedComponents
import NonsoficGroupsExist.ComponentPinning
import NonsoficGroupsExist.NormalizedVariation
import NonsoficGroupsExist.InverseNormalization
import NonsoficGroupsExist.GlobalVariation
import NonsoficGroupsExist.SlowThreshold
import NonsoficGroupsExist.FiniteMarkov
import NonsoficGroupsExist.MatchingPreparation
import NonsoficGroupsExist.MatchingSelection
import NonsoficGroupsExist.EdgeWitnessDistance
import NonsoficGroupsExist.EdgeWitnessRestriction
import NonsoficGroupsExist.GeneratorGraphEditing
import NonsoficGroupsExist.CompletionGraphEditing
import NonsoficGroupsExist.SelectedGraphComparison
import NonsoficGroupsExist.ConservativeMatching
import NonsoficGroupsExist.CriterionAssembly
import NonsoficGroupsExist.Leavitt
import NonsoficGroupsExist.UniversalLeavittOver
import NonsoficGroupsExist.LeavittNormalForm
import NonsoficGroupsExist.DiagonalClassGroup
import NonsoficGroupsExist.DiagonalDescent
import NonsoficGroupsExist.GLIsElementary
import NonsoficGroupsExist.LeavittDiagonalClass
import NonsoficGroupsExist.BinaryLeavittDiagonal
import NonsoficGroupsExist.StableUnitsGenerators
import NonsoficGroupsExist.FamilyDiagonalClass
import NonsoficGroupsExist.FieldMatrixReduction
import NonsoficGroupsExist.LeavittDegreeZero
import NonsoficGroupsExist.FamilyDescent
import NonsoficGroupsExist.LeavittGradingSpans
import NonsoficGroupsExist.MatrixDiagonalization
import NonsoficGroupsExist.LeavittSimplicity
import NonsoficGroupsExist.LeavittRankEquivalence
import NonsoficGroupsExist.FiniteGraph
import NonsoficGroupsExist.LeavittCorner
import NonsoficGroupsExist.LeavittMatrixCompression
import NonsoficGroupsExist.DiagonalCornerCompression
import NonsoficGroupsExist.DiagonalElementary
import NonsoficGroupsExist.LeavittSelfSimilarity
import NonsoficGroupsExist.Localization
import NonsoficGroupsExist.MatrixSelfSimilarity
import NonsoficGroupsExist.PermutationConservation
import NonsoficGroupsExist.Sofic
import NonsoficGroupsExist.SoficPositiveControl
import NonsoficGroupsExist.SemanticPositiveControls
import NonsoficGroupsExist.SoficErrors
import NonsoficGroupsExist.Whitehead
import NonsoficGroupsExist.KazhdanCover
import NonsoficGroupsExist.TableCover
import NonsoficGroupsExist.LeavittWords
import NonsoficGroupsExist.PrefixCode
import NonsoficGroupsExist.ElementaryGroup
import NonsoficGroupsExist.ElementaryRoots
import NonsoficGroupsExist.ElementaryStabilization
import NonsoficGroupsExist.RankFourCompressors
import NonsoficGroupsExist.UniversalLeavitt
import NonsoficGroupsExist.UniversalRankFour
import NonsoficGroupsExist.UniversalPropertyT
import NonsoficGroupsExist.UniversalCompressionSetup
import NonsoficGroupsExist.ThompsonV
import NonsoficGroupsExist.ThompsonVEmbedding
import NonsoficGroupsExist.ThompsonVWitness
import NonsoficGroupsExist.ThompsonWitness
import NonsoficGroupsExist.MatchedComponents
import NonsoficGroupsExist.SoficTransfer
import NonsoficGroupsExist.MainResults
import NonsoficGroupsExist.Audit

/-!
# An unconditional construction of a finitely presented nonsofic group

This library contains proved finite, asymptotic, Leavitt-family, elementary
matrix, non-LEF-obstruction, localization, and finite-table results. It proves
unconditionally that a nonsofic group exists and that a finitely presented
nonsofic group exists.

In particular, no declaration in this root module assumes a proposition named
after Kun, Kun--Thom, or Ershov--Jaikin and then advertises the resulting
parameterized implication as an existence theorem.  The uninstantiated
`ExpanderDecomposition`, `MatchingCertificate`, and `LocalCriterionData` are
specifications for intermediate mathematics, not proofs merely by being
inhabited in interface lemmas.  The exact full-sequence Kun decomposition
and Kun--Thom implication are now proved, as are property `(T)` for the
universal-Leavitt rank-three core and rank-four ambient group. `MainResults` assembles
them through the local criterion. Likewise,
`UniversalRankFour.compressionSetup` is an actual inhabitant of the algebraic
`CompressionSetup` interface.

The coefficient ring used by the headline group is now the actual universal
binary Leavitt algebra, defined as the presented quotient of the free algebra.
Its stream-operator representation proves that quotient nontrivial; no
faithfulness claim is needed. The two explicit
cylinder units prove a genuine finite non-LEF obstruction for their generated
corner subgroup; the development does not identify that subgroup with
Thompson's group `V`.  Their generated subgroup is now embedded in `EL₃` by
explicit cylinder-commutator and Whitehead identities.  The rank-four module
also proves compressor conjugation, ambient generation, centralization, and
trivial intersection, and `UniversalRankFour.compressionSetup` constructs the
complete algebraic setup rather than accepting it from a caller.

`MainResults.universalLeavittEL4_not_isSofic` supplies the initial
nonsofic group. `TableCover` then constructs its finitely presented nonsofic
cover, yielding the two premise-free public headline theorems in
`MainResults`.
-/
