import NonsoficGroupsExist.Sofic.Asymptotics
import NonsoficGroupsExist.Sofic.AlmostAutomorphism
import NonsoficGroupsExist.PropertyT.A2System
import NonsoficGroupsExist.PropertyT.A2ClassTwoOrthogonality
import NonsoficGroupsExist.PropertyT.A2MagicGraph
import NonsoficGroupsExist.PropertyT.A2MagicGraphEstimates
import NonsoficGroupsExist.PropertyT.A2MagicLaplacian
import NonsoficGroupsExist.PropertyT.A2MagicEnergy
import NonsoficGroupsExist.PropertyT.A2MagicHilbert
import NonsoficGroupsExist.Kazhdan.PositiveOperatorGap
import NonsoficGroupsExist.PropertyT.FreeAlgebraDegree
import NonsoficGroupsExist.PropertyT.FreeRootFiltration
import NonsoficGroupsExist.PropertyT.FreeRootActions
import NonsoficGroupsExist.PropertyT.FreeRootPlane
import NonsoficGroupsExist.PropertyT.FreeRootPlaneMassBase
import NonsoficGroupsExist.PropertyT.FreeRootPlaneMass
import NonsoficGroupsExist.PropertyT.FreeRootFunctionalValuation
import NonsoficGroupsExist.PropertyT.FreeRootPlaneFourier
import NonsoficGroupsExist.PropertyT.FreeRootCharacterValuationBase
import NonsoficGroupsExist.PropertyT.FreeRootCharacterValuation
import NonsoficGroupsExist.PropertyT.FiniteFieldElementaryPropertyT
import NonsoficGroupsExist.PropertyT.FreeElementaryPropertyT
import NonsoficGroupsExist.PropertyT.FiniteTypeCharacteristicTwoPropertyT
import NonsoficGroupsExist.Leavitt.FiniteFieldLeavitt
import NonsoficGroupsExist.PropertyT.A2Kazhdan
import NonsoficGroupsExist.PropertyT.ClassTwoNormalForm
import NonsoficGroupsExist.PropertyT.ClassTwoApproximation
import NonsoficGroupsExist.Matching.DirectedCoarea
import NonsoficGroupsExist.Kazhdan.KazhdanImprovement
import NonsoficGroupsExist.Kazhdan.Kazhdan
import NonsoficGroupsExist.Kazhdan.HilbertComplexification
import NonsoficGroupsExist.Kazhdan.KazhdanComplex
import NonsoficGroupsExist.Kazhdan.KazhdanUniverse
import NonsoficGroupsExist.Kazhdan.KazhdanFiniteGeneration
import NonsoficGroupsExist.PropertyT.CharacterMass
import NonsoficGroupsExist.Leavitt.RankTwoCompression
import NonsoficGroupsExist.Kazhdan.KazhdanControl
import NonsoficGroupsExist.Kazhdan.AlmostMinimalDisplacement
import NonsoficGroupsExist.Kazhdan.DelormeFixedPoint
import NonsoficGroupsExist.Kazhdan.ShalomFinitePresentation
import NonsoficGroupsExist.Kazhdan.UltralimitGeometry
import NonsoficGroupsExist.Kazhdan.GaussianPositiveDefinite
import NonsoficGroupsExist.Kazhdan.HilbertCircumcenter
import NonsoficGroupsExist.Kazhdan.KazhdanFixedSpace
import NonsoficGroupsExist.Kazhdan.HilbertConvexFixedPoint
import NonsoficGroupsExist.PropertyT.InvolutionSplitting
import NonsoficGroupsExist.PropertyT.FiniteInvolutionDecomposition
import NonsoficGroupsExist.Kazhdan.HilbertEpsilonOrthogonality
import NonsoficGroupsExist.PropertyT.FiniteGroupAverage
import NonsoficGroupsExist.PropertyT.FiniteOrbitRepresentation
import NonsoficGroupsExist.PropertyT.FiniteClassTwoOrthogonality
import NonsoficGroupsExist.PropertyT.OrthogonalRepresentationDecomposition
import NonsoficGroupsExist.PropertyT.FiniteClassTwoDecompositionBound
import NonsoficGroupsExist.PropertyT.ClassTwoOrthogonality
import NonsoficGroupsExist.PropertyT.NormalEdgeCodistance
import NonsoficGroupsExist.Kazhdan.KazhdanGenerators
import NonsoficGroupsExist.Kazhdan.KazhdanOrthogonal
import NonsoficGroupsExist.Kazhdan.KazhdanFiniteModel
import NonsoficGroupsExist.Kazhdan.KazhdanGNS
import NonsoficGroupsExist.Kun.KunFiniteMarkov
import NonsoficGroupsExist.Kun.KunBoundary
import NonsoficGroupsExist.Kun.KunRounding
import NonsoficGroupsExist.Kun.KunThreshold
import NonsoficGroupsExist.Kun.KunGeneratorGraph
import NonsoficGroupsExist.Kun.KunSupport
import NonsoficGroupsExist.Kun.KunIndicatorRounding
import NonsoficGroupsExist.Kun.KunQuantitativeRounding
import NonsoficGroupsExist.Kun.KunRemoval
import NonsoficGroupsExist.Kun.KunAsymptoticRemoval
import NonsoficGroupsExist.Kun.KunSmallBoundary
import NonsoficGroupsExist.Kun.KunPartition
import NonsoficGroupsExist.Kun.KunFinitePartition
import NonsoficGroupsExist.Kun.KunDiagonalPartition
import NonsoficGroupsExist.Kun.KunDecomposition
import NonsoficGroupsExist.Kun.KunFixedDecomposition
import NonsoficGroupsExist.KunThom.KunThomDiagonal
import NonsoficGroupsExist.KunThom.KunThomCorrelation
import NonsoficGroupsExist.KunThom.KunThomFiniteMarkov
import NonsoficGroupsExist.KunThom.KunThomRounding
import NonsoficGroupsExist.KunThom.KunThomParameters
import NonsoficGroupsExist.KunThom.KunThomTheorem
import NonsoficGroupsExist.Kun.KunSpectralCounterexample
import NonsoficGroupsExist.Matching.MaximalCutRepair
import NonsoficGroupsExist.Sofic.SoficRestriction
import NonsoficGroupsExist.Matching.EssentialExpanderRepair
import NonsoficGroupsExist.KunThom.KunThomEssential
import NonsoficGroupsExist.Kun.KunPartitionBoundary
import NonsoficGroupsExist.Kun.KunPartitionCrossing
import NonsoficGroupsExist.Kun.KunBlockGraph
import NonsoficGroupsExist.Kun.KunRepairGraph
import NonsoficGroupsExist.Kun.KunMarkerSelection
import NonsoficGroupsExist.Kun.KunLocalNeighborhood
import NonsoficGroupsExist.Kun.KunBadBlocks
import NonsoficGroupsExist.Kun.KunSelectiveRepairGraph
import NonsoficGroupsExist.Kun.KunSelectiveRepairExpansion
import NonsoficGroupsExist.Kun.KunRefinedInvariance
import NonsoficGroupsExist.Kun.KunRepairExpansion
import NonsoficGroupsExist.Kun.KunUniformMovement
import NonsoficGroupsExist.Kun.KunUniformRemoval
import NonsoficGroupsExist.Kun.KunUniformRounding
import NonsoficGroupsExist.Kun.KunUniformDecompositionStep
import NonsoficGroupsExist.Criterion.CompressionSetup
import NonsoficGroupsExist.Criterion.LocalCriterion
import NonsoficGroupsExist.Criterion.LocalizedApproximation
import NonsoficGroupsExist.Criterion.SelectionOutput
import NonsoficGroupsExist.Matching.Pinning
import NonsoficGroupsExist.Matching.Refinement
import NonsoficGroupsExist.Matching.Selection
import NonsoficGroupsExist.Matching.MedianNormalization
import NonsoficGroupsExist.Sofic.LEF
import NonsoficGroupsExist.Sofic.FinitelyPresentedLEF
import NonsoficGroupsExist.Sofic.ThompsonFObstruction
import NonsoficGroupsExist.Criterion.Scheme
import NonsoficGroupsExist.Criterion.Criterion
import NonsoficGroupsExist.Matching.BlockEnumeration
import NonsoficGroupsExist.Matching.BlockIndex
import NonsoficGroupsExist.Matching.ComponentDivergence
import NonsoficGroupsExist.Matching.GeneratorWords
import NonsoficGroupsExist.Matching.BlockWordCrossing
import NonsoficGroupsExist.Matching.BlockTransport
import NonsoficGroupsExist.Matching.ComponentRefinement
import NonsoficGroupsExist.Matching.DecompositionRefinement
import NonsoficGroupsExist.Matching.EdgeEditing
import NonsoficGroupsExist.Matching.GeneratorCrossing
import NonsoficGroupsExist.Matching.ExternalCompressorCrossing
import NonsoficGroupsExist.Matching.CompressionRefinement
import NonsoficGroupsExist.Matching.FiniteMedian
import NonsoficGroupsExist.Matching.NormalizedComponents
import NonsoficGroupsExist.Matching.ComponentPinning
import NonsoficGroupsExist.Matching.NormalizedVariation
import NonsoficGroupsExist.Matching.InverseNormalization
import NonsoficGroupsExist.Matching.GlobalVariation
import NonsoficGroupsExist.Matching.SlowThreshold
import NonsoficGroupsExist.Matching.FiniteMarkov
import NonsoficGroupsExist.Matching.MatchingPreparation
import NonsoficGroupsExist.Matching.MatchingSelection
import NonsoficGroupsExist.Matching.EdgeWitnessDistance
import NonsoficGroupsExist.Matching.EdgeWitnessRestriction
import NonsoficGroupsExist.Matching.GeneratorGraphEditing
import NonsoficGroupsExist.Matching.CompletionGraphEditing
import NonsoficGroupsExist.Matching.SelectedGraphComparison
import NonsoficGroupsExist.Matching.ConservativeMatching
import NonsoficGroupsExist.Criterion.CriterionAssembly
import NonsoficGroupsExist.Leavitt.Leavitt
import NonsoficGroupsExist.Leavitt.AryCorner
import NonsoficGroupsExist.Leavitt.FamilyRankFour
import NonsoficGroupsExist.Leavitt.RawSwapCompressors
import NonsoficGroupsExist.Leavitt.LeavittOverCommRing
import NonsoficGroupsExist.Leavitt.IntegralGeneration
import NonsoficGroupsExist.Leavitt.ElementaryPerfect
import NonsoficGroupsExist.Leavitt.AryProfile
import NonsoficGroupsExist.Leavitt.SelfSimilarityAlgebra
import NonsoficGroupsExist.Leavitt.PlaneEmbedding
import NonsoficGroupsExist.Leavitt.GeneralRankWords
import NonsoficGroupsExist.Leavitt.GeneralScheme
import NonsoficGroupsExist.Leavitt.GeneralCornerTheorem
import NonsoficGroupsExist.Sofic.LEFSofic
import NonsoficGroupsExist.Sofic.FreeGroupResiduallyFinite
import NonsoficGroupsExist.Endpoint.QuotientNonclosure
import NonsoficGroupsExist.Leavitt.AryLeavitt
import NonsoficGroupsExist.Leavitt.AryCornerMatrix
import NonsoficGroupsExist.Leavitt.AryEndpoints
import NonsoficGroupsExist.Leavitt.UniversalLeavittOver
import NonsoficGroupsExist.Leavitt.LeavittNormalForm
import NonsoficGroupsExist.Leavitt.DiagonalClassGroup
import NonsoficGroupsExist.KOne.GLIsElementary
import NonsoficGroupsExist.Leavitt.LeavittDiagonalClass
import NonsoficGroupsExist.Leavitt.BinaryLeavittDiagonal
import NonsoficGroupsExist.KOne.StableUnitsGenerators
import NonsoficGroupsExist.Leavitt.FamilyDiagonalClass
import NonsoficGroupsExist.KOne.FieldMatrixReduction
import NonsoficGroupsExist.Leavitt.LeavittDegreeZero
import NonsoficGroupsExist.Leavitt.FamilyDescent
import NonsoficGroupsExist.Leavitt.LeavittGradingSpans
import NonsoficGroupsExist.Leavitt.LeavittBalancedUnits
import NonsoficGroupsExist.Leavitt.LeavittWindowReduction
import NonsoficGroupsExist.Leavitt.BinaryLeavittWindow
import NonsoficGroupsExist.KOne.ScaledStreamRepresentation
import NonsoficGroupsExist.KOne.VandermondeExtraction
import NonsoficGroupsExist.KOne.GradedIndependence
import NonsoficGroupsExist.KOne.BaseChangeIndependence
import NonsoficGroupsExist.KOne.StableRankOne
import NonsoficGroupsExist.KOne.BalancedStableRank
import NonsoficGroupsExist.Leavitt.WhiteheadFlip
import NonsoficGroupsExist.KOne.ResidualNormalForm
import NonsoficGroupsExist.KOne.ResidualMoves
import NonsoficGroupsExist.KOne.ResidualReduction
import NonsoficGroupsExist.KOne.BalancedRegularity
import NonsoficGroupsExist.KOne.WindowProductClosure
import NonsoficGroupsExist.KOne.NilpotentTailKill
import NonsoficGroupsExist.KOne.IncomparableUnipotents
import NonsoficGroupsExist.KOne.ShapeCalculus
import NonsoficGroupsExist.KOne.GradedComponents
import NonsoficGroupsExist.KOne.PureTailNilpotency
import NonsoficGroupsExist.Leavitt.RankNormalForm
import NonsoficGroupsExist.KOne.DegreeShapeBridge
import NonsoficGroupsExist.KOne.CylinderCornerRank
import NonsoficGroupsExist.KOne.ZeroKOne
import NonsoficGroupsExist.KOne.WidthTwoReduction
import NonsoficGroupsExist.KOne.WindowNonnegReduction
import NonsoficGroupsExist.KOne.OppositeTranspose
import NonsoficGroupsExist.KOne.ThetaStable
import NonsoficGroupsExist.KOne.WindowNonposReduction
import NonsoficGroupsExist.KOne.CodeChangeInfrastructure
import NonsoficGroupsExist.KOne.CodeChangeSwap
import NonsoficGroupsExist.KOne.CodeChangeUnits
import NonsoficGroupsExist.KOne.PencilCore
import NonsoficGroupsExist.KOne.PencilForm
import NonsoficGroupsExist.KOne.CodePairTransport
import NonsoficGroupsExist.KOne.CodeScalarMoves
import NonsoficGroupsExist.KOne.CodeRelativeFullness
import NonsoficGroupsExist.KOne.CodeChangeGlue
import NonsoficGroupsExist.KOne.AtomPeel
import NonsoficGroupsExist.KOne.MixedCodeMoves
import NonsoficGroupsExist.KOne.GLPairNormalization
import NonsoficGroupsExist.KOne.PencilEntryArith
import NonsoficGroupsExist.KOne.CompleteCodeSupply
import NonsoficGroupsExist.KOne.GLVectorNormalization
import NonsoficGroupsExist.KOne.RowClearMove
import NonsoficGroupsExist.KOne.FullExtraction
import NonsoficGroupsExist.KOne.MirrorExtraction
import NonsoficGroupsExist.KOne.EntryStrip
import NonsoficGroupsExist.KOne.EntrywiseKill
import NonsoficGroupsExist.KOne.StackDichotomy
import NonsoficGroupsExist.KOne.RefinedCodes
import NonsoficGroupsExist.KOne.BalancedCodePencil
import NonsoficGroupsExist.KOne.EntrywiseKillMirror
import NonsoficGroupsExist.KOne.RefineStep
import NonsoficGroupsExist.KOne.StrictNegativePencil
import NonsoficGroupsExist.KOne.CodeShapeSupply
import NonsoficGroupsExist.KOne.PencilReshape
import NonsoficGroupsExist.KOne.RefineLoopDischarge
import NonsoficGroupsExist.Leavitt.MatrixDiagonalization
import NonsoficGroupsExist.Leavitt.LeavittSimplicity
import NonsoficGroupsExist.Leavitt.LeavittRankEquivalence
import NonsoficGroupsExist.Matching.FiniteGraph
import NonsoficGroupsExist.Leavitt.LeavittCorner
import NonsoficGroupsExist.Leavitt.LeavittMatrixCompression
import NonsoficGroupsExist.Leavitt.DiagonalCornerCompression
import NonsoficGroupsExist.Leavitt.DiagonalElementary
import NonsoficGroupsExist.Leavitt.LeavittSelfSimilarity
import NonsoficGroupsExist.Matching.Localization
import NonsoficGroupsExist.Leavitt.MatrixSelfSimilarity
import NonsoficGroupsExist.Matching.PermutationConservation
import NonsoficGroupsExist.Sofic.Sofic
import NonsoficGroupsExist.Sofic.SoficPositiveControl
import NonsoficGroupsExist.Sofic.SemanticPositiveControls
import NonsoficGroupsExist.Sofic.SoficErrors
import NonsoficGroupsExist.Sofic.Normalization
import NonsoficGroupsExist.Leavitt.Whitehead
import NonsoficGroupsExist.Covers.KazhdanCover
import NonsoficGroupsExist.Covers.TableCover
import NonsoficGroupsExist.Leavitt.LeavittWords
import NonsoficGroupsExist.Leavitt.PrefixCode
import NonsoficGroupsExist.Leavitt.ElementaryGroup
import NonsoficGroupsExist.Leavitt.ElementaryRoots
import NonsoficGroupsExist.Leavitt.ElementaryStabilization
import NonsoficGroupsExist.Leavitt.RankFourCompressors
import NonsoficGroupsExist.Leavitt.UniversalLeavitt
import NonsoficGroupsExist.Leavitt.UniversalRankFour
import NonsoficGroupsExist.Leavitt.UniversalPropertyT
import NonsoficGroupsExist.Leavitt.UniversalCompressionSetup
import NonsoficGroupsExist.Leavitt.ThompsonV
import NonsoficGroupsExist.Leavitt.ThompsonVEmbedding
import NonsoficGroupsExist.Leavitt.FamilyVEmbedding
import NonsoficGroupsExist.Leavitt.ThompsonVWitness
import NonsoficGroupsExist.Leavitt.ThompsonWitness
import NonsoficGroupsExist.Matching.MatchedComponents
import NonsoficGroupsExist.Sofic.SoficTransfer
import NonsoficGroupsExist.Endpoint.MainResults
import NonsoficGroupsExist.Leavitt.UnitsGLProfile
import NonsoficGroupsExist.KOne.AllRanksElementary
import NonsoficGroupsExist.Kazhdan.KazhdanTextbook
import NonsoficGroupsExist.Monsters.Terminality
import NonsoficGroupsExist.Monsters.TwoConjugacyClasses
import NonsoficGroupsExist.Monsters.VerbalCompleteness
import NonsoficGroupsExist.Monsters.Protection
import NonsoficGroupsExist.Endpoint.Audit
import NonsoficGroupsExist.Endpoint.Public

/-!
# An unconditional construction of a finitely presented nonsofic group

This library proves that a nonsofic group exists, and that a finitely
presented one does.  Both are closed theorems: neither takes a hypothesis
standing in for a construction, and neither is a parameterized implication
advertised as an existence result.

**Start at `NonsoficGroupsExist.Public`.**  It is the reading path -- the
declarations a referee needs, each named against the theorem of
`nonsofic_groups_exist.tex` it establishes.  The statement-by-statement
correspondence with the manuscript is `docs/CLAIM_MAP.md`, generated from the
paper's own margin notes and checked on every build.

## What is proved here rather than assumed

The paper cites four external theorems; three of them are proved in this
library, so they are inputs to the manuscript and not to the development:
Kun's expander decomposition (`KunDecomposition`), the Kun--Thom centralizer
obstruction (`KunThomTheorem`), and Shalom's finitely presented Kazhdan covers
(`ShalomFinitePresentation`).  The fourth, property `(T)` for elementary
groups over arbitrary finitely generated rings, is imported; the
characteristic-two cases the endpoints use are proved in
`FreeElementaryPropertyT`.

The `K₁`-theoretic input is likewise eliminated: `BinaryLeavitt.K1_trivial`
proves `K₁(L_k(1,2)) = 0` in Whitehead form by an elementary two-exit
elimination, so the localization-sequence citation is confirmation rather than
dependency.

## The construction

The coefficient ring is the actual universal binary Leavitt algebra, defined
as the presented quotient of the free algebra; its stream-operator
representation proves that quotient nontrivial, so no faithfulness claim is
needed.  `UniversalRankFour.compressionSetup` constructs the algebraic setup
rather than accepting it from a caller, and the corner subgroup carrying the
non-LEF obstruction is identified with Thompson's group `V`
(`ThompsonVWitness.thompsonV_not_isLEF`), proved non-LEF unconditionally with
no Higman presentation input.

`MainResults.universalLeavittEL4_not_isSofic` supplies the initial nonsofic
group; `TableCover` builds its finitely presented cover, and `KazhdanCover`
the Kazhdan one.

## Trust surface

`NonsoficGroupsExist.Audit` prints the axiom report for the public results on
an ordinary build.  `scripts/Audit.lean` independently walks the transitive
axiom closure of the whole namespace and fails on anything beyond `propext`,
`Classical.choice`, and `Quot.sound`; `scripts/check.py` scans the source text
for what the kernel cannot see, including files that are never compiled.
-/
