import Lean

/-!
# One answer to "did a person write this declaration"

Adapted from gnomon's `proofs/validation/Shared/DeclFilter.lean`, which exists
because three detectors in that repository each carried a private copy of this
filter and no two agreed — so the tools reported totals over different
populations while looking equally authoritative.

Every scan in `Audit.Scan` asks this module and only this module.  A second
private copy of any predicate here is the defect this file was created to
prevent.

It imports `Lean` and nothing else, deliberately: it must never depend on the
corpus it audits, or it could not be loaded before that corpus builds.
-/

open Lean

namespace Audit

/-- Final name components Lean generates for an inductive type or structure,
which no author types.  One line per entry with the reason, because a filter
nobody can audit is how the copies drifted apart in the first place.

* `mk`               — the constructor, synthesised with the structure.
* `injEq`            — constructor injectivity, `S.mk a = S.mk b ↔ a = b`.
* `eta`              — the eta rule for the structure.
* `sizeOf`           — the `SizeOf` measure used for termination.
* `sizeOf_spec`      — its defining equation.
* `noConfusion`      — distinct constructors are unequal.
* `noConfusionType`  — the motive `noConfusion` eliminates into.
* `rec`              — the primitive recursor.
* `ndrec`            — its non-dependent form.
* `recOn`            — the recursor with the major premise moved first.
* `casesOn`          — the recursor restricted to case analysis.
* `brecOn`           — the course-of-values recursor for structural recursion.
* `below`            — the motive `brecOn` recurses over.
* `toCtorIdx`        — the constructor index, generated for enumerations.
* `ofNat`            — the `OfNat` instance field for numeric literals.
* `ext`              — extensionality, generated by the `@[ext]` machinery.
* `ext_iff`          — its iff form, generated alongside.
* `congr_simp`       — the congruence lemma `simp` generates for a function.
* `congr`            — the same, in its unsimplified form.
* `eq_mp`/`eq_mpr`   — generated transport lemmas.
-/
def generatedComponents : List String :=
  ["mk", "injEq", "eta", "sizeOf", "sizeOf_spec", "noConfusion", "noConfusionType",
   "rec", "ndrec", "recOn", "casesOn", "brecOn", "below", "toCtorIdx", "ofNat",
   "ext", "ext_iff", "congr_simp", "congr", "eq_mp", "eq_mpr"]

/-- Is this final name component an equation lemma Lean generated for a
definition?  Lean emits `f.eq_1`, `f.eq_2`, … per branch, plus `f.eq_def` and
`f.eq_unfold` for the unfolding rule.  They are `rfl` by construction and answer
a different question than "which hand-written theorems close by `rfl`".

NOT a blanket `startsWith "eq_"`.  That also swallows hand-written theorems
named `eq_of_…`, `eq_zero_of_…`, and silently drops them from every scan —
which, for an axiom guard, is the exact opposite of the intent.  The
digits-or-`def`-or-`unfold` test catches the generated lemmas and none of those. -/
def isEquationLemma (component : String) : Bool :=
  component == "eq_def" || component == "eq_unfold" ||
    (component.startsWith "eq_" &&
      (let rest := component.drop 3
       !rest.isEmpty && rest.all Char.isDigit))

/-- Lemmas Lean generates about a structure's constructor: `S.mk.inj`,
`S.mk.injEq`, `S.mk.sizeOf_spec`.

Matched on the PARENT component rather than the final one.  `inj` is an
ordinary word a person could end a theorem name with, so it cannot go in
`generatedComponents`; and leaving `S.mk.inj` in the population is not
cosmetic — its premises are the structure's own fields, so every field of
every `Prop`-carrying structure gets reported as a smuggled premise. -/
def isConstructorLemma : Name → Bool
  | .str (.str _ "mk") f => f == "inj" || f == "injEq" || f == "sizeOf_spec"
  | _ => false

/-- Was this declaration generated by Lean rather than written by a person?

1. `Name.isInternalDetail` — macro scopes, `_private.…`, Lean's internal naming.
2. `Environment.isProjectionFn` — a structure field accessor.  Its value *is*
   the projection, necessarily; counting that as an author asserting something
   is a category error.
3. `proof_` / `match_` prefixes — obligations and match auxiliaries Lean lifts
   out of a definition.
4. `isEquationLemma`, `isConstructorLemma`, `generatedComponents` — above.
5. Any name that is not `.str`, i.e. anonymous or numeric.  Nothing an author
   typed has such a name, and `Name.getString!` panics on them. -/
def isGenerated (env : Environment) (n : Name) : Bool :=
  n.isInternalDetail
    || env.isProjectionFn n
    || isConstructorLemma n
    || (match n with
        | .str _ f =>
            f.startsWith "proof_" || f.startsWith "match_"
              || isEquationLemma f || generatedComponents.contains f
        | _ => true)

/-- Was this declaration written by a person?  The negation of `isGenerated`. -/
def userWritten (env : Environment) (n : Name) : Bool :=
  !isGenerated env n

end Audit
