import NonsoficGroupsExist.ElementaryRoots
import NonsoficGroupsExist.ClassTwoNormalForm
import Mathlib.GroupTheory.Commutator.Basic

/-!
# Root-subgroup systems of type A₂

The six ordered roots of `A₂` are indexed by distinct pairs in `Fin 3`.
This file records the algebraic hypotheses used by the EJZ magic-graph
argument and proves them for elementary groups over every associative ring.
-/

namespace NonsoficGroupsExist

open scoped commutatorElement

/-- The six ordered roots of type `A₂`. -/
abbrev A2Root := {p : Fin 3 × Fin 3 // p.1 ≠ p.2}

/-- The third coordinate distinct from a given ordered pair.  Values on the
diagonal are irrelevant; the root-indexed lemmas below always assume the two
inputs are distinct. -/
def a2ThirdIndex (i j : Fin 3) : Fin 3 :=
  ![![0, 2, 1], ![2, 1, 0], ![1, 0, 2]] i j

@[simp] theorem a2ThirdIndex_ne_left (i j : Fin 3) (hij : i ≠ j) :
    a2ThirdIndex i j ≠ i := by
  fin_cases i <;> fin_cases j <;> simp_all [a2ThirdIndex]

@[simp] theorem a2ThirdIndex_ne_right (i j : Fin 3) (hij : i ≠ j) :
    a2ThirdIndex i j ≠ j := by
  fin_cases i <;> fin_cases j <;> simp_all [a2ThirdIndex]

/-- A strongly graded `A₂` root-subgroup system: the six subgroups generate,
non-addable roots commute, commutators of consecutive roots land in their sum
root, and every element of a sum root is such a commutator.  The final field is
the strong-grading hypothesis required by the EJZ Kazhdan-subset argument. -/
structure A2System (G : Type*) [Group G] where
  root : ∀ (i j : Fin 3), i ≠ j → Subgroup G
  generate : Subgroup.closure
    {g | ∃ (i j : Fin 3) (hij : i ≠ j), g ∈ root i j hij} = ⊤
  commute : ∀ (i j k l : Fin 3)
    (hij : i ≠ j) (hkl : k ≠ l), j ≠ k → l ≠ i →
      ∀ x ∈ root i j hij, ∀ y ∈ root k l hkl, Commute x y
  commutator_mem : ∀ (i j k : Fin 3)
    (hij : i ≠ j) (hjk : j ≠ k) (hik : i ≠ k),
      ∀ x ∈ root i j hij, ∀ y ∈ root j k hjk,
        ⁅x, y⁆ ∈ root i k hik
  commutator_surjective : ∀ (i j k : Fin 3)
    (hij : i ≠ j) (hjk : j ≠ k) (hik : i ≠ k),
      ∀ z ∈ root i k hik,
        ∃ x ∈ root i j hij, ∃ y ∈ root j k hjk, ⁅x, y⁆ = z

namespace A2System

variable {G : Type*} [Group G]

/-- A root subgroup indexed by the finite type of six ordered roots. -/
def rootAt (A : A2System G) (a : A2Root) : Subgroup G :=
  A.root a.1.1 a.1.2 a.2

/-- The class-two vertex subgroup associated with an ordered root `(i,j)`,
generated by the two root groups through the third coordinate `k`. -/
def vertexGroup (A : A2System G) (a : A2Root) : Subgroup G :=
  let i := a.1.1
  let j := a.1.2
  let k := a2ThirdIndex i j
  A.root i k (a2ThirdIndex_ne_left i j a.2).symm ⊔
    A.root k j (a2ThirdIndex_ne_right i j a.2)

theorem leftRoot_le_vertexGroup (A : A2System G) (a : A2Root) :
    A.root a.1.1 (a2ThirdIndex a.1.1 a.1.2)
        (a2ThirdIndex_ne_left a.1.1 a.1.2 a.2).symm ≤
      A.vertexGroup a := le_sup_left

theorem rightRoot_le_vertexGroup (A : A2System G) (a : A2Root) :
    A.root (a2ThirdIndex a.1.1 a.1.2) a.1.2
        (a2ThirdIndex_ne_right a.1.1 a.1.2 a.2) ≤
      A.vertexGroup a := le_sup_right

/-- Strong grading puts the sum root inside its associated vertex group. -/
theorem rootAt_le_vertexGroup (A : A2System G) (a : A2Root) :
    A.rootAt a ≤ A.vertexGroup a := by
  intro z hz
  let i := a.1.1
  let j := a.1.2
  let k := a2ThirdIndex i j
  have hik : i ≠ k := (a2ThirdIndex_ne_left i j a.2).symm
  have hkj : k ≠ j := a2ThirdIndex_ne_right i j a.2
  obtain ⟨x, hx, y, hy, rfl⟩ :=
    A.commutator_surjective i k j hik hkj a.2 z hz
  have hxV := A.leftRoot_le_vertexGroup a hx
  have hyV := A.rightRoot_le_vertexGroup a hy
  exact (A.vertexGroup a).mul_mem
    ((A.vertexGroup a).mul_mem
      ((A.vertexGroup a).mul_mem hxV hyV)
    ((A.vertexGroup a).inv_mem hxV))
    ((A.vertexGroup a).inv_mem hyV)

/-- Every element of a magic-graph vertex group is a product of one element
from each of its two generating roots followed by one element of the sum
root.  This is the three-factor decomposition used to transfer displacement
bounds from root groups to vertex groups. -/
theorem exists_vertexGroup_three_factor (A : A2System G) (a : A2Root)
    {g : G} (hg : g ∈ A.vertexGroup a) :
    let i := a.1.1
    let j := a.1.2
    let k := a2ThirdIndex i j
    ∃ x ∈ A.root i k (a2ThirdIndex_ne_left i j a.2).symm,
      ∃ y ∈ A.root k j (a2ThirdIndex_ne_right i j a.2),
        ∃ z ∈ A.rootAt a, x * y * z = g := by
  let i := a.1.1
  let j := a.1.2
  let k := a2ThirdIndex i j
  have hik : i ≠ k := (a2ThirdIndex_ne_left i j a.2).symm
  have hkj : k ≠ j := a2ThirdIndex_ne_right i j a.2
  let X := A.root i k hik
  let Y := A.root k j hkj
  let Z := A.rootAt a
  have hYX : ⁅Y, X⁆ ≤ Z := by
    apply Subgroup.commutator_le.mpr
    intro y hy x hx
    have hxy : ⁅x, y⁆ ∈ Z := A.commutator_mem i k j hik hkj a.2 x hx y hy
    rw [← commutatorElement_inv x y]
    exact Z.inv_mem hxy
  have hXZ : ⁅X, Z⁆ ≤ Z := by
    apply Subgroup.commutator_le.mpr
    intro x hx z hz
    have hcomm : Commute x z :=
      A.commute i k i j hik a.2
        (a2ThirdIndex_ne_left i j a.2) a.2.symm x hx z hz
    rw [commutatorElement_eq_one_iff_commute.mpr hcomm]
    exact Z.one_mem
  have hYZ : ⁅Y, Z⁆ ≤ Z := by
    apply Subgroup.commutator_le.mpr
    intro y hy z hz
    have hcomm : Commute y z :=
      A.commute k j i j hkj a.2 a.2.symm hkj.symm y hy z hz
    rw [commutatorElement_eq_one_iff_commute.mpr hcomm]
    exact Z.one_mem
  exact ClassTwoNormalForm.exists_three_factor X Y Z hYX hXZ hYZ
    (A.rootAt_le_vertexGroup a) hg

/-- The union of the six root subgroups. -/
def rootSet (A : A2System G) : Set G :=
  {g | ∃ (i j : Fin 3) (hij : i ≠ j), g ∈ A.root i j hij}

/-- The union of the six class-two vertex groups in the magic graph. -/
def vertexSet (A : A2System G) : Set G :=
  {g | ∃ a : A2Root, g ∈ A.vertexGroup a}

theorem mem_rootSet_iff (A : A2System G) (g : G) :
    g ∈ A.rootSet ↔ ∃ a : A2Root, g ∈ A.rootAt a := by
  constructor
  · rintro ⟨i, j, hij, hg⟩
    exact ⟨⟨(i, j), hij⟩, hg⟩
  · rintro ⟨⟨⟨i, j⟩, hij⟩, hg⟩
    exact ⟨i, j, hij, hg⟩

theorem rootSet_generate (A : A2System G) :
    Subgroup.closure A.rootSet = ⊤ := A.generate

/-- Each root subgroup in an `A₂` system is abelian.  This is a consequence
of the non-addable-root commutation axiom, not an additional assumption. -/
theorem root_commute (A : A2System G) (i j : Fin 3) (hij : i ≠ j) :
    ∀ x ∈ A.root i j hij, ∀ y ∈ A.root i j hij, Commute x y := by
  exact A.commute i j i j hij hij hij.symm hij.symm

end A2System

/-- Elementary matrices in rank three form an `A₂` system, with every
axiom discharged by explicit matrix identities. -/
def elementaryA2System (R : Type*) [Ring R] :
    A2System (elementaryGroup (Fin 3) R) where
  root := fun i j hij ↦ elementaryRootSubgroup i j hij
  generate := by
    exact elementaryRootSet_generate
  commute := by
    intro i j k l hij hkl hjk hli x hx y hy
    obtain ⟨a, rfl⟩ := hx
    obtain ⟨b, rfl⟩ := hy
    exact elementaryRoot_commute_of_ne i j k l hij hkl hjk hli a b
  commutator_mem := by
    intro i j k hij hjk hik x hx y hy
    obtain ⟨a, rfl⟩ := hx
    obtain ⟨b, rfl⟩ := hy
    exact ⟨a * b, (elementaryRoot_commutator i j k hij hjk hik a b).symm⟩
  commutator_surjective := by
    intro i j k hij hjk hik z hz
    obtain ⟨a, rfl⟩ := hz
    refine ⟨elementaryRoot i j hij a, ⟨a, rfl⟩,
      elementaryRoot j k hjk 1, ⟨1, rfl⟩, ?_⟩
    simpa using elementaryRoot_commutator i j k hij hjk hik a 1

end NonsoficGroupsExist
