import NonsoficGroupsExist.MainResults
import NonsoficGroupsExist.SoficPositiveControl
import NonsoficGroupsExist.KunDecomposition
import NonsoficGroupsExist.KunThomTheorem
import NonsoficGroupsExist.FreeElementaryPropertyT
import NonsoficGroupsExist.KazhdanComplex
import NonsoficGroupsExist.KazhdanUniverse

/-!
# Human-readable axiom report

This module pins the axiom reports for the public results and the three most
load-bearing mathematical inputs.  It is imported by the library root, so a
normal `lake build` prints these reports.  The stricter executable gate in
`scripts/Audit.lean` independently traverses the transitive axiom closure of
the entire project namespace and fails on anything beyond classical Lean.
-/

#print axioms NonsoficGroupsExist.nonsofic_groups_exist
#print axioms NonsoficGroupsExist.universalLeavittEL4_not_isSofic
#print axioms NonsoficGroupsExist.universalLeavittEL3_not_isSofic
#print axioms NonsoficGroupsExist.universalLeavittUnits_not_isSofic
#print axioms NonsoficGroupsExist.universalLeavittGL_not_isSofic
#print axioms NonsoficGroupsExist.ambient_profile
#print axioms NonsoficGroupsExist.ambient_full_profile
#print axioms NonsoficGroupsExist.universalLeavitt_profile
#print axioms NonsoficGroupsExist.binaryLeavitt_finiteField_profile
#print axioms NonsoficGroupsExist.exists_finitelyPresented_nonsofic_group
#print axioms NonsoficGroupsExist.exists_infinite_finitelyPresented_nonsofic_ambient_cover
#print axioms NonsoficGroupsExist.KunDecomposition.exists_expanderDecomposition
#print axioms NonsoficGroupsExist.KunSelectiveRepairExpansion.refined_bad_component_expands_at_every_positive_constant
#print axioms NonsoficGroupsExist.KunThomTheorem.isLEF_of_exactProductExpansion
#print axioms NonsoficGroupsExist.FreeElementaryPropertyT.freeElementary_hasKazhdanPropertyT
#print axioms NonsoficGroupsExist.UniversalRankFour.witness_not_isLEF
#print axioms NonsoficGroupsExist.ThompsonFObstruction.finite_image_generatorCommutator_eq_one
#print axioms NonsoficGroupsExist.isSofic_of_finite
#print axioms NonsoficGroupsExist.isSofic_multiplicative_int
#print axioms NonsoficGroupsExist.isSofic_iff_productRestricted
#print axioms NonsoficGroupsExist.isLEF_of_finite
#print axioms NonsoficGroupsExist.isLEF_multiplicative_int
#print axioms NonsoficGroupsExist.isLEF_iff_textbook
#print axioms NonsoficGroupsExist.isKazhdanPair_iff_complex
#print axioms NonsoficGroupsExist.hasKazhdanPropertyT_iff_complex
#print axioms NonsoficGroupsExist.IsKazhdanPair.liftUniverse
#print axioms NonsoficGroupsExist.HasKazhdanPropertyT.liftUniverse
#print axioms NonsoficGroupsExist.IsKazhdanPair.lowerUniverse
#print axioms NonsoficGroupsExist.hasKazhdanPropertyT_universe_iff
#print axioms NonsoficGroupsExist.hasKazhdanPropertyT_iff_textbook
