import NonsoficGroupsExist.HilbertEpsilonOrthogonality
import NonsoficGroupsExist.KazhdanFixedSpace

/-!
# Finite-stage approximation for two generated subgroups

The universal class-two orthogonality theorem of Ershov--Jaikin-Zapirain is
obtained from its finitely generated case by enlarging finite subsets of the
two abelian generating subgroups.  This file constructs that directed family
inside Lean and proves that it exhausts the original join.
-/

namespace NonsoficGroupsExist

universe u v

namespace ClassTwoApproximation

variable {G : Type u} [Group G]

noncomputable section

local instance {α : Type*} : DecidableEq α := Classical.decEq α

/-- A finite stage consists of finite subsets of the two generating
subgroups. -/
abbrev StageIndex (X Y : Subgroup G) := Finset X × Finset Y

/-- The subgroup generated by the selected elements of `X`. -/
def leftStage (X Y : Subgroup G) (a : StageIndex X Y) : Subgroup G :=
  Subgroup.closure (a.1.image Subtype.val : Set G)

/-- The subgroup generated by the selected elements of `Y`. -/
def rightStage (X Y : Subgroup G) (a : StageIndex X Y) : Subgroup G :=
  Subgroup.closure (a.2.image Subtype.val : Set G)

/-- The finitely generated subgroup obtained at one stage. -/
def stageGroup (X Y : Subgroup G) (a : StageIndex X Y) : Subgroup G :=
  leftStage X Y a ⊔ rightStage X Y a

theorem leftStage_le (X Y : Subgroup G) (a : StageIndex X Y) :
    leftStage X Y a ≤ X := by
  rw [leftStage, Subgroup.closure_le]
  intro g hg
  simp only [Finset.mem_coe, Finset.mem_image] at hg
  obtain ⟨x, _, rfl⟩ := hg
  exact x.2

theorem rightStage_le (X Y : Subgroup G) (a : StageIndex X Y) :
    rightStage X Y a ≤ Y := by
  rw [rightStage, Subgroup.closure_le]
  intro g hg
  simp only [Finset.mem_coe, Finset.mem_image] at hg
  obtain ⟨y, _, rfl⟩ := hg
  exact y.2

theorem leftStage_mono (X Y : Subgroup G) :
    Monotone (leftStage X Y) := by
  intro a b hab
  apply Subgroup.closure_mono
  intro g hg
  simp only [Finset.mem_coe, Finset.mem_image] at hg ⊢
  obtain ⟨x, hxa, rfl⟩ := hg
  exact ⟨x, hab.1 hxa, rfl⟩

theorem rightStage_mono (X Y : Subgroup G) :
    Monotone (rightStage X Y) := by
  intro a b hab
  apply Subgroup.closure_mono
  intro g hg
  simp only [Finset.mem_coe, Finset.mem_image] at hg ⊢
  obtain ⟨y, hya, rfl⟩ := hg
  exact ⟨y, hab.2 hya, rfl⟩

theorem stageGroup_mono (X Y : Subgroup G) :
    Monotone (stageGroup X Y) := by
  intro a b hab
  exact sup_le_sup ((leftStage_mono X Y) hab) ((rightStage_mono X Y) hab)

/-- Every stage group is genuinely finitely generated by the two selected
finite sets. -/
theorem stageGroup_fg (X Y : Subgroup G) (a : StageIndex X Y) :
    (stageGroup X Y a).FG := by
  refine ⟨a.1.image Subtype.val ∪ a.2.image Subtype.val, ?_⟩
  rw [stageGroup, leftStage, rightStage]
  simpa using Subgroup.closure_union
    (s := (a.1.image Subtype.val : Set G))
    (t := (a.2.image Subtype.val : Set G))

/-- The subtype group at every finite stage carries a finite-generation
proof obtained from its explicit generators. -/
theorem stageGroup_groupFG (X Y : Subgroup G) (a : StageIndex X Y) :
    Group.FG (stageGroup X Y a) :=
  (Group.fg_iff_subgroup_fg (stageGroup X Y a)).mpr (stageGroup_fg X Y a)

theorem iSup_leftStage (X Y : Subgroup G) :
    ⨆ a : StageIndex X Y, leftStage X Y a = X := by
  apply le_antisymm
  · exact iSup_le (leftStage_le X Y)
  · intro g hg
    let a : StageIndex X Y := ({⟨g, hg⟩}, ∅)
    apply (le_iSup (leftStage X Y) a)
    apply Subgroup.subset_closure
    simp [a]

theorem iSup_rightStage (X Y : Subgroup G) :
    ⨆ a : StageIndex X Y, rightStage X Y a = Y := by
  apply le_antisymm
  · exact iSup_le (rightStage_le X Y)
  · intro g hg
    let a : StageIndex X Y := (∅, {⟨g, hg⟩})
    apply (le_iSup (rightStage X Y) a)
    apply Subgroup.subset_closure
    simp [a]

/-- The directed family of finite stages exhausts the join of the two
original subgroups. -/
theorem iSup_stageGroup (X Y : Subgroup G) :
    ⨆ a : StageIndex X Y, stageGroup X Y a = X ⊔ Y := by
  apply le_antisymm
  · exact iSup_le fun a ↦ sup_le
      ((leftStage_le X Y a).trans le_sup_left)
      ((rightStage_le X Y a).trans le_sup_right)
  · apply sup_le
    · calc
        X = ⨆ a : StageIndex X Y, leftStage X Y a :=
          (iSup_leftStage X Y).symm
        _ ≤ ⨆ a : StageIndex X Y, stageGroup X Y a :=
          iSup_le fun a ↦
            (show leftStage X Y a ≤ stageGroup X Y a from le_sup_left).trans
              (le_iSup (stageGroup X Y) a)
    · calc
        Y = ⨆ a : StageIndex X Y, rightStage X Y a :=
          (iSup_rightStage X Y).symm
        _ ≤ ⨆ a : StageIndex X Y, stageGroup X Y a :=
          iSup_le fun a ↦
            (show rightStage X Y a ≤ stageGroup X Y a from le_sup_right).trans
              (le_iSup (stageGroup X Y) a)

variable {E : Type v} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [CompleteSpace E]

/-- The exact directed-limit reduction used in the universal class-two
argument.  Once the projected fixed vectors satisfy the same bound at every
explicit finite stage, the original fixed subspaces satisfy it. -/
theorem epsilonOrthogonal_of_stage_estimates
    (rho : G →* (E ≃ₗᵢ[ℝ] E)) (X Y : Subgroup G) {epsilon : ℝ}
    (hgen : X ⊔ Y = ⊤)
    (hno : IsKazhdanPair.HasNoInvariantVectors G rho)
    (hstage : ∀ a : StageIndex X Y,
      ∀ u, u ∈ KazhdanFixedSpace.fixedSubspace rho X →
      ∀ v, v ∈ KazhdanFixedSpace.fixedSubspace rho Y →
        |inner ℝ
          (KazhdanFixedSpace.subgroupMovingProjection rho
            (stageGroup X Y a) u)
          (KazhdanFixedSpace.subgroupMovingProjection rho
            (stageGroup X Y a) v)| ≤
        epsilon *
          ‖KazhdanFixedSpace.subgroupMovingProjection rho
            (stageGroup X Y a) u‖ *
          ‖KazhdanFixedSpace.subgroupMovingProjection rho
            (stageGroup X Y a) v‖) :
    HilbertEpsilonOrthogonality.EpsilonOrthogonal
      (KazhdanFixedSpace.fixedSubspace rho X)
      (KazhdanFixedSpace.fixedSubspace rho Y) epsilon := by
  let H : StageIndex X Y → Subgroup G := stageGroup X Y
  let W : StageIndex X Y → Submodule ℝ E := fun a ↦
    KazhdanFixedSpace.subgroupMovingSubspace rho (H a)
  letI (a : StageIndex X Y) : CompleteSpace
      (KazhdanFixedSpace.fixedSubspace rho (H a)) :=
    (KazhdanFixedSpace.isClosed_fixedSubspace rho (H a)).completeSpace_coe
  letI (a : StageIndex X Y) : (W a).HasOrthogonalProjection := by
    dsimp [W, KazhdanFixedSpace.subgroupMovingSubspace]
    infer_instance
  have hH : Monotone H := stageGroup_mono X Y
  have hW : Monotone W := by
    intro a b hab
    exact Submodule.orthogonal_le (KazhdanFixedSpace.antitone rho (hH hab))
  have hHsup : ⨆ a, H a = ⊤ := by
    rw [show (⨆ a, H a) = X ⊔ Y from iSup_stageGroup X Y, hgen]
  have hdense : ⊤ ≤ (⨆ a, W a).topologicalClosure := by
    exact KazhdanFixedSpace.movingSubspaces_iSup_dense rho H hHsup hno
  apply HilbertEpsilonOrthogonality.of_monotone_starProjection
    W hW hdense
  intro a u hu v hv
  simpa [W, H, KazhdanFixedSpace.subgroupMovingProjection,
    KazhdanFixedSpace.subgroupMovingSubspace] using hstage a u hu v hv

end

end ClassTwoApproximation
end NonsoficGroupsExist
