import NonsoficGroupsExist.Leavitt
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.Algebra.FreeAlgebra
import Mathlib.Data.Countable.Basic
import Mathlib.Data.Finsupp.Encodable
import Mathlib.Data.ZMod.Basic
import Mathlib.RingTheory.FiniteType
import Mathlib.SetTheory.Cardinal.Free
import Mathlib.Tactic.FinCases

/-!
# A represented algebra satisfying the binary Leavitt relations

This module constructs a subalgebra of the endomorphisms of the `ZMod 2`-valued
functions on infinite binary streams.  Its two prefix operators and two
prefix-deletion operators satisfy the binary Leavitt relations, so the
generated algebra has a kernel-checked `LeavittFamily` and is finitely
generated.  No isomorphism with the universal binary Leavitt algebra is
claimed or needed for these conclusions.
-/

namespace NonsoficGroupsExist

/-- Infinite binary streams. -/
abbrev BinaryStream := ℕ → Fin 2

/-- The vector space on which the concrete Leavitt algebra acts. -/
abbrev BinaryStreamSpace := BinaryStream → ZMod 2

namespace ConcreteLeavitt

/-- Add a bit at the front of an infinite stream. -/
def prepend (i : Fin 2) (w : BinaryStream) : BinaryStream
  | 0 => i
  | n + 1 => w n

/-- Remove the first bit of an infinite stream. -/
def tail (w : BinaryStream) : BinaryStream := fun n ↦ w (n + 1)

@[simp] theorem tail_prepend (i : Fin 2) (w : BinaryStream) :
    tail (prepend i w) = w := by
  funext n
  rfl

@[simp] theorem prepend_zero (i : Fin 2) (w : BinaryStream) :
    prepend i w 0 = i := rfl

@[simp] theorem prepend_head_tail (w : BinaryStream) :
    prepend (w 0) (tail w) = w := by
  funext n
  cases n <;> rfl

/-- The operator which prefixes a stream by `i`. -/
def prefixOperator (i : Fin 2) : Module.End (ZMod 2) BinaryStreamSpace where
  toFun f w := if w 0 = i then f (tail w) else 0
  map_add' _ _ := by
    funext w
    by_cases h : w 0 = i <;> simp [h]
  map_smul' _ _ := by
    funext w
    by_cases h : w 0 = i <;> simp [h]

/-- The operator which deletes an initial `i`, and is zero on the other
initial cylinder. -/
def deleteOperator (i : Fin 2) : Module.End (ZMod 2) BinaryStreamSpace where
  toFun f w := f (prepend i w)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

@[simp] theorem prefixOperator_apply (i : Fin 2) (f : BinaryStreamSpace)
    (w : BinaryStream) :
    prefixOperator i f w = if w 0 = i then f (tail w) else 0 := rfl

@[simp] theorem deleteOperator_apply (i : Fin 2) (f : BinaryStreamSpace)
    (w : BinaryStream) :
    deleteOperator i f w = f (prepend i w) := rfl

theorem delete_mul_prefix_same (i : Fin 2) :
    deleteOperator i * prefixOperator i = 1 := by
  ext f w
  simp

theorem delete_mul_prefix_ne {i j : Fin 2} (hij : i ≠ j) :
    deleteOperator i * prefixOperator j = 0 := by
  ext f w
  simp [hij]

theorem prefix_delete_sum :
    prefixOperator 0 * deleteOperator 0 +
      prefixOperator 1 * deleteOperator 1 = 1 := by
  ext f w
  have hw : w 0 = 0 ∨ w 0 = 1 := by omega
  rcases hw with hw | hw
  · simpa [hw] using congrArg f (prepend_head_tail w)
  · simpa [hw] using congrArg f (prepend_head_tail w)

/-- Names for the four algebra generators. -/
abbrev Generator := Fin 4

def s0 : Generator := 0
def s1 : Generator := 1
def t0 : Generator := 2
def t1 : Generator := 3

/-- The four concrete endomorphisms indexed by their generator names. -/
def generatorOperator (g : Generator) : Module.End (ZMod 2) BinaryStreamSpace :=
  if g = s0 then prefixOperator 0
  else if g = s1 then prefixOperator 1
  else if g = t0 then deleteOperator 0
  else deleteOperator 1

@[simp] theorem generatorOperator_s0 : generatorOperator s0 = prefixOperator 0 := by
  simp [generatorOperator, s0]

@[simp] theorem generatorOperator_s1 : generatorOperator s1 = prefixOperator 1 := by
  simp [generatorOperator, s0, s1]

@[simp] theorem generatorOperator_t0 : generatorOperator t0 = deleteOperator 0 := by
  simp [generatorOperator, s0, s1, t0]

@[simp] theorem generatorOperator_t1 : generatorOperator t1 = deleteOperator 1 := by
  simp [generatorOperator, s0, s1, t0, t1]

noncomputable instance countableFreeAlgebra (X : Type*) [Countable X] :
    Countable (FreeAlgebra (ZMod 2) X) := by
  letI : Countable (FreeMonoid X) :=
    Countable.of_equiv (List X) (FreeMonoid.ofList (α := X))
  letI : Countable (MonoidAlgebra (ZMod 2) (FreeMonoid X)) :=
    Countable.of_equiv ((FreeMonoid X) →₀ ZMod 2)
      (MonoidAlgebra.coeffEquiv (R := ZMod 2) (M := FreeMonoid X)).symm
  exact Countable.of_equiv (MonoidAlgebra (ZMod 2) (FreeMonoid X))
    (FreeAlgebra.equivMonoidAlgebraFreeMonoid
      (R := ZMod 2) (X := X)).symm.toEquiv

/-- Evaluation of noncommutative polynomials in the four stream operators. -/
noncomputable def evaluation :
    FreeAlgebra (ZMod 2) Generator →ₐ[ZMod 2]
      Module.End (ZMod 2) BinaryStreamSpace :=
  FreeAlgebra.lift (ZMod 2) generatorOperator

/-- The subalgebra generated by the four prefix/deletion endomorphisms. -/
noncomputable abbrev StreamOperatorAlgebra := evaluation.range

/-- The canonical surjection from the free algebra on the four generators. -/
noncomputable def presentation :
    FreeAlgebra (ZMod 2) Generator →ₐ[ZMod 2] StreamOperatorAlgebra :=
  evaluation.codRestrict evaluation.range fun x ↦ ⟨x, rfl⟩

theorem presentation_surjective : Function.Surjective presentation := by
  rintro ⟨x, p, hp⟩
  refine ⟨p, ?_⟩
  exact Subtype.ext hp

instance : Algebra.FiniteType (ZMod 2) StreamOperatorAlgebra :=
  Algebra.FiniteType.of_surjective presentation presentation_surjective

noncomputable instance : Countable StreamOperatorAlgebra := by
  exact presentation_surjective.countable

noncomputable def generator (g : Generator) : StreamOperatorAlgebra :=
  ⟨generatorOperator g, FreeAlgebra.ι (ZMod 2) g, by
    simp [evaluation]⟩

/-- The defining Leavitt family in the concrete algebra. -/
noncomputable def family : LeavittFamily StreamOperatorAlgebra where
  s0 := generator s0
  s1 := generator s1
  t0 := generator t0
  t1 := generator t1
  t0_s0 := by
    apply Subtype.ext
    exact delete_mul_prefix_same 0
  t0_s1 := by
    apply Subtype.ext
    exact delete_mul_prefix_ne (by decide : (0 : Fin 2) ≠ 1)
  t1_s0 := by
    apply Subtype.ext
    exact delete_mul_prefix_ne (by decide : (1 : Fin 2) ≠ 0)
  t1_s1 := by
    apply Subtype.ext
    exact delete_mul_prefix_same 1
  sum_range := by
    apply Subtype.ext
    exact prefix_delete_sum

noncomputable instance : Infinite StreamOperatorAlgebra := family.infinite

end ConcreteLeavitt
end NonsoficGroupsExist
