import Mathlib.Algebra.Group.Subgroup.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Tactic.Group

/-!
# Words in a symmetric generating set

The expander decomposition records almost invariance only for the fixed
symmetric generators.  This file extracts an actual finite word for every
element of the generated group, retaining membership of every letter in the
given generating finset.
-/

namespace NonsoficGroupsExist

variable {G : Type} [Group G]

/-- The inverse word, in the order required in a noncommutative group. -/
def inverseWord (w : List G) : List G := (w.map Inv.inv).reverse

@[simp] theorem prod_inverseWord (w : List G) : (inverseWord w).prod = w.prod⁻¹ := by
  induction w with
  | nil => simp [inverseWord]
  | cons g w ih =>
      simp only [inverseWord, List.map_cons, List.reverse_cons, List.prod_cons]
      change (inverseWord w ++ [g⁻¹]).prod = (g * w.prod)⁻¹
      simp [ih]

/-- Every element of the subgroup generated by a symmetric finset is the
product of a list of letters in that finset. -/
theorem exists_generator_word (T : Finset G)
    (hsymm : ∀ g ∈ T, g⁻¹ ∈ T) (hgen : Subgroup.closure (T : Set G) = ⊤)
    (g : G) : ∃ w : List G, (∀ x ∈ w, x ∈ T) ∧ w.prod = g := by
  have hg : g ∈ Subgroup.closure (T : Set G) := by
    rw [hgen]
    exact Subgroup.mem_top g
  induction hg using Subgroup.closure_induction with
  | mem x hx => exact ⟨[x], by simpa using hx, by simp⟩
  | one => exact ⟨[], by simp, by simp⟩
  | mul x y _ _ hx hy =>
      obtain ⟨wx, hxmem, hxprod⟩ := hx
      obtain ⟨wy, hymem, hyprod⟩ := hy
      refine ⟨wx ++ wy, ?_, ?_⟩
      · intro z hz
        rcases List.mem_append.mp hz with hz | hz
        · exact hxmem z hz
        · exact hymem z hz
      · simp [hxprod, hyprod]
  | inv x _ hx =>
      obtain ⟨w, hwmem, hwprod⟩ := hx
      refine ⟨inverseWord w, ?_, ?_⟩
      · intro z hz
        simp only [inverseWord, List.mem_reverse, List.mem_map] at hz
        obtain ⟨a, ha, rfl⟩ := hz
        exact hsymm a (hwmem a ha)
      · simp [hwprod]

end NonsoficGroupsExist
