import NonsoficGroupsExist.ThompsonVEmbedding
import NonsoficGroupsExist.ThompsonWitness

/-!
# The corner witness inside the permutation units

The non-LEF corner witness subgroup is generated by cylinder swaps and
their corner insertions.  Every cylinder swap acts on the faithful stream
basis as the boundary transposition of the two cylinders, so the entire
witness lies in the basis-permuting units (checkpoint `D3`, first half).
-/

namespace NonsoficGroupsExist
namespace BinaryLeavitt

open ThompsonV LeavittFamily

open Classical in
/-- The boundary transposition of two cylinders. -/
noncomputable def swapMap (a b : List (Fin 2)) (x : Boundary) :
    Boundary :=
  if IsStreamPrefix a x then
    ThompsonV.prepend b (ThompsonV.drop a.length x)
  else if IsStreamPrefix b x then
    ThompsonV.prepend a (ThompsonV.drop b.length x)
  else x

theorem not_isStreamPrefix_prepend {a b : List (Fin 2)}
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) (y : Boundary) :
    ¬ IsStreamPrefix a (ThompsonV.prepend b y) := by
  intro h
  rcases prefix_or_prefix_of_isStreamPrefix h
    (isStreamPrefix_prepend b y) with hc | hc
  · exact hab hc
  · exact hba hc

theorem not_both_isStreamPrefix {a b : List (Fin 2)}
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) {x : Boundary}
    (ha : IsStreamPrefix a x) : ¬ IsStreamPrefix b x := by
  intro hb
  rcases prefix_or_prefix_of_isStreamPrefix ha hb with hc | hc
  · exact hab hc
  · exact hba hc

open Classical in
theorem swapMap_involutive (a b : List (Fin 2)) (hab : ¬ a <+: b)
    (hba : ¬ b <+: a) : Function.Involutive (swapMap a b) := by
  intro x
  by_cases ha : IsStreamPrefix a x
  · have h1 : swapMap a b x =
        ThompsonV.prepend b (ThompsonV.drop a.length x) := by
      rw [swapMap, if_pos ha]
    rw [h1, swapMap,
      if_neg (not_isStreamPrefix_prepend hab hba _),
      if_pos (isStreamPrefix_prepend b _), drop_prepend,
      prepend_drop_of_isStreamPrefix a x ha]
  · by_cases hb : IsStreamPrefix b x
    · have h1 : swapMap a b x =
          ThompsonV.prepend a (ThompsonV.drop b.length x) := by
        rw [swapMap, if_neg ha, if_pos hb]
      rw [h1, swapMap,
        if_pos (isStreamPrefix_prepend a _),
        drop_prepend, prepend_drop_of_isStreamPrefix b x hb]
    · have h1 : swapMap a b x = x := by
        rw [swapMap, if_neg ha, if_neg hb]
      rw [h1, h1]

open Classical in
/-- The boundary transposition as a permutation. -/
noncomputable def swapPerm (a b : List (Fin 2)) (hab : ¬ a <+: b)
    (hba : ¬ b <+: a) : Equiv.Perm Boundary :=
  (swapMap_involutive a b hab hba).toPerm

@[simp] theorem swapPerm_apply (a b : List (Fin 2)) (hab : ¬ a <+: b)
    (hba : ¬ b <+: a) (x : Boundary) :
    swapPerm a b hab hba x = swapMap a b x := rfl

variable (k : Type) [Field k]

open Classical in
/-- A cylinder swap acts on the stream basis by the boundary
transposition. -/
theorem finsuppStreamRep_cylinderSwap_single (a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) (x : Boundary) (c : k) :
    finsuppStreamRep k
        (((family k).cylinderSwap a b hab hba :
          (BinaryLeavittAlgebra k)ˣ) : BinaryLeavittAlgebra k)
        (Finsupp.single x c) =
      Finsupp.single (swapMap a b x) c := by
  rw [cylinderSwap_val, transpositionValue]
  simp only [map_sub, map_add, map_mul, map_one, LinearMap.sub_apply,
    LinearMap.add_apply, Module.End.mul_apply, Module.End.one_apply]
  rw [finsuppStreamRep_wordT_single, finsuppStreamRep_wordT_single]
  by_cases ha : IsStreamPrefix a x
  · have hb : ¬ IsStreamPrefix b x := not_both_isStreamPrefix hab hba ha
    rw [if_pos ha, if_neg hb]
    simp only [map_zero]
    rw [finsuppStreamRep_wordS_single, finsuppStreamRep_wordS_single,
      prepend_drop_of_isStreamPrefix a x ha]
    rw [swapMap, if_pos ha]
    abel
  · by_cases hb : IsStreamPrefix b x
    · rw [if_pos hb, if_neg ha]
      simp only [map_zero]
      rw [finsuppStreamRep_wordS_single, finsuppStreamRep_wordS_single,
        prepend_drop_of_isStreamPrefix b x hb]
      rw [swapMap, if_neg ha, if_pos hb]
      abel
    · rw [if_neg ha, if_neg hb]
      simp only [map_zero]
      rw [swapMap, if_neg ha, if_neg hb]
      abel

theorem cylinderSwap_mem_deltaPermUnits (a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) :
    (family k).cylinderSwap a b hab hba ∈ deltaPermUnits k :=
  ⟨swapPerm a b hab hba, fun x c ↦ by
    rw [swapPerm_apply]
    exact finsuppStreamRep_cylinderSwap_single k a b hab hba x c⟩


section Insertion

variable {A : Type*} [Ring A] (L : LeavittFamily A)

/-- Prefix insertion carries a cylinder swap to the swap of the inserted
cylinders. -/
theorem prefixInsertionUnit_cylinderSwap (l a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) :
    L.prefixInsertionUnit l (L.cylinderSwap a b hab hba) =
      L.cylinderSwap (l ++ a) (l ++ b)
        (fun h ↦ hab ((List.prefix_append_right_inj l).1 h))
        (fun h ↦ hba ((List.prefix_append_right_inj l).1 h)) := by
  apply Units.ext
  show L.wordS l *
      transpositionValue (L.wordS a) (L.wordT a) (L.wordS b)
        (L.wordT b) * L.wordT l + (1 - L.cylinder l) =
    transpositionValue (L.wordS (l ++ a)) (L.wordT (l ++ a))
      (L.wordS (l ++ b)) (L.wordT (l ++ b))
  have hc : L.cylinder l = L.wordS l * L.wordT l := rfl
  rw [transpositionValue, transpositionValue, L.wordS_append l a,
    L.wordS_append l b, L.wordT_append l a, L.wordT_append l b, hc]
  noncomm_ring

/-- The corner homomorphism is prefix insertion at the cylinder `[1]`. -/
theorem cornerHom_eq_prefixInsertionUnit (u : Aˣ) :
    L.cornerHom u = L.prefixInsertionUnit [1] u := by
  apply Units.ext
  show L.p0 + L.s1 * (↑u : A) * L.t1 =
    L.wordS [1] * (↑u : A) * L.wordT [1] + (1 - L.cylinder [1])
  have h1 : L.wordS [1] = L.s1 := by
    rw [L.wordS_cons, L.wordS_nil, mul_one]
    rfl
  have h2 : L.wordT [1] = L.t1 := by
    rw [L.wordT_cons, L.wordT_nil, one_mul]
    rfl
  have hc : L.cylinder [1] = L.wordS [1] * L.wordT [1] := rfl
  have hp : L.p0 = 1 - L.s1 * L.t1 :=
    eq_sub_of_add_eq L.p0_add_s1t1
  rw [h1, h2, hc, h1, h2, hp]
  noncomm_ring

end Insertion

section WitnessMembership

open Classical

variable (k : Type) [Field k]

theorem cornerHom_cylinderSwap_mem (a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) :
    (family k).cornerHom ((family k).cylinderSwap a b hab hba) ∈
      deltaPermUnits k := by
  rw [cornerHom_eq_prefixInsertionUnit,
    prefixInsertionUnit_cylinderSwap]
  exact cylinderSwap_mem_deltaPermUnits k _ _ _ _

theorem cornerHom_insertion_cylinderSwap_mem (l a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) :
    (family k).cornerHom ((family k).prefixInsertionUnit l
      ((family k).cylinderSwap a b hab hba)) ∈ deltaPermUnits k := by
  rw [prefixInsertionUnit_cylinderSwap]
  exact cornerHom_cylinderSwap_mem k _ _ _ _

/-- **The corner witness consists of basis-permuting units** (checkpoint
`D3`, first half): the two-generated non-LEF witness subgroup lies inside
the units permuting the stream basis. -/
theorem cornerWitness_le_deltaPermUnits :
    (family k).cornerWitnessSubgroup ≤ deltaPermUnits k := by
  rw [LeavittFamily.cornerWitnessSubgroup, Subgroup.closure_le]
  rintro x (rfl | rfl)
  · show (family k).cornerHom (family k).generatorA ∈ _
    rw [LeavittFamily.generatorA, map_inv]
    refine Subgroup.inv_mem _ ?_
    rw [LeavittFamily.rootRotation, map_mul, map_mul]
    exact Subgroup.mul_mem _
      (Subgroup.mul_mem _
        (cornerHom_cylinderSwap_mem k [0] [1, 0] (by decide) (by decide))
        (cornerHom_cylinderSwap_mem k [0] [1, 1] (by decide) (by decide)))
      (cornerHom_cylinderSwap_mem k [0] [1] (by decide) (by decide))
  · show (family k).cornerHom (family k).generatorB ∈ _
    rw [LeavittFamily.generatorB, LeavittFamily.rightRotation, map_inv]
    refine Subgroup.inv_mem _ ?_
    rw [LeavittFamily.rootRotation, map_mul, map_mul, map_mul, map_mul,
      LeavittFamily.prefixInsertion_apply, LeavittFamily.prefixInsertion_apply,
      LeavittFamily.prefixInsertion_apply]
    exact Subgroup.mul_mem _
      (Subgroup.mul_mem _
        (cornerHom_insertion_cylinderSwap_mem k [1] [0] [1, 0]
          (by decide) (by decide))
        (cornerHom_insertion_cylinderSwap_mem k [1] [0] [1, 1]
          (by decide) (by decide)))
      (cornerHom_insertion_cylinderSwap_mem k [1] [0] [1]
        (by decide) (by decide))

end WitnessMembership

end BinaryLeavitt
end NonsoficGroupsExist
