import NonsoficGroupsExist.ThompsonVEmbedding
import NonsoficGroupsExist.ThompsonWitness
import Mathlib.Algebra.Field.ZMod

/-!
# The corner witness inside the permutation units

The non-LEF corner witness subgroup is generated by cylinder swaps and
their corner insertions.  Every cylinder swap acts on the faithful stream
basis as the boundary transposition of the two cylinders, so the entire
witness lies in the basis-permuting units (checkpoint `D3`, first half).
-/

namespace NonsoficGroupsExist
namespace BinaryLeavitt

open ThompsonV LeavittFamily

open Classical in
/-- The boundary transposition of two cylinders. -/
noncomputable def swapMap (a b : List (Fin 2)) (x : Boundary) :
    Boundary :=
  if IsStreamPrefix a x then
    ThompsonV.prepend b (ThompsonV.drop a.length x)
  else if IsStreamPrefix b x then
    ThompsonV.prepend a (ThompsonV.drop b.length x)
  else x

theorem not_isStreamPrefix_prepend {a b : List (Fin 2)}
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) (y : Boundary) :
    ¬ IsStreamPrefix a (ThompsonV.prepend b y) := by
  intro h
  rcases prefix_or_prefix_of_isStreamPrefix h
    (isStreamPrefix_prepend b y) with hc | hc
  · exact hab hc
  · exact hba hc

theorem not_both_isStreamPrefix {a b : List (Fin 2)}
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) {x : Boundary}
    (ha : IsStreamPrefix a x) : ¬ IsStreamPrefix b x := by
  intro hb
  rcases prefix_or_prefix_of_isStreamPrefix ha hb with hc | hc
  · exact hab hc
  · exact hba hc

open Classical in
theorem swapMap_involutive (a b : List (Fin 2)) (hab : ¬ a <+: b)
    (hba : ¬ b <+: a) : Function.Involutive (swapMap a b) := by
  intro x
  by_cases ha : IsStreamPrefix a x
  · have h1 : swapMap a b x =
        ThompsonV.prepend b (ThompsonV.drop a.length x) := by
      rw [swapMap, if_pos ha]
    rw [h1, swapMap,
      if_neg (not_isStreamPrefix_prepend hab hba _),
      if_pos (isStreamPrefix_prepend b _), drop_prepend,
      prepend_drop_of_isStreamPrefix a x ha]
  · by_cases hb : IsStreamPrefix b x
    · have h1 : swapMap a b x =
          ThompsonV.prepend a (ThompsonV.drop b.length x) := by
        rw [swapMap, if_neg ha, if_pos hb]
      rw [h1, swapMap,
        if_pos (isStreamPrefix_prepend a _),
        drop_prepend, prepend_drop_of_isStreamPrefix b x hb]
    · have h1 : swapMap a b x = x := by
        rw [swapMap, if_neg ha, if_neg hb]
      rw [h1, h1]

open Classical in
/-- The boundary transposition as a permutation. -/
noncomputable def swapPerm (a b : List (Fin 2)) (hab : ¬ a <+: b)
    (hba : ¬ b <+: a) : Equiv.Perm Boundary :=
  (swapMap_involutive a b hab hba).toPerm

@[simp] theorem swapPerm_apply (a b : List (Fin 2)) (hab : ¬ a <+: b)
    (hba : ¬ b <+: a) (x : Boundary) :
    swapPerm a b hab hba x = swapMap a b x := rfl

variable (k : Type) [Field k]

open Classical in
/-- A cylinder swap acts on the stream basis by the boundary
transposition. -/
theorem finsuppStreamRep_cylinderSwap_single (a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) (x : Boundary) (c : k) :
    finsuppStreamRep k
        (((family k).cylinderSwap a b hab hba :
          (BinaryLeavittAlgebra k)ˣ) : BinaryLeavittAlgebra k)
        (Finsupp.single x c) =
      Finsupp.single (swapMap a b x) c := by
  rw [cylinderSwap_val, transpositionValue]
  simp only [map_sub, map_add, map_mul, map_one, LinearMap.sub_apply,
    LinearMap.add_apply, Module.End.mul_apply, Module.End.one_apply]
  rw [finsuppStreamRep_wordT_single, finsuppStreamRep_wordT_single]
  by_cases ha : IsStreamPrefix a x
  · have hb : ¬ IsStreamPrefix b x := not_both_isStreamPrefix hab hba ha
    rw [if_pos ha, if_neg hb]
    simp only [map_zero]
    rw [finsuppStreamRep_wordS_single, finsuppStreamRep_wordS_single,
      prepend_drop_of_isStreamPrefix a x ha]
    rw [swapMap, if_pos ha]
    abel
  · by_cases hb : IsStreamPrefix b x
    · rw [if_pos hb, if_neg ha]
      simp only [map_zero]
      rw [finsuppStreamRep_wordS_single, finsuppStreamRep_wordS_single,
        prepend_drop_of_isStreamPrefix b x hb]
      rw [swapMap, if_neg ha, if_pos hb]
      abel
    · rw [if_neg ha, if_neg hb]
      simp only [map_zero]
      rw [swapMap, if_neg ha, if_neg hb]
      abel

theorem cylinderSwap_mem_deltaPermUnits (a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) :
    (family k).cylinderSwap a b hab hba ∈ deltaPermUnits k :=
  ⟨swapPerm a b hab hba, fun x c ↦ by
    rw [swapPerm_apply]
    exact finsuppStreamRep_cylinderSwap_single k a b hab hba x c⟩


section Insertion

variable {A : Type*} [Ring A] (L : LeavittFamily A)

/-- Prefix insertion carries a cylinder swap to the swap of the inserted
cylinders. -/
theorem prefixInsertionUnit_cylinderSwap (l a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) :
    L.prefixInsertionUnit l (L.cylinderSwap a b hab hba) =
      L.cylinderSwap (l ++ a) (l ++ b)
        (fun h ↦ hab ((List.prefix_append_right_inj l).1 h))
        (fun h ↦ hba ((List.prefix_append_right_inj l).1 h)) := by
  apply Units.ext
  show L.wordS l *
      transpositionValue (L.wordS a) (L.wordT a) (L.wordS b)
        (L.wordT b) * L.wordT l + (1 - L.cylinder l) =
    transpositionValue (L.wordS (l ++ a)) (L.wordT (l ++ a))
      (L.wordS (l ++ b)) (L.wordT (l ++ b))
  have hc : L.cylinder l = L.wordS l * L.wordT l := rfl
  rw [transpositionValue, transpositionValue, L.wordS_append l a,
    L.wordS_append l b, L.wordT_append l a, L.wordT_append l b, hc]
  noncomm_ring

/-- The corner homomorphism is prefix insertion at the cylinder `[1]`. -/
theorem cornerHom_eq_prefixInsertionUnit (u : Aˣ) :
    L.cornerHom u = L.prefixInsertionUnit [1] u := by
  apply Units.ext
  show L.p0 + L.s1 * (↑u : A) * L.t1 =
    L.wordS [1] * (↑u : A) * L.wordT [1] + (1 - L.cylinder [1])
  have h1 : L.wordS [1] = L.s1 := by
    rw [L.wordS_cons, L.wordS_nil, mul_one]
    rfl
  have h2 : L.wordT [1] = L.t1 := by
    rw [L.wordT_cons, L.wordT_nil, one_mul]
    rfl
  have hc : L.cylinder [1] = L.wordS [1] * L.wordT [1] := rfl
  have hp : L.p0 = 1 - L.s1 * L.t1 :=
    eq_sub_of_add_eq L.p0_add_s1t1
  rw [h1, h2, hc, h1, h2, hp]
  noncomm_ring

end Insertion

section WitnessMembership

open Classical

variable (k : Type) [Field k]

theorem cornerHom_cylinderSwap_mem (a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) :
    (family k).cornerHom ((family k).cylinderSwap a b hab hba) ∈
      deltaPermUnits k := by
  rw [cornerHom_eq_prefixInsertionUnit,
    prefixInsertionUnit_cylinderSwap]
  exact cylinderSwap_mem_deltaPermUnits k _ _ _ _

theorem cornerHom_insertion_cylinderSwap_mem (l a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) :
    (family k).cornerHom ((family k).prefixInsertionUnit l
      ((family k).cylinderSwap a b hab hba)) ∈ deltaPermUnits k := by
  rw [prefixInsertionUnit_cylinderSwap]
  exact cornerHom_cylinderSwap_mem k _ _ _ _

/-- **The corner witness consists of basis-permuting units** (checkpoint
`D3`, first half): the two-generated non-LEF witness subgroup lies inside
the units permuting the stream basis. -/
theorem cornerWitness_le_deltaPermUnits :
    (family k).cornerWitnessSubgroup ≤ deltaPermUnits k := by
  rw [LeavittFamily.cornerWitnessSubgroup, Subgroup.closure_le]
  rintro x (rfl | rfl)
  · show (family k).cornerHom (family k).generatorA ∈ _
    rw [LeavittFamily.generatorA, map_inv]
    refine Subgroup.inv_mem _ ?_
    rw [LeavittFamily.rootRotation, map_mul, map_mul]
    exact Subgroup.mul_mem _
      (Subgroup.mul_mem _
        (cornerHom_cylinderSwap_mem k [0] [1, 0] (by decide) (by decide))
        (cornerHom_cylinderSwap_mem k [0] [1, 1] (by decide) (by decide)))
      (cornerHom_cylinderSwap_mem k [0] [1] (by decide) (by decide))
  · show (family k).cornerHom (family k).generatorB ∈ _
    rw [LeavittFamily.generatorB, LeavittFamily.rightRotation, map_inv]
    refine Subgroup.inv_mem _ ?_
    rw [LeavittFamily.rootRotation, map_mul, map_mul, map_mul, map_mul,
      LeavittFamily.prefixInsertion_apply, LeavittFamily.prefixInsertion_apply,
      LeavittFamily.prefixInsertion_apply]
    exact Subgroup.mul_mem _
      (Subgroup.mul_mem _
        (cornerHom_insertion_cylinderSwap_mem k [1] [0] [1, 0]
          (by decide) (by decide))
        (cornerHom_insertion_cylinderSwap_mem k [1] [0] [1, 1]
          (by decide) (by decide)))
      (cornerHom_insertion_cylinderSwap_mem k [1] [0] [1]
        (by decide) (by decide))

end WitnessMembership


section SwapTable

open Classical

/-- The index type of the swap table: the two swapped cylinders together
with all depth-`N` words avoiding both. -/
abbrev SwapIndex (a b : List (Fin 2)) : Type :=
  Fin 2 ⊕ {g : Fin (max a.length b.length) → Fin 2 //
    ¬ a <+: List.ofFn g ∧ ¬ b <+: List.ofFn g}

open Classical in
noncomputable instance (a b : List (Fin 2)) : Fintype (SwapIndex a b) := by
  unfold SwapIndex
  infer_instance

variable (a b : List (Fin 2))

private theorem ofFn_swapIndex_length
    (g : {g : Fin (max a.length b.length) → Fin 2 //
      ¬ a <+: List.ofFn g ∧ ¬ b <+: List.ofFn g}) :
    (List.ofFn g.val).length = max a.length b.length := by
  simp

private theorem prefix_of_eq {u l : List (Fin 2)} (h : l = u) :
    u <+: l := by
  rw [h]

/-- The leaf code of the swap table, with the two distinguished cylinders
listed in the given order. -/
noncomputable def swapCode (u v : List (Fin 2))
    (huv : ¬ u <+: v) (hvu : ¬ v <+: u)
    (hgu : ∀ g : {g : Fin (max a.length b.length) → Fin 2 //
      ¬ a <+: List.ofFn g ∧ ¬ b <+: List.ofFn g},
      ¬ u <+: List.ofFn g.val)
    (hgv : ∀ g : {g : Fin (max a.length b.length) → Fin 2 //
      ¬ a <+: List.ofFn g ∧ ¬ b <+: List.ofFn g},
      ¬ v <+: List.ofFn g.val)
    (hlu : u.length ≤ max a.length b.length)
    (hlv : v.length ≤ max a.length b.length) :
    BinaryPrefixCode (SwapIndex a b) where
  word i := Sum.elim (fun t : Fin 2 ↦ if t = 0 then u else v)
    (fun g ↦ List.ofFn g.val) i
  prefix_free := by
    rintro (t | g) (t' | g') hij h
    · by_cases ht : t = 0
      · by_cases ht' : t' = 0
        · exact hij (by rw [ht, ht'])
        · rw [Sum.elim_inl, Sum.elim_inl, if_pos ht, if_neg ht'] at h
          exact huv h
      · by_cases ht' : t' = 0
        · rw [Sum.elim_inl, Sum.elim_inl, if_neg ht, if_pos ht'] at h
          exact hvu h
        · exact hij (by
            rw [show t = 1 from by omega, show t' = 1 from by omega])
    · rw [Sum.elim_inl, Sum.elim_inr] at h
      by_cases ht : t = 0
      · rw [if_pos ht] at h
        exact hgu g' h
      · rw [if_neg ht] at h
        exact hgv g' h
    · rw [Sum.elim_inr, Sum.elim_inl] at h
      by_cases ht' : t' = 0
      · rw [if_pos ht'] at h
        have hle := h.length_le
        rw [ofFn_swapIndex_length a b g] at hle
        exact hgu g (prefix_of_eq (List.IsPrefix.eq_of_length h (by
          rw [ofFn_swapIndex_length a b g]
          omega)))
      · rw [if_neg ht'] at h
        have hle := h.length_le
        rw [ofFn_swapIndex_length a b g] at hle
        exact hgv g (prefix_of_eq (List.IsPrefix.eq_of_length h (by
          rw [ofFn_swapIndex_length a b g]
          omega)))
    · rw [Sum.elim_inr, Sum.elim_inr] at h
      have heq : List.ofFn g.val = List.ofFn g'.val :=
        List.IsPrefix.eq_of_length h (by
          rw [ofFn_swapIndex_length a b g, ofFn_swapIndex_length a b g'])
      exact hij (by
        rw [Sum.inr.injEq]
        exact Subtype.ext (List.ofFn_injective heq))

end SwapTable




section SwapPermMem

open Classical ThompsonV

theorem isStreamPrefix_of_prefix_trunc {w : List (Fin 2)} {x : Boundary}
    {N : ℕ} (h : w <+: List.ofFn (fun n : Fin N ↦ x n)) :
    IsStreamPrefix w x := by
  intro m hm
  obtain ⟨hle, helem⟩ := List.prefix_iff_getElem.mp h
  have hstep := helem m hm
  simpa using hstep.symm

theorem trunc_isStreamPrefix (x : Boundary) (N : ℕ) :
    IsStreamPrefix (List.ofFn (fun n : Fin N ↦ x n)) x := by
  intro m hm
  simp only [List.length_ofFn] at hm
  simp

variable (a b : List (Fin 2)) (hab : ¬ a <+: b) (hba : ¬ b <+: a)

theorem covers_swapCode (u v : List (Fin 2))
    (huv : ¬ u <+: v) (hvu : ¬ v <+: u)
    (hgu : ∀ g : {g : Fin (max a.length b.length) → Fin 2 //
      ¬ a <+: List.ofFn g ∧ ¬ b <+: List.ofFn g},
      ¬ u <+: List.ofFn g.val)
    (hgv : ∀ g : {g : Fin (max a.length b.length) → Fin 2 //
      ¬ a <+: List.ofFn g ∧ ¬ b <+: List.ofFn g},
      ¬ v <+: List.ofFn g.val)
    (hlu : u.length ≤ max a.length b.length)
    (hlv : v.length ≤ max a.length b.length)
    (hset : (u = a ∧ v = b) ∨ (u = b ∧ v = a)) :
    ThompsonV.Covers (swapCode a b u v huv hvu hgu hgv hlu hlv) := by
  intro x
  by_cases hu : IsStreamPrefix u x
  · refine ⟨Sum.inl 0, ?_⟩
    have hw : (swapCode a b u v huv hvu hgu hgv hlu hlv).word
        (Sum.inl 0) = u := rfl
    rw [hw]
    exact hu
  by_cases hv : IsStreamPrefix v x
  · refine ⟨Sum.inl 1, ?_⟩
    have hw : (swapCode a b u v huv hvu hgu hgv hlu hlv).word
        (Sum.inl 1) = v := rfl
    rw [hw]
    exact hv
  · set g : Fin (max a.length b.length) → Fin 2 := fun n ↦ x n with hg
    have hga : ¬ a <+: List.ofFn g := by
      intro hpre
      rcases hset with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
      · exact hu (isStreamPrefix_of_prefix_trunc hpre)
      · exact hv (isStreamPrefix_of_prefix_trunc hpre)
    have hgb : ¬ b <+: List.ofFn g := by
      intro hpre
      rcases hset with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
      · exact hv (isStreamPrefix_of_prefix_trunc hpre)
      · exact hu (isStreamPrefix_of_prefix_trunc hpre)
    refine ⟨Sum.inr ⟨g, hga, hgb⟩, ?_⟩
    have hw : (swapCode a b u v huv hvu hgu hgv hlu hlv).word
        (Sum.inr ⟨g, hga, hgb⟩) = List.ofFn g := rfl
    rw [hw]
    exact trunc_isStreamPrefix x _

/-- The source leaves of the swap. -/
noncomputable def swapE : BinaryPrefixCode (SwapIndex a b) :=
  swapCode a b a b hab hba (fun g ↦ g.property.1)
    (fun g ↦ g.property.2) (le_max_left _ _) (le_max_right _ _)

/-- The target leaves of the swap. -/
noncomputable def swapB : BinaryPrefixCode (SwapIndex a b) :=
  swapCode a b b a hba hab (fun g ↦ g.property.2)
    (fun g ↦ g.property.1) (le_max_right _ _) (le_max_left _ _)

theorem covers_swapE : ThompsonV.Covers (swapE a b hab hba) :=
  covers_swapCode a b a b _ _ _ _ _ _ (Or.inl ⟨rfl, rfl⟩)

theorem covers_swapB : ThompsonV.Covers (swapB a b hab hba) :=
  covers_swapCode a b b a _ _ _ _ _ _ (Or.inr ⟨rfl, rfl⟩)

/-- **Cylinder transpositions are tree tables.** -/
theorem swapPerm_mem_thompsonV :
    swapPerm a b hab hba ∈ thompsonV := by
  have hEB : tableEquiv (swapE a b hab hba) (swapB a b hab hba)
      (covers_swapE a b hab hba) (covers_swapB a b hab hba) =
      swapPerm a b hab hba := by
    apply Equiv.ext
    intro x
    show tableMap (swapE a b hab hba) (swapB a b hab hba)
      (covers_swapE a b hab hba) x = swapMap a b x
    by_cases ha : IsStreamPrefix a x
    · have hidx : coveringIndex (swapE a b hab hba)
          (covers_swapE a b hab hba) x = Sum.inl 0 :=
        coveringIndex_eq _ _ (by
          have hw : (swapE a b hab hba).word (Sum.inl 0) = a := rfl
          rw [hw]
          exact ha)
      rw [tableMap, hidx, swapMap, if_pos ha]
      rfl
    · by_cases hb : IsStreamPrefix b x
      · have hidx : coveringIndex (swapE a b hab hba)
            (covers_swapE a b hab hba) x = Sum.inl 1 :=
          coveringIndex_eq _ _ (by
            have hw : (swapE a b hab hba).word (Sum.inl 1) = b := rfl
            rw [hw]
            exact hb)
        rw [tableMap, hidx, swapMap, if_neg ha, if_pos hb]
        rfl
      · set g : Fin (max a.length b.length) → Fin 2 := fun n ↦ x n
          with hg
        have hga : ¬ a <+: List.ofFn g := fun hpre ↦
          ha (isStreamPrefix_of_prefix_trunc hpre)
        have hgb : ¬ b <+: List.ofFn g := fun hpre ↦
          hb (isStreamPrefix_of_prefix_trunc hpre)
        have hidx : coveringIndex (swapE a b hab hba)
            (covers_swapE a b hab hba) x = Sum.inr ⟨g, hga, hgb⟩ :=
          coveringIndex_eq _ _ (by
            have hw : (swapE a b hab hba).word
                (Sum.inr ⟨g, hga, hgb⟩) = List.ofFn g := rfl
            rw [hw]
            exact trunc_isStreamPrefix x _)
        rw [tableMap, hidx, swapMap, if_neg ha, if_neg hb]
        show ThompsonV.prepend (List.ofFn g)
          (ThompsonV.drop (List.ofFn g).length x) = x
        exact prepend_drop_of_isStreamPrefix _ x
          (trunc_isStreamPrefix x _)
  rw [← hEB]
  exact tableEquiv_mem_thompsonV' _ _ _ _

end SwapPermMem


section VNotLEF

open Classical ThompsonV

variable (k : Type) [Field k]

theorem toPerm_congr {u v : (BinaryLeavittAlgebra k)ˣ}
    (h : u = v) (hu : u ∈ deltaPermUnits k) (hv : v ∈ deltaPermUnits k) :
    toPerm k ⟨u, hu⟩ = toPerm k ⟨v, hv⟩ := by
  congr 1
  exact Subtype.ext h

theorem toPerm_mk_mul (u v : (BinaryLeavittAlgebra k)ˣ)
    (hu : u ∈ deltaPermUnits k) (hv : v ∈ deltaPermUnits k)
    (huv : u * v ∈ deltaPermUnits k) :
    toPerm k ⟨u * v, huv⟩ = toPerm k ⟨u, hu⟩ * toPerm k ⟨v, hv⟩ := by
  rw [show (⟨u * v, huv⟩ : deltaPermUnits k) =
    ⟨u, hu⟩ * ⟨v, hv⟩ from Subtype.ext rfl, map_mul]

theorem toPerm_mk_inv (u : (BinaryLeavittAlgebra k)ˣ)
    (hu : u ∈ deltaPermUnits k) (hui : u⁻¹ ∈ deltaPermUnits k) :
    toPerm k ⟨u⁻¹, hui⟩ = (toPerm k ⟨u, hu⟩)⁻¹ := by
  rw [show (⟨u⁻¹, hui⟩ : deltaPermUnits k) =
    (⟨u, hu⟩ : deltaPermUnits k)⁻¹ from Subtype.ext rfl, map_inv]

theorem toPerm_cylinderSwap (a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) :
    toPerm k ⟨(family k).cylinderSwap a b hab hba,
      cylinderSwap_mem_deltaPermUnits k a b hab hba⟩ =
    swapPerm a b hab hba := by
  apply deltaPermUnits_sigma_unique k
  intro x c
  calc
    Finsupp.single (toPerm k ⟨(family k).cylinderSwap a b hab hba,
        cylinderSwap_mem_deltaPermUnits k a b hab hba⟩ x) c =
        finsuppStreamRep k
          (((family k).cylinderSwap a b hab hba :
            (BinaryLeavittAlgebra k)ˣ) : BinaryLeavittAlgebra k)
          (Finsupp.single x c) :=
      (toPerm_spec k _ x c).symm
    _ = Finsupp.single (swapMap a b x) c :=
      finsuppStreamRep_cylinderSwap_single k a b hab hba x c
    _ = Finsupp.single (swapPerm a b hab hba x) c := by
      rw [swapPerm_apply]

theorem toPerm_cylinderSwap_mem (a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) :
    toPerm k ⟨(family k).cylinderSwap a b hab hba,
      cylinderSwap_mem_deltaPermUnits k a b hab hba⟩ ∈ thompsonV := by
  rw [toPerm_cylinderSwap]
  exact swapPerm_mem_thompsonV a b hab hba

theorem toPerm_cornerHom_cylinderSwap_mem (a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a)
    (hmem : (family k).cornerHom ((family k).cylinderSwap a b hab hba) ∈
      deltaPermUnits k) :
    toPerm k ⟨(family k).cornerHom ((family k).cylinderSwap a b hab hba),
      hmem⟩ ∈ thompsonV := by
  have hval : (family k).cornerHom ((family k).cylinderSwap a b hab hba) =
      (family k).cylinderSwap ([1] ++ a) ([1] ++ b)
        (fun h ↦ hab ((List.prefix_append_right_inj [1]).1 h))
        (fun h ↦ hba ((List.prefix_append_right_inj [1]).1 h)) := by
    rw [cornerHom_eq_prefixInsertionUnit,
      prefixInsertionUnit_cylinderSwap]
  rw [toPerm_congr k hval hmem
    (cylinderSwap_mem_deltaPermUnits k _ _ _ _)]
  exact toPerm_cylinderSwap_mem k _ _ _ _

theorem toPerm_cornerHom_insertion_cylinderSwap_mem
    (l a b : List (Fin 2)) (hab : ¬ a <+: b) (hba : ¬ b <+: a)
    (hmem : (family k).cornerHom ((family k).prefixInsertionUnit l
      ((family k).cylinderSwap a b hab hba)) ∈ deltaPermUnits k) :
    toPerm k ⟨(family k).cornerHom ((family k).prefixInsertionUnit l
      ((family k).cylinderSwap a b hab hba)), hmem⟩ ∈ thompsonV := by
  have hval : (family k).prefixInsertionUnit l
      ((family k).cylinderSwap a b hab hba) =
      (family k).cylinderSwap (l ++ a) (l ++ b)
        (fun h ↦ hab ((List.prefix_append_right_inj l).1 h))
        (fun h ↦ hba ((List.prefix_append_right_inj l).1 h)) :=
    prefixInsertionUnit_cylinderSwap _ l a b hab hba
  rw [toPerm_congr k (congrArg (family k).cornerHom hval) hmem
    (by
      rw [← congrArg (family k).cornerHom hval]
      exact hmem)]
  exact toPerm_cornerHom_cylinderSwap_mem k _ _ _ _ _

theorem toPerm_mem_thompsonV_of_mem_witness (x : (BinaryLeavittAlgebra k)ˣ)
    (hx : x ∈ (family k).cornerWitnessSubgroup) :
    toPerm k ⟨x, cornerWitness_le_deltaPermUnits k hx⟩ ∈ thompsonV := by
  induction hx using Subgroup.closure_induction with
  | mem y hy =>
      rcases hy with rfl | rfl
      · -- the cornered generator A
        have hval : (family k).cornerHom (family k).generatorA =
            ((family k).cornerHom ((family k).cylinderSwap [0] [1, 0]
                (by decide) (by decide)) *
              (family k).cornerHom ((family k).cylinderSwap [0] [1, 1]
                (by decide) (by decide)) *
              (family k).cornerHom ((family k).cylinderSwap [0] [1]
                (by decide) (by decide)))⁻¹ := by
          rw [LeavittFamily.generatorA, ← map_mul, ← map_mul, ← map_inv,
            LeavittFamily.rootRotation]
        rw [toPerm_congr k hval _ (by
          rw [← hval]
          exact cornerWitness_le_deltaPermUnits k
            (Subgroup.subset_closure (Or.inl rfl)))]
        rw [toPerm_mk_inv k _ (Subgroup.mul_mem _
          (Subgroup.mul_mem _
            (cornerHom_cylinderSwap_mem k [0] [1, 0] (by decide) (by decide))
            (cornerHom_cylinderSwap_mem k [0] [1, 1] (by decide) (by decide)))
          (cornerHom_cylinderSwap_mem k [0] [1] (by decide) (by decide))) _]
        refine Subgroup.inv_mem _ ?_
        rw [toPerm_mk_mul k _ _ (Subgroup.mul_mem _
            (cornerHom_cylinderSwap_mem k [0] [1, 0] (by decide) (by decide))
            (cornerHom_cylinderSwap_mem k [0] [1, 1] (by decide) (by decide)))
          (cornerHom_cylinderSwap_mem k [0] [1] (by decide) (by decide)) _]
        rw [toPerm_mk_mul k _ _
          (cornerHom_cylinderSwap_mem k [0] [1, 0] (by decide) (by decide))
          (cornerHom_cylinderSwap_mem k [0] [1, 1] (by decide) (by decide)) _]
        exact Subgroup.mul_mem _
          (Subgroup.mul_mem _
            (toPerm_cornerHom_cylinderSwap_mem k [0] [1, 0]
              (by decide) (by decide) _)
            (toPerm_cornerHom_cylinderSwap_mem k [0] [1, 1]
              (by decide) (by decide) _))
          (toPerm_cornerHom_cylinderSwap_mem k [0] [1]
            (by decide) (by decide) _)
      · -- the cornered generator B
        have hval : (family k).cornerHom (family k).generatorB =
            ((family k).cornerHom ((family k).prefixInsertionUnit [1]
                ((family k).cylinderSwap [0] [1, 0]
                  (by decide) (by decide))) *
              (family k).cornerHom ((family k).prefixInsertionUnit [1]
                ((family k).cylinderSwap [0] [1, 1]
                  (by decide) (by decide))) *
              (family k).cornerHom ((family k).prefixInsertionUnit [1]
                ((family k).cylinderSwap [0] [1]
                  (by decide) (by decide))))⁻¹ := by
          rw [LeavittFamily.generatorB, LeavittFamily.rightRotation,
            map_inv, LeavittFamily.rootRotation, map_mul,
            map_mul, map_mul, map_mul,
            LeavittFamily.prefixInsertion_apply,
            LeavittFamily.prefixInsertion_apply,
            LeavittFamily.prefixInsertion_apply]
        rw [toPerm_congr k hval _ (by
          rw [← hval]
          exact cornerWitness_le_deltaPermUnits k
            (Subgroup.subset_closure (Or.inr rfl)))]
        rw [toPerm_mk_inv k _ (Subgroup.mul_mem _
          (Subgroup.mul_mem _
            (cornerHom_insertion_cylinderSwap_mem k [1] [0] [1, 0]
              (by decide) (by decide))
            (cornerHom_insertion_cylinderSwap_mem k [1] [0] [1, 1]
              (by decide) (by decide)))
          (cornerHom_insertion_cylinderSwap_mem k [1] [0] [1]
            (by decide) (by decide))) _]
        refine Subgroup.inv_mem _ ?_
        rw [toPerm_mk_mul k _ _ (Subgroup.mul_mem _
            (cornerHom_insertion_cylinderSwap_mem k [1] [0] [1, 0]
              (by decide) (by decide))
            (cornerHom_insertion_cylinderSwap_mem k [1] [0] [1, 1]
              (by decide) (by decide)))
          (cornerHom_insertion_cylinderSwap_mem k [1] [0] [1]
            (by decide) (by decide)) _]
        rw [toPerm_mk_mul k _ _
          (cornerHom_insertion_cylinderSwap_mem k [1] [0] [1, 0]
            (by decide) (by decide))
          (cornerHom_insertion_cylinderSwap_mem k [1] [0] [1, 1]
            (by decide) (by decide)) _]
        exact Subgroup.mul_mem _
          (Subgroup.mul_mem _
            (toPerm_cornerHom_insertion_cylinderSwap_mem k [1] [0] [1, 0]
              (by decide) (by decide) _)
            (toPerm_cornerHom_insertion_cylinderSwap_mem k [1] [0] [1, 1]
              (by decide) (by decide) _))
          (toPerm_cornerHom_insertion_cylinderSwap_mem k [1] [0] [1]
            (by decide) (by decide) _)
  | one =>
      rw [toPerm_congr k rfl _ (Subgroup.one_mem _),
        show (⟨1, Subgroup.one_mem _⟩ : deltaPermUnits k) = 1 from
          Subtype.ext rfl, map_one]
      exact Subgroup.one_mem _
  | mul y z hy hz ihy ihz =>
      rw [toPerm_mk_mul k y z (cornerWitness_le_deltaPermUnits k hy)
        (cornerWitness_le_deltaPermUnits k hz) _]
      exact Subgroup.mul_mem _ ihy ihz
  | inv y hy ihy =>
      rw [toPerm_mk_inv k y (cornerWitness_le_deltaPermUnits k hy) _]
      exact Subgroup.inv_mem _ ihy

/-- **Proposition `prop:vnotlef`, unconditionally** (checkpoint `D4`):
Thompson's group `V` is not LEF.  The manuscript derives this from the
cited simplicity and finite presentability of `V`; here it follows
kernel-checked from the finite-obstruction witness, which embeds into `V`
through the faithful stream action, since LEF passes to subgroups. -/
theorem thompsonV_not_isLEF : ¬ IsLEF ↥thompsonV := by
  intro hLEF
  refine (family (ZMod 2)).not_isLEF_cornerWitnessSubgroup ?_
  refine isLEF_of_injective (G := ↥thompsonV) ?_ ?_ hLEF
  · exact {
      toFun := fun w ↦ ⟨toPerm (ZMod 2)
          ⟨(w : (BinaryLeavittAlgebra (ZMod 2))ˣ),
            cornerWitness_le_deltaPermUnits (ZMod 2) w.property⟩,
        toPerm_mem_thompsonV_of_mem_witness (ZMod 2) w w.property⟩
      map_one' := by
        apply Subtype.ext
        show toPerm (ZMod 2) ⟨1, _⟩ = 1
        rw [show (⟨1, cornerWitness_le_deltaPermUnits (ZMod 2)
            (Subgroup.one_mem _)⟩ : deltaPermUnits (ZMod 2)) = 1 from
          Subtype.ext rfl, map_one]
      map_mul' := fun w₁ w₂ ↦ by
        apply Subtype.ext
        exact toPerm_mk_mul (ZMod 2) _ _
          (cornerWitness_le_deltaPermUnits (ZMod 2) w₁.property)
          (cornerWitness_le_deltaPermUnits (ZMod 2) w₂.property) _ }
  · intro w₁ w₂ h
    have h1 := congrArg Subtype.val h
    have h2 := toPerm_injective (ZMod 2) h1
    have h3 := congrArg Subtype.val h2
    exact Subtype.ext h3

end VNotLEF

end BinaryLeavitt
end NonsoficGroupsExist
