import NonsoficGroupsExist.ThompsonVEmbedding
import NonsoficGroupsExist.ThompsonWitness

/-!
# The corner witness inside the permutation units

The non-LEF corner witness subgroup is generated by cylinder swaps and
their corner insertions.  Every cylinder swap acts on the faithful stream
basis as the boundary transposition of the two cylinders, so the entire
witness lies in the basis-permuting units (checkpoint `D3`, first half).
-/

namespace NonsoficGroupsExist
namespace BinaryLeavitt

open ThompsonV LeavittFamily

open Classical in
/-- The boundary transposition of two cylinders. -/
noncomputable def swapMap (a b : List (Fin 2)) (x : Boundary) :
    Boundary :=
  if IsStreamPrefix a x then
    ThompsonV.prepend b (ThompsonV.drop a.length x)
  else if IsStreamPrefix b x then
    ThompsonV.prepend a (ThompsonV.drop b.length x)
  else x

theorem not_isStreamPrefix_prepend {a b : List (Fin 2)}
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) (y : Boundary) :
    ¬ IsStreamPrefix a (ThompsonV.prepend b y) := by
  intro h
  rcases prefix_or_prefix_of_isStreamPrefix h
    (isStreamPrefix_prepend b y) with hc | hc
  · exact hab hc
  · exact hba hc

theorem not_both_isStreamPrefix {a b : List (Fin 2)}
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) {x : Boundary}
    (ha : IsStreamPrefix a x) : ¬ IsStreamPrefix b x := by
  intro hb
  rcases prefix_or_prefix_of_isStreamPrefix ha hb with hc | hc
  · exact hab hc
  · exact hba hc

open Classical in
theorem swapMap_involutive (a b : List (Fin 2)) (hab : ¬ a <+: b)
    (hba : ¬ b <+: a) : Function.Involutive (swapMap a b) := by
  intro x
  by_cases ha : IsStreamPrefix a x
  · have h1 : swapMap a b x =
        ThompsonV.prepend b (ThompsonV.drop a.length x) := by
      rw [swapMap, if_pos ha]
    rw [h1, swapMap,
      if_neg (not_isStreamPrefix_prepend hab hba _),
      if_pos (isStreamPrefix_prepend b _), drop_prepend,
      prepend_drop_of_isStreamPrefix a x ha]
  · by_cases hb : IsStreamPrefix b x
    · have h1 : swapMap a b x =
          ThompsonV.prepend a (ThompsonV.drop b.length x) := by
        rw [swapMap, if_neg ha, if_pos hb]
      rw [h1, swapMap,
        if_pos (isStreamPrefix_prepend a _),
        drop_prepend, prepend_drop_of_isStreamPrefix b x hb]
    · have h1 : swapMap a b x = x := by
        rw [swapMap, if_neg ha, if_neg hb]
      rw [h1, h1]

open Classical in
/-- The boundary transposition as a permutation. -/
noncomputable def swapPerm (a b : List (Fin 2)) (hab : ¬ a <+: b)
    (hba : ¬ b <+: a) : Equiv.Perm Boundary :=
  (swapMap_involutive a b hab hba).toPerm

@[simp] theorem swapPerm_apply (a b : List (Fin 2)) (hab : ¬ a <+: b)
    (hba : ¬ b <+: a) (x : Boundary) :
    swapPerm a b hab hba x = swapMap a b x := rfl

variable (k : Type) [Field k]

open Classical in
/-- A cylinder swap acts on the stream basis by the boundary
transposition. -/
theorem finsuppStreamRep_cylinderSwap_single (a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) (x : Boundary) (c : k) :
    finsuppStreamRep k
        (((family k).cylinderSwap a b hab hba :
          (BinaryLeavittAlgebra k)ˣ) : BinaryLeavittAlgebra k)
        (Finsupp.single x c) =
      Finsupp.single (swapMap a b x) c := by
  rw [cylinderSwap_val, transpositionValue]
  simp only [map_sub, map_add, map_mul, map_one, LinearMap.sub_apply,
    LinearMap.add_apply, Module.End.mul_apply, Module.End.one_apply]
  rw [finsuppStreamRep_wordT_single, finsuppStreamRep_wordT_single]
  by_cases ha : IsStreamPrefix a x
  · have hb : ¬ IsStreamPrefix b x := not_both_isStreamPrefix hab hba ha
    rw [if_pos ha, if_neg hb]
    simp only [map_zero]
    rw [finsuppStreamRep_wordS_single, finsuppStreamRep_wordS_single,
      prepend_drop_of_isStreamPrefix a x ha]
    rw [swapMap, if_pos ha]
    abel
  · by_cases hb : IsStreamPrefix b x
    · rw [if_pos hb, if_neg ha]
      simp only [map_zero]
      rw [finsuppStreamRep_wordS_single, finsuppStreamRep_wordS_single,
        prepend_drop_of_isStreamPrefix b x hb]
      rw [swapMap, if_neg ha, if_pos hb]
      abel
    · rw [if_neg ha, if_neg hb]
      simp only [map_zero]
      rw [swapMap, if_neg ha, if_neg hb]
      abel

theorem cylinderSwap_mem_deltaPermUnits (a b : List (Fin 2))
    (hab : ¬ a <+: b) (hba : ¬ b <+: a) :
    (family k).cylinderSwap a b hab hba ∈ deltaPermUnits k :=
  ⟨swapPerm a b hab hba, fun x c ↦ by
    rw [swapPerm_apply]
    exact finsuppStreamRep_cylinderSwap_single k a b hab hba x c⟩

end BinaryLeavitt
end NonsoficGroupsExist
