import NonsoficGroupsExist.Sofic.ScalarCocycle
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.GroupTheory.OrderOfElement

/-!
# How many characters see a cocycle

Remark `rem:scalarcocycle` records that a projective model assembled from a
family of characters pays a *graded* version of the price a global scalar pays:
after untwisting, the multiplicative defect is the proportion of characters that
see the cocycle.  That sentence is only useful if the proportion can be
computed, and it can -- it is a greatest common divisor, and the computation is
finite.

The characters of `ℤ/n` are `β_l(x) = exp(2πi lx/n)` for `l ∈ ℤ/n`, and
`β_l` kills `α` exactly when `lα = 0` in `ℤ/n`.  So the count that matters is
the size of the annihilator of `α`, and

    #{ l : ℤ/n | lα = 0 }  =  gcd(n, α).

Composing with the untwisting identity of `ScalarCocycle` gives the defect of
the character-indexed model outright:

    d_Hamm(untwist, untwist twisted by α)  =  1 - gcd(n, α)/n.

Two readings, and they are the two ends of the same formula.  A cocycle
invisible to almost every character -- `gcd(n,α)` close to `n` -- costs almost
nothing.  A cocycle whose value *generates*, which is the case for the
microstates of Thom's group `K` at level `p^k`, has `gcd = 1`: exactly one
character out of `p^k` kills it, the defect is `1 - p^{-k}`, and untwisting
destroys the model completely as `k` grows.  This is the quantitative form of
the obstruction that Remark `rem:thomK` describes in words, and it says the
obvious route from Thom's projective microstates to a sofic approximation does
not merely fail to be obvious -- it fails, with a computed defect.

Nothing here decides Question 3.4.  It prices one route and closes it.
-/

namespace NonsoficGroupsExist

open Finset

/-! ## The annihilator count -/

/-- The additive map `l ↦ lα` has image the cyclic subgroup generated by `α`.
Both inclusions are the statement that in `ℤ/n` a ring multiple and an integer
multiple are the same thing. -/
theorem range_mulRight (n : ℕ) [NeZero n] (a : ZMod n) :
    (AddMonoidHom.mulRight a).range = AddSubgroup.zmultiples a := by
  ext x
  constructor
  · rintro ⟨l, rfl⟩
    refine ⟨(l : ZMod n).val, ?_⟩
    show ((l : ZMod n).val : ℤ) • a = _
    rw [natCast_zsmul, nsmul_eq_mul, ZMod.natCast_val, ZMod.cast_id]
    rfl
  · rintro ⟨k, rfl⟩
    exact ⟨(k : ZMod n), by simp [zsmul_eq_mul]⟩

/-- **The annihilator of `α` in `ℤ/n` has exactly `gcd(n, α)` elements.**
The map `l ↦ lα` has image of size `addOrderOf α = n / gcd(n, α)`, so by
Lagrange its kernel has size `gcd(n, α)`. -/
theorem card_annihilator (n : ℕ) [NeZero n] (a : ZMod n) :
    (univ.filter fun l : ZMod n ↦ l * a = 0).card = Nat.gcd n a.val := by
  classical
  have hn : n ≠ 0 := NeZero.ne n
  set f : ZMod n →+ ZMod n := AddMonoidHom.mulRight a with hf
  -- the filter is the kernel
  have hker : (univ.filter fun l : ZMod n ↦ l * a = 0).card = Nat.card f.ker := by
    rw [Nat.card_eq_fintype_card, Fintype.card_subtype]
    congr 1
    ext l
    simp [hf, AddMonoidHom.mem_ker]
  -- the range has size `n / gcd`
  have haddord : addOrderOf a = n / Nat.gcd n a.val := by
    conv_lhs => rw [show a = ((a.val : ℕ) : ZMod n) from by rw [ZMod.natCast_val, ZMod.cast_id]]
    exact ZMod.addOrderOf_coe _ hn
  have hrange : Nat.card f.range = n / Nat.gcd n a.val := by
    rw [hf, range_mulRight, Nat.card_zmultiples, haddord]
  -- Lagrange
  have hquot : Nat.card (ZMod n ⧸ f.ker) = Nat.card f.range :=
    Nat.card_congr (QuotientAddGroup.quotientKerEquivRange f).toEquiv
  have hlag : Nat.card (ZMod n) = Nat.card (ZMod n ⧸ f.ker) * Nat.card f.ker :=
    AddSubgroup.card_eq_card_quotient_mul_card_addSubgroup f.ker
  have hcard : Nat.card (ZMod n) = n := by
    rw [Nat.card_eq_fintype_card, ZMod.card]
  have hdvd : Nat.gcd n a.val ∣ n := Nat.gcd_dvd_left _ _
  have hgpos : 0 < Nat.gcd n a.val :=
    Nat.gcd_pos_of_pos_left _ (Nat.pos_of_ne_zero hn)
  have hqpos : 0 < n / Nat.gcd n a.val := Nat.div_pos (Nat.le_of_dvd
    (Nat.pos_of_ne_zero hn) hdvd) hgpos
  rw [hker]
  rw [hquot, hrange, hcard] at hlag
  have hmul : (n / Nat.gcd n a.val) * Nat.gcd n a.val = n :=
    Nat.div_mul_cancel hdvd
  have := hlag.symm.trans hmul.symm
  exact Nat.eq_of_mul_eq_mul_left hqpos this

/-- The complementary count: the characters that *see* `α`. -/
theorem card_sees (n : ℕ) [NeZero n] (a : ZMod n) :
    (univ.filter fun l : ZMod n ↦ l * a ≠ 0).card = n - Nat.gcd n a.val := by
  classical
  have hsplit := Finset.card_filter_add_card_filter_not
    (s := (univ : Finset (ZMod n))) (fun l : ZMod n ↦ l * a = 0)
  rw [card_annihilator, Finset.card_univ, ZMod.card] at hsplit
  simp only [ne_eq]
  omega

/-! ## The defect of a character-indexed model -/

/-- The model indexed by the characters of `ℤ/m`. -/
abbrev characterModel (m : ℕ) [NeZero m] : FiniteModel :=
  ⟨ZMod m, inferInstance, inferInstance⟩

/-- **The price of untwisting a character-indexed projective model.**  Take the
model whose points are the characters of `ℤ/m`, and twist the phase at the
character `l` by that character's value on the cocycle datum `α` -- which is the
additive `lα`.  Then the untwisted permutations disagree exactly on the
characters that see `α`, so the multiplicative defect is

    1 - gcd(m, α)/m.

For `α` a generator this is `1 - 1/m`: the model is destroyed. -/
theorem hammingDistance_characterUntwist (m : ℕ) [NeZero m] (α : ZMod m)
    (d : ZMod m → ZMod m) (σ : Equiv.Perm (ZMod m)) :
    hammingDistance (wreathModel (characterModel m) m)
        (wreathPerm (characterModel m) m d σ)
        (wreathPerm (characterModel m) m (fun l ↦ d l + l * α) σ)
      = 1 - (Nat.gcd m α.val : ℝ) / m := by
  classical
  have h := hammingDistance_wreathPerm_blockConst (characterModel m) m
    (L := ZMod m) (fun l ↦ l) (fun l ↦ l * α) d σ
  rw [h]
  have hcard : Fintype.card (characterModel m) = m := ZMod.card m
  rw [hcard, card_sees]
  have hdvd : Nat.gcd m α.val ∣ m := Nat.gcd_dvd_left _ _
  have hle : Nat.gcd m α.val ≤ m := Nat.le_of_dvd (Nat.pos_of_ne_zero (NeZero.ne m)) hdvd
  have hm : (m : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne m)
  rw [Nat.cast_sub hle]
  field_simp

/-- **The generating case.**  A cocycle datum that generates `ℤ/m` is killed by
exactly one character, and untwisting then costs all but a `1/m` fraction of the
model.  This is the case of Thom's microstates at level `p^k`. -/
theorem hammingDistance_characterUntwist_generator (m : ℕ) [NeZero m]
    (α : ZMod m) (hα : Nat.gcd m α.val = 1)
    (d : ZMod m → ZMod m) (σ : Equiv.Perm (ZMod m)) :
    hammingDistance (wreathModel (characterModel m) m)
        (wreathPerm (characterModel m) m d σ)
        (wreathPerm (characterModel m) m (fun l ↦ d l + l * α) σ)
      = 1 - 1 / m := by
  rw [hammingDistance_characterUntwist, hα]
  norm_num

end NonsoficGroupsExist
