import NonsoficGroupsExist.KOne.AllRanksElementary
import Mathlib.Algebra.Colimit.DirectLimit
import Mathlib.Data.Fintype.BigOperators
import Mathlib.GroupTheory.QuotientGroup.Basic

/-!
# The classical `K₁`: `colim_n GL_n(L) / E_∞(L)`, and its triviality over `L_k(1,2)`

`KOne/WhiteheadQuotient.lean` builds `K₁` in *Whitehead form* -- the quotient of
`Lˣ` by the units with elementary diagonal stabilization -- and proves it
trivial.  That is a rank-one statement.  This module builds the **classical**
object instead: the direct limit

  `GL(L) = colim_n GL_n(L)`,   `K₁(L) = GL(L) / E_∞(L)`,

where the colimit is taken along the block-diagonal inclusions
`GL_n(L) → GL_m(L)`, `A ↦ diag(A, 1_{m-n})`, and `E_∞(L) ≤ GL(L)` is the
subgroup generated by the images of the elementary subgroups `EL_n(L)` at every
finite rank.  `binaryLeavittClassicalK1_subsingleton` proves that this group is
trivial over `L_k(1,2)`, for every field `k`.

## The construction

* `padEntry`, `stabMatrix` -- the block padding `A ↦ diag(A, 1)` written as an
  entry formula on natural-number indices.  Writing it this way (rather than by
  `Matrix.fromBlocks` along a reindexing `Fin n ⊕ Fin (m - n) ≃ Fin m`) is what
  makes *functoriality* -- `stabMatrix_stabMatrix`, padding twice equals padding
  once -- a computation with no induction on `m - n` and no transport of
  reindexing isomorphisms.  That law is exactly what a direct system over `ℕ`
  needs.
* `stabMonoidHom`, `glStab` -- the padding as a monoid map on matrix rings and
  hence on their unit groups.  Multiplicativity genuinely needs `n ≤ m`
  (`stabMatrix_mul`); the identity is preserved for free.
* `glDirectedSystem` -- the two functoriality laws, packaged as Mathlib's
  `DirectedSystem`.  The colimit is then Mathlib's `DirectLimit`, which already
  carries the group structure, so nothing about quotients of sigma types is
  re-derived here.
* `ClassicalGLColim`, `glColimOf`, `elementaryColim` -- `GL(R)`, the canonical
  maps `GL_n(R) → GL(R)`, and `E_∞(R)`.

## What this discharges

The triviality is a corollary of the all-rank equality `GL_n(L) = EL_n(L)`
(`BinaryLeavitt.elementaryGroup_eq_top`, manuscript `prop:glel(i)`): a class in
the colimit is represented at some rank `n`, and equally at rank `max n 2`,
where every invertible matrix is already elementary -- so the class lies in
`E_∞`.  Hence `binaryLeavittElementaryColim_eq_top`, and the quotient collapses.
This is the colimit argument that the docstring of `KOne/WhiteheadQuotient.lean`
describes and leaves to the reader; it is formalized here.  Together with
`binaryLeavittWhiteheadK1_subsingleton` it closes manuscript
`cor:K1consequences` in both of its forms -- Whitehead and classical.

`E_∞` is defined as the supremum of the images of the `EL_n`, i.e. as the
subgroup of `GL(L)` generated by all elementary matrices of all finite ranks,
which is the classical definition.  That the *elementary* groups separately form
a direct system -- that the padding carries `EL_n` into `EL_m` -- is true, but it
is never needed below and is therefore omitted: with `GL_n = EL_n` at every rank
`≥ 2` the supremum is all of `GL(L)` anyway.
-/

namespace NonsoficGroupsExist

section Padding

variable {R : Type*} [Ring R]

/-- The entry function of the block padding `A ↦ diag(A, 1)`, read at
natural-number indices: `A` inside the `n × n` corner, the identity matrix
outside it.  The values straddling the corner boundary are forced: such an index
pair is off the diagonal, so the identity contributes `0` there. -/
def padEntry {n : ℕ} (A : Matrix (Fin n) (Fin n) R) (x y : ℕ) : R :=
  if hx : x < n then (if hy : y < n then A ⟨x, hx⟩ ⟨y, hy⟩ else 0)
  else if x = y then 1 else 0

theorem padEntry_of_lt_lt {n : ℕ} (A : Matrix (Fin n) (Fin n) R) {x y : ℕ}
    (hx : x < n) (hy : y < n) : padEntry A x y = A ⟨x, hx⟩ ⟨y, hy⟩ := by
  simp only [padEntry, dif_pos hx, dif_pos hy]

theorem padEntry_of_lt_ge {n : ℕ} (A : Matrix (Fin n) (Fin n) R) {x y : ℕ}
    (hx : x < n) (hy : ¬ y < n) : padEntry A x y = 0 := by
  simp only [padEntry, dif_pos hx, dif_neg hy]

theorem padEntry_of_ge {n : ℕ} (A : Matrix (Fin n) (Fin n) R) {x y : ℕ}
    (hx : ¬ x < n) : padEntry A x y = if x = y then 1 else 0 := by
  simp only [padEntry, dif_neg hx]

theorem padEntry_diag_of_ge {n : ℕ} (A : Matrix (Fin n) (Fin n) R) {x : ℕ}
    (hx : ¬ x < n) : padEntry A x x = 1 := by
  rw [padEntry_of_ge A hx]
  simp

theorem padEntry_one (n : ℕ) (x y : ℕ) :
    padEntry (1 : Matrix (Fin n) (Fin n) R) x y = if x = y then 1 else 0 := by
  by_cases hx : x < n
  · by_cases hy : y < n
    · rw [padEntry_of_lt_lt (1 : Matrix (Fin n) (Fin n) R) hx hy,
        Matrix.one_apply]
      by_cases hxy : x = y
      · subst hxy
        simp
      · have hne : (⟨x, hx⟩ : Fin n) ≠ ⟨y, hy⟩ :=
          fun hc => hxy (congrArg Fin.val hc)
        rw [if_neg hne, if_neg hxy]
    · have hne : x ≠ y := by omega
      rw [padEntry_of_lt_ge (1 : Matrix (Fin n) (Fin n) R) hx hy, if_neg hne]
  · rw [padEntry_of_ge (1 : Matrix (Fin n) (Fin n) R) hx]

/-- The block padding `A ↦ diag(A, 1_{m-n})` of an `n × n` matrix to an
`m × m` matrix.  For `m < n` the same formula truncates instead; every lemma
below that needs the block picture carries the hypothesis `n ≤ m`. -/
noncomputable def stabMatrix {n : ℕ} (m : ℕ) (A : Matrix (Fin n) (Fin n) R) :
    Matrix (Fin m) (Fin m) R :=
  Matrix.of fun x y => padEntry A (x : ℕ) (y : ℕ)

@[simp] theorem stabMatrix_apply {n m : ℕ} (A : Matrix (Fin n) (Fin n) R)
    (x y : Fin m) : stabMatrix m A x y = padEntry A (x : ℕ) (y : ℕ) := rfl

/-- Padding to the rank a matrix already has is the identity. -/
@[simp] theorem stabMatrix_self {n : ℕ} (A : Matrix (Fin n) (Fin n) R) :
    stabMatrix n A = A := by
  ext x y
  rw [stabMatrix_apply]
  exact padEntry_of_lt_lt A x.isLt y.isLt

@[simp] theorem stabMatrix_one (n m : ℕ) :
    stabMatrix m (1 : Matrix (Fin n) (Fin n) R) = 1 := by
  ext x y
  rw [stabMatrix_apply, padEntry_one, Matrix.one_apply]
  by_cases hxy : x = y
  · subst hxy
    simp
  · have hne : (x : ℕ) ≠ (y : ℕ) := fun hc => hxy (Fin.val_injective hc)
    rw [if_neg hne, if_neg hxy]

/-- **The padding is multiplicative.**  This is the one place `n ≤ m` is
needed: for `m < n` the formula truncates, and the truncation of a product is
not the product of the truncations. -/
theorem stabMatrix_mul {n m : ℕ} (h : n ≤ m) (A B : Matrix (Fin n) (Fin n) R) :
    stabMatrix m (A * B) = stabMatrix m A * stabMatrix m B := by
  ext x y
  rw [Matrix.mul_apply]
  simp only [stabMatrix_apply]
  by_cases hx : (x : ℕ) < n
  · -- inside the corner: the summation range drops from rank `m` to rank `n`
    have hrange : ∀ p : ℕ,
        ∑ z : Fin p, padEntry A (x : ℕ) (z : ℕ) * padEntry B (z : ℕ) (y : ℕ)
          = ∑ z ∈ Finset.range p,
              padEntry A (x : ℕ) z * padEntry B z (y : ℕ) := fun p =>
      Fin.sum_univ_eq_sum_range
        (fun z => padEntry A (x : ℕ) z * padEntry B z (y : ℕ)) p
    have hsum :
        ∑ z : Fin m,
            padEntry A (x : ℕ) (z : ℕ) * padEntry B (z : ℕ) (y : ℕ)
          = ∑ z : Fin n,
              padEntry A (x : ℕ) (z : ℕ) * padEntry B (z : ℕ) (y : ℕ) := by
      rw [hrange m, hrange n]
      refine (Finset.sum_subset (Finset.range_subset_range.mpr h) ?_).symm
      intro z _ hz
      rw [Finset.mem_range] at hz
      rw [padEntry_of_lt_ge A hx hz, zero_mul]
    rw [hsum]
    by_cases hy : (y : ℕ) < n
    · rw [padEntry_of_lt_lt (A * B) hx hy, Matrix.mul_apply]
      refine Finset.sum_congr rfl ?_
      intro z _
      have h1 : padEntry A (x : ℕ) (z : ℕ) = A ⟨(x : ℕ), hx⟩ z :=
        padEntry_of_lt_lt A hx z.isLt
      have h2 : padEntry B (z : ℕ) (y : ℕ) = B z ⟨(y : ℕ), hy⟩ :=
        padEntry_of_lt_lt B z.isLt hy
      rw [h1, h2]
    · rw [padEntry_of_lt_ge (A * B) hx hy]
      refine (Finset.sum_eq_zero ?_).symm
      intro z _
      rw [padEntry_of_lt_ge B z.isLt hy, mul_zero]
  · -- outside the corner: the sum collapses to its one diagonal term
    have hsingle :
        ∑ z : Fin m, padEntry A (x : ℕ) (z : ℕ) * padEntry B (z : ℕ) (y : ℕ)
          = padEntry A (x : ℕ) (x : ℕ) * padEntry B (x : ℕ) (y : ℕ) := by
      refine Finset.sum_eq_single x ?_ ?_
      · intro z _ hzx
        have hne : (x : ℕ) ≠ (z : ℕ) := fun hc => hzx (Fin.val_injective hc.symm)
        rw [padEntry_of_ge A hx, if_neg hne, zero_mul]
      · intro hxu
        exact absurd (Finset.mem_univ x) hxu
    rw [hsingle, padEntry_diag_of_ge A hx, one_mul, padEntry_of_ge (A * B) hx,
      padEntry_of_ge B hx]

/-- Padding read at natural-number indices does not see the intermediate
rank. -/
theorem padEntry_stabMatrix {n m : ℕ} (h : n ≤ m)
    (A : Matrix (Fin n) (Fin n) R) (x y : ℕ) :
    padEntry (stabMatrix m A) x y = padEntry A x y := by
  by_cases hxm : x < m
  · by_cases hym : y < m
    · rw [padEntry_of_lt_lt (stabMatrix m A) hxm hym]
      exact stabMatrix_apply A ⟨x, hxm⟩ ⟨y, hym⟩
    · rw [padEntry_of_lt_ge (stabMatrix m A) hxm hym]
      by_cases hxn : x < n
      · exact (padEntry_of_lt_ge A hxn (by omega)).symm
      · have hne : x ≠ y := by omega
        rw [padEntry_of_ge A hxn, if_neg hne]
  · rw [padEntry_of_ge (stabMatrix m A) hxm, padEntry_of_ge A (by omega : ¬ x < n)]

/-- **Functoriality of the padding**: padding to rank `m` and then to rank `p`
is padding to rank `p`.  This is the composition law of the direct system. -/
theorem stabMatrix_stabMatrix {n m : ℕ} (h : n ≤ m) (p : ℕ)
    (A : Matrix (Fin n) (Fin n) R) :
    stabMatrix p (stabMatrix m A) = stabMatrix p A := by
  ext x y
  simp only [stabMatrix_apply]
  exact padEntry_stabMatrix h A (x : ℕ) (y : ℕ)

/-- The block padding as a monoid map between matrix rings. -/
noncomputable def stabMonoidHom {n m : ℕ} (h : n ≤ m) :
    Matrix (Fin n) (Fin n) R →* Matrix (Fin m) (Fin m) R where
  toFun := stabMatrix m
  map_one' := stabMatrix_one n m
  map_mul' A B := stabMatrix_mul h A B

end Padding

section Colimit

variable (R : Type*) [Ring R]

/-- The transition map `GL_n(R) → GL_m(R)`, `A ↦ diag(A, 1_{m-n})`, of the
classical direct system of general linear groups. -/
noncomputable def glStab (n m : ℕ) (h : n ≤ m) :
    (Matrix (Fin n) (Fin n) R)ˣ →* (Matrix (Fin m) (Fin m) R)ˣ :=
  Units.map (stabMonoidHom (R := R) h)

@[simp] theorem glStab_val (n m : ℕ) (h : n ≤ m)
    (u : (Matrix (Fin n) (Fin n) R)ˣ) :
    ((glStab R n m h u : (Matrix (Fin m) (Fin m) R)ˣ) :
        Matrix (Fin m) (Fin m) R) =
      stabMatrix m (u : Matrix (Fin n) (Fin n) R) := rfl

/-- The general linear groups of all finite ranks, with the block-diagonal
inclusions between them, form a direct system over `ℕ`. -/
instance glDirectedSystem :
    DirectedSystem (fun n : ℕ => (Matrix (Fin n) (Fin n) R)ˣ)
      (fun i j h => ⇑(glStab R i j h)) where
  map_self := fun _ u => by
    apply Units.ext
    simp only [glStab_val, stabMatrix_self]
  map_map := fun _ _ _ hij _ u => by
    apply Units.ext
    simp only [glStab_val]
    exact stabMatrix_stabMatrix hij _ _

/-- **The stable general linear group** `GL(R) = colim_n GL_n(R)`: the direct
limit of the `GL_n(R)` along the block-diagonal inclusions. -/
noncomputable abbrev ClassicalGLColim :=
  DirectLimit (fun n : ℕ => (Matrix (Fin n) (Fin n) R)ˣ) (glStab R)

/-- The canonical map `GL_n(R) → GL(R)` into the stable general linear
group. -/
noncomputable def glColimOf (n : ℕ) :
    (Matrix (Fin n) (Fin n) R)ˣ →* ClassicalGLColim R where
  toFun u := ⟦⟨n, u⟩⟧
  map_one' := (DirectLimit.one_def n).symm
  map_mul' u v := (DirectLimit.mul_def n u v).symm

@[simp] theorem glColimOf_apply (n : ℕ) (u : (Matrix (Fin n) (Fin n) R)ˣ) :
    glColimOf R n u = ⟦⟨n, u⟩⟧ := rfl

/-- The canonical maps are compatible with the block-diagonal inclusions: a
matrix and its padding name the same class in the stable group. -/
theorem glColimOf_glStab {n m : ℕ} (h : n ≤ m)
    (u : (Matrix (Fin n) (Fin n) R)ˣ) :
    glColimOf R m (glStab R n m h u) = glColimOf R n u := by
  rw [glColimOf_apply, glColimOf_apply]
  exact DirectLimit.mk_apply n m u h

/-- **`E_∞(R)`**: the subgroup of the stable general linear group generated by
the images of the elementary subgroups `EL_n(R)` at every finite rank. -/
noncomputable def elementaryColim : Subgroup (ClassicalGLColim R) :=
  ⨆ n : ℕ, (elementaryGroup (Fin n) R).map (glColimOf R n)

theorem glColimOf_mem_elementaryColim {n : ℕ}
    {u : (Matrix (Fin n) (Fin n) R)ˣ} (hu : u ∈ elementaryGroup (Fin n) R) :
    glColimOf R n u ∈ elementaryColim R := by
  show glColimOf R n u ∈
    ⨆ r : ℕ, (elementaryGroup (Fin r) R).map (glColimOf R r)
  exact Subgroup.mem_iSup_of_mem n (Subgroup.mem_map_of_mem _ hu)

end Colimit

section BinaryLeavittClassical

variable (k : Type) [Field k]

/-- **Every class of the stable general linear group of `L_k(1,2)` is
elementary.**  A class is represented at some rank `n`, hence equally at rank
`max n 2`, and there `GL = EL` by `BinaryLeavitt.elementaryGroup_eq_top`. -/
theorem binaryLeavittMem_elementaryColim
    (z : ClassicalGLColim (BinaryLeavitt.BinaryLeavittAlgebra k)) :
    z ∈ elementaryColim (BinaryLeavitt.BinaryLeavittAlgebra k) := by
  induction z using DirectLimit.induction with
  | ih n u =>
      have hn : n ≤ max n 2 := le_max_left n 2
      have hmem :
          glStab (BinaryLeavitt.BinaryLeavittAlgebra k) n (max n 2) hn u ∈
            elementaryGroup (Fin (max n 2))
              (BinaryLeavitt.BinaryLeavittAlgebra k) := by
        rw [BinaryLeavitt.elementaryGroup_eq_top k (max n 2) (le_max_right n 2)]
        exact Subgroup.mem_top _
      have hz := glColimOf_mem_elementaryColim
        (BinaryLeavitt.BinaryLeavittAlgebra k) hmem
      rwa [glColimOf_glStab, glColimOf_apply] at hz

/-- **`E_∞(L_k(1,2))` is everything**: the elementary subgroup of the stable
general linear group is the whole stable general linear group.  Subgroup form of
`binaryLeavittMem_elementaryColim`. -/
theorem binaryLeavittElementaryColim_eq_top :
    elementaryColim (BinaryLeavitt.BinaryLeavittAlgebra k) = ⊤ :=
  Subgroup.eq_top_iff'.mpr (binaryLeavittMem_elementaryColim k)

/-- `E_∞` is normal because it is everything. -/
instance binaryLeavittElementaryColim_normal :
    (elementaryColim (BinaryLeavitt.BinaryLeavittAlgebra k)).Normal := by
  rw [binaryLeavittElementaryColim_eq_top k]
  infer_instance

/-- **`K₁(L_k(1,2))` in classical form**: the stable general linear group
`colim_n GL_n(L)` modulo the elementary subgroup `E_∞(L)`.  Contrast
`BinaryLeavittWhiteheadK1`, which is the rank-one Whitehead quotient
`Lˣ / stableUnits L`. -/
noncomputable abbrev BinaryLeavittClassicalK1 :=
  ClassicalGLColim (BinaryLeavitt.BinaryLeavittAlgebra k) ⧸
    elementaryColim (BinaryLeavitt.BinaryLeavittAlgebra k)

/-- **`K₁(L_k(1,2)) = 0` in classical form**, over every field: the direct-limit
`K₁` of the binary Leavitt algebra is trivial.  This is the colimit consequence
of `GL_n(L) = EL_n(L)` at every rank `n ≥ 2` (manuscript `prop:glel(i)`), and
together with `binaryLeavittWhiteheadK1_subsingleton` it is manuscript
`cor:K1consequences`. -/
instance binaryLeavittClassicalK1_subsingleton :
    Subsingleton (BinaryLeavittClassicalK1 k) := by
  constructor
  intro x y
  obtain ⟨a, rfl⟩ := QuotientGroup.mk_surjective x
  obtain ⟨b, rfl⟩ := QuotientGroup.mk_surjective y
  have ha : (QuotientGroup.mk a : BinaryLeavittClassicalK1 k) = 1 :=
    (QuotientGroup.eq_one_iff a).mpr (binaryLeavittMem_elementaryColim k a)
  have hb : (QuotientGroup.mk b : BinaryLeavittClassicalK1 k) = 1 :=
    (QuotientGroup.eq_one_iff b).mpr (binaryLeavittMem_elementaryColim k b)
  rw [ha, hb]

/-- The trivial group structure on the classical `K₁`, in `Unique` form. -/
@[reducible] noncomputable def binaryLeavittClassicalK1Unique :
    Unique (BinaryLeavittClassicalK1 k) where
  default := 1
  uniq a := Subsingleton.elim a 1

/-- Every invertible matrix over `L_k(1,2)`, of every finite rank, dies in the
classical `K₁`: the comparison map `GL_n(L) → K₁(L)` is trivial at every
rank. -/
theorem binaryLeavittClassicalK1_mk_eq_one (n : ℕ)
    (u : (Matrix (Fin n) (Fin n) (BinaryLeavitt.BinaryLeavittAlgebra k))ˣ) :
    (QuotientGroup.mk
        (glColimOf (BinaryLeavitt.BinaryLeavittAlgebra k) n u) :
      BinaryLeavittClassicalK1 k) = 1 :=
  Subsingleton.elim _ 1

end BinaryLeavittClassical

end NonsoficGroupsExist
