import NonsoficGroupsExist.Leavitt.AryCornerMatrix
import NonsoficGroupsExist.Leavitt.FamilyRankFour
import NonsoficGroupsExist.Leavitt.AryLeavitt

/-!
# `d`-ary Leavitt rings over finite fields have nonsofic unit, `GL`, and `EL` groups

The corner route, assembled end to end.  Let `k` be a finite field
and `A` a nontrivial countable `k`-algebra carrying a `d`-ary Leavitt family
(`d ≥ 2`).  Then:

* the corner of `A` at `e = p₀ + ⋯ + p_{d-2}` carries a unital binary Leavitt
  family (`AryCorner`);
* the `k`-subalgebra of the corner generated by the four family elements is a
  nontrivial countable finite-type `k`-algebra with a binary family, so
  finite generation costs nothing;
* the generic rank-four pipeline (`FamilyRankFour`) makes its elementary
  groups of every rank `≥ 2`, its unit group, and all its general linear
  groups nonsofic;
* the corner-extension homomorphisms (`AryCorner`, `AryCornerMatrix`)
  transport these subgroups into `Aˣ`, `GL_r(A)`, and `EL_r(A)`.

Specializing `A` to the universal algebra `L_k(1,d)` of `AryLeavitt`:

> for every finite field `k` and every `d ≥ 2`, the unit group of
> `L_k(1,d)`, every `GL_r(L_k(1,d))` with `r ≥ 1`, and every
> `EL_r(L_k(1,d))` with `r ≥ 2` are nonsofic.

At `d = 2` these are the nonsoficity statements of Theorem `thm:allranks` of
the manuscript, for the universal binary algebra built here rather than for
the presented `L_k(1,2)`; the manuscript's route to them, in full profile
form and including Theorem `thm:A`, is `Endpoint/MainResults`, and nothing in
this module feeds it.  Theorem `thm:A` itself is *not* restated here: the
statements below assert nonsoficity only, not the accompanying
finite-generation, infiniteness, and property-`(T)` clauses.

The restriction to finite-field coefficients is exactly the reach of the
formalized property-`(T)` input (Ershov–Jaikin-Zapirain for finite-type
algebras over a finite field).  The integral case `EL₄(L_ℤ(1,2))` is not
formalized, here or elsewhere in this library.
-/

namespace NonsoficGroupsExist

/-! ### The finite-type core of a binary Leavitt family -/

namespace LeavittFamily

variable (k : Type*) [Field k] {C : Type*} [Ring C] [Algebra k C]
variable (L : LeavittFamily C)

/-- The `k`-subalgebra generated by the four elements of a binary Leavitt
family.  It is finite type by construction, and it inherits the family. -/
def coreSubalgebra : Subalgebra k C :=
  Algebra.adjoin k {L.s0, L.s1, L.t0, L.t1}

theorem s0_mem_coreSubalgebra : L.s0 ∈ L.coreSubalgebra k :=
  Algebra.subset_adjoin (by simp)

theorem s1_mem_coreSubalgebra : L.s1 ∈ L.coreSubalgebra k :=
  Algebra.subset_adjoin (by simp)

theorem t0_mem_coreSubalgebra : L.t0 ∈ L.coreSubalgebra k :=
  Algebra.subset_adjoin (by simp)

theorem t1_mem_coreSubalgebra : L.t1 ∈ L.coreSubalgebra k :=
  Algebra.subset_adjoin (by simp)

/-- The binary Leavitt family restricted to its finite-type core. -/
def coreFamily : LeavittFamily (L.coreSubalgebra k) where
  s0 := ⟨L.s0, L.s0_mem_coreSubalgebra k⟩
  s1 := ⟨L.s1, L.s1_mem_coreSubalgebra k⟩
  t0 := ⟨L.t0, L.t0_mem_coreSubalgebra k⟩
  t1 := ⟨L.t1, L.t1_mem_coreSubalgebra k⟩
  t0_s0 := Subtype.ext L.t0_s0
  t0_s1 := Subtype.ext L.t0_s1
  t1_s0 := Subtype.ext L.t1_s0
  t1_s1 := Subtype.ext L.t1_s1
  sum_range := Subtype.ext L.sum_range

theorem coreSubalgebra_finiteType :
    Algebra.FiniteType k (L.coreSubalgebra k) := by
  rw [← Subalgebra.fg_iff_finiteType]
  classical
  refine ⟨{L.s0, L.s1, L.t0, L.t1}, ?_⟩
  show Algebra.adjoin k
      (↑({L.s0, L.s1, L.t0, L.t1} : Finset C) : Set C) = L.coreSubalgebra k
  rw [coreSubalgebra]
  congr 1
  simp

theorem coreSubalgebra_nontrivial [Nontrivial C] :
    Nontrivial (L.coreSubalgebra k) :=
  ⟨⟨0, 1, fun h =>
    zero_ne_one (α := C) (by simpa using congrArg Subtype.val h)⟩⟩

end LeavittFamily

/-! ### Injectivity of elementary maps along injective coefficient maps -/

theorem elementaryGroupMap_injective {R S : Type*} [Ring R] [Ring S]
    {ι : Type*} [Fintype ι] [DecidableEq ι] (f : R →+* S)
    (hf : Function.Injective f) :
    Function.Injective (elementaryGroupMap (ι := ι) f) := by
  intro x y h
  apply Subtype.ext
  apply Units.map_injective (f := f.mapMatrix.toMonoidHom)
    (fun M N hMN => Matrix.ext fun i j => hf (by
      have := congrArg (fun X : Matrix ι ι S => X i j) hMN
      simpa [RingHom.mapMatrix_apply, Matrix.map_apply] using this))
  exact congrArg (fun z : elementaryGroup ι S => (z : (Matrix ι ι S)ˣ)) h

/-! ### Theorem A for an arbitrary `d`-ary Leavitt ring over a finite field -/

namespace CompleteMatrixFamily

variable (k : Type) [Field k] [Finite k]
variable {A : Type} [Ring A] [Algebra k A] [Countable A] [Nontrivial A]
variable {n : ℕ} (F : CompleteMatrixFamily A (Fin (n + 2)))

include k F in
/-- **Units.**  The unit group of any nontrivial countable
`k`-algebra with a `d`-ary Leavitt family, `d ≥ 2`, is nonsofic. -/
theorem units_not_isSofic : ¬ IsSofic Aˣ := by
  classical
  intro hS
  haveI : Countable F.isIdempotentElem_cornerIdem.Corner :=
    inferInstanceAs
      (Countable {x : A // x ∈ Subsemigroup.corner F.cornerIdem})
  haveI : Nontrivial F.isIdempotentElem_cornerIdem.Corner :=
    F.cornerBinaryFamily_nontrivial
  haveI : Algebra.FiniteType k (F.cornerBinaryFamily.coreSubalgebra k) :=
    F.cornerBinaryFamily.coreSubalgebra_finiteType k
  haveI : Nontrivial (F.cornerBinaryFamily.coreSubalgebra k) :=
    F.cornerBinaryFamily.coreSubalgebra_nontrivial k
  have h1 : IsSofic (F.isIdempotentElem_cornerIdem.Corner)ˣ :=
    isSofic_of_injective (cornerUnitsExtend F.isIdempotentElem_cornerIdem)
      (cornerUnitsExtend_injective F.isIdempotentElem_cornerIdem) hS
  have h2 : IsSofic ((F.cornerBinaryFamily.coreSubalgebra k))ˣ :=
    isSofic_of_injective
      (Units.map (F.cornerBinaryFamily.coreSubalgebra k).val.toRingHom.toMonoidHom)
      (Units.map_injective fun a b hab => Subtype.ext hab) h1
  exact FamilyRankFour.units_not_isSofic
    (F.cornerBinaryFamily.coreFamily k) k h2

include k F in
/-- **General linear groups.**  Every positive-rank `GL` over
a nontrivial countable `k`-algebra with a `d`-ary Leavitt family is
nonsofic. -/
theorem gl_not_isSofic (m : ℕ) :
    ¬ IsSofic ((Matrix (Fin (m + 1)) (Fin (m + 1)) A)ˣ) := by
  intro hGL
  refine F.units_not_isSofic k ?_
  refine isSofic_of_injective
    (Units.map (Matrix.scalar (Fin (m + 1))).toMonoidHom) ?_ hGL
  exact Units.map_injective fun a b hab => Matrix.scalar_inj.mp hab

include k F in
/-- **Elementary groups.**  Every elementary group of rank
at least two over a nontrivial countable `k`-algebra with a `d`-ary Leavitt
family is nonsofic: transvections over the finite-type core of the
corner extend to transvections over `A`. -/
theorem elementary_not_isSofic (m : ℕ) (hm : 0 < m) :
    ¬ IsSofic (elementaryGroup (Fin (m + 1)) A) := by
  classical
  intro hS
  haveI : Countable F.isIdempotentElem_cornerIdem.Corner :=
    inferInstanceAs
      (Countable {x : A // x ∈ Subsemigroup.corner F.cornerIdem})
  haveI : Nontrivial F.isIdempotentElem_cornerIdem.Corner :=
    F.cornerBinaryFamily_nontrivial
  haveI : Algebra.FiniteType k (F.cornerBinaryFamily.coreSubalgebra k) :=
    F.cornerBinaryFamily.coreSubalgebra_finiteType k
  haveI : Nontrivial (F.cornerBinaryFamily.coreSubalgebra k) :=
    F.cornerBinaryFamily.coreSubalgebra_nontrivial k
  have h1 : IsSofic
      (elementaryGroup (Fin (m + 1)) F.isIdempotentElem_cornerIdem.Corner) :=
    isSofic_of_injective
      (cornerElementaryExtend F.isIdempotentElem_cornerIdem (Fin (m + 1)))
      (cornerElementaryExtend_injective F.isIdempotentElem_cornerIdem
        (Fin (m + 1))) hS
  have h2 : IsSofic
      (elementaryGroup (Fin (m + 1)) (F.cornerBinaryFamily.coreSubalgebra k)) :=
    isSofic_of_injective
      (elementaryGroupMap
        (F.cornerBinaryFamily.coreSubalgebra k).val.toRingHom)
      (elementaryGroupMap_injective _ fun a b hab => Subtype.ext hab) h1
  exact FamilyRankFour.elementary_not_isSofic
    (F.cornerBinaryFamily.coreFamily k) k m hm h2

end CompleteMatrixFamily

/-! ### The universal algebras `L_k(1,d)` -/

namespace AryLeavitt

variable (k : Type) [Field k] [Finite k]

/-- **`L_k(1,d)`, units**: the unit group of the universal
`d`-ary Leavitt algebra over a finite field is nonsofic, for every
`d ≥ 2`. -/
theorem aryLeavitt_units_not_isSofic (d : ℕ) (hd : 2 ≤ d) :
    ¬ IsSofic (AryLeavittAlgebra k d)ˣ := by
  obtain ⟨n, rfl⟩ : ∃ n, d = n + 2 := ⟨d - 2, by omega⟩
  haveI : NeZero (n + 2) := ⟨by omega⟩
  exact (family k (n + 2)).units_not_isSofic k

/-- **`L_k(1,d)`, general linear groups**: every
`GL_{m+1}(L_k(1,d))` is nonsofic, for every `d ≥ 2`. -/
theorem aryLeavitt_gl_not_isSofic (d : ℕ) (hd : 2 ≤ d) (m : ℕ) :
    ¬ IsSofic ((Matrix (Fin (m + 1)) (Fin (m + 1))
      (AryLeavittAlgebra k d))ˣ) := by
  obtain ⟨n, rfl⟩ : ∃ n, d = n + 2 := ⟨d - 2, by omega⟩
  haveI : NeZero (n + 2) := ⟨by omega⟩
  exact (family k (n + 2)).gl_not_isSofic k m

/-- **`L_k(1,d)`, elementary groups**: every
`EL_{m+1}(L_k(1,d))` with `m ≥ 1` is nonsofic, for every `d ≥ 2`.  In
particular so is the rank-four elementary group over every `d`-ary Leavitt
algebra over every finite field. -/
theorem aryLeavitt_elementary_not_isSofic (d : ℕ) (hd : 2 ≤ d) (m : ℕ)
    (hm : 0 < m) :
    ¬ IsSofic (elementaryGroup (Fin (m + 1)) (AryLeavittAlgebra k d)) := by
  obtain ⟨n, rfl⟩ : ∃ n, d = n + 2 := ⟨d - 2, by omega⟩
  haveI : NeZero (n + 2) := ⟨by omega⟩
  exact (family k (n + 2)).elementary_not_isSofic k m hm

/-- The headline specialization: `EL₄(L_k(1,d))` is nonsofic for every
finite field `k` and every `d ≥ 2`. -/
theorem aryLeavitt_EL4_not_isSofic (d : ℕ) (hd : 2 ≤ d) :
    ¬ IsSofic (elementaryGroup (Fin 4) (AryLeavittAlgebra k d)) :=
  aryLeavitt_elementary_not_isSofic k d hd 3 (by omega)

end AryLeavitt
end NonsoficGroupsExist
