import NonsoficGroupsExist.Leavitt.LeavittWords
import NonsoficGroupsExist.Leavitt.UniversalLeavittOver

/-!
# Monomial normal form for the universal binary Leavitt algebra

`L_k(1,2)` is spanned, as a `k`-vector space, by the monomials
`s_α t_β` over pairs of finite binary words.  The proof exhibits the span
as a subalgebra containing the four generators: the product of two
monomials collapses to a monomial or to zero by the prefix trichotomy.
-/

namespace NonsoficGroupsExist
namespace BinaryLeavitt

open LeavittFamily

noncomputable section

variable (k : Type) [Field k]

/-- The monomials `s_α t_β`. -/
def monomialSet : Set (BinaryLeavittAlgebra k) :=
  {x | ∃ a b : List (Fin 2),
    x = (family k).wordS a * (family k).wordT b}

/-- The product of two monomials is a monomial or zero. -/
theorem monomial_mul_monomial {x y : BinaryLeavittAlgebra k}
    (hx : x ∈ monomialSet k) (hy : y ∈ monomialSet k) :
    x * y ∈ monomialSet k ∨ x * y = 0 := by
  obtain ⟨a, b, rfl⟩ := hx
  obtain ⟨c, d, rfl⟩ := hy
  by_cases hbc : b <+: c
  · obtain ⟨e, rfl⟩ := hbc
    left
    refine ⟨a ++ e, d, ?_⟩
    calc
      (family k).wordS a * (family k).wordT b *
          ((family k).wordS (b ++ e) * (family k).wordT d) =
        (family k).wordS a *
          ((family k).wordT b * (family k).wordS (b ++ e)) *
            (family k).wordT d := by
        simp only [mul_assoc]
      _ = (family k).wordS (a ++ e) * (family k).wordT d := by
        rw [wordT_mul_wordS_append_left, wordS_append]
  by_cases hcb : c <+: b
  · obtain ⟨f, rfl⟩ := hcb
    left
    refine ⟨a, d ++ f, ?_⟩
    calc
      (family k).wordS a * (family k).wordT (c ++ f) *
          ((family k).wordS c * (family k).wordT d) =
        (family k).wordS a *
          ((family k).wordT (c ++ f) * (family k).wordS c) *
            (family k).wordT d := by
        simp only [mul_assoc]
      _ = (family k).wordS a * (family k).wordT (d ++ f) := by
        rw [wordT_append_mul_wordS, wordT_append, mul_assoc]
  · right
    calc
      (family k).wordS a * (family k).wordT b *
          ((family k).wordS c * (family k).wordT d) =
        (family k).wordS a *
          ((family k).wordT b * (family k).wordS c) *
            (family k).wordT d := by
        simp only [mul_assoc]
      _ = 0 := by
        rw [wordT_mul_wordS_of_incomparable (family k) b c hbc hcb]
        simp

/-- The monomial span is a subalgebra. -/
def monomialSubalgebra : Subalgebra k (BinaryLeavittAlgebra k) where
  carrier := ↑(Submodule.span k (monomialSet k))
  add_mem' := fun ha hb ↦ Submodule.add_mem _ ha hb
  mul_mem' := by
    intro x y hx hy
    induction hx using Submodule.span_induction with
    | mem u hu =>
        induction hy using Submodule.span_induction with
        | mem v hv =>
            rcases monomial_mul_monomial k hu hv with h | h
            · exact Submodule.subset_span h
            · rw [h]
              exact Submodule.zero_mem _
        | zero =>
            rw [mul_zero]
            exact Submodule.zero_mem _
        | add v w _ _ hv hw =>
            rw [mul_add]
            exact Submodule.add_mem _ hv hw
        | smul c v _ hv =>
            rw [mul_smul_comm]
            exact Submodule.smul_mem _ c hv
    | zero =>
        rw [zero_mul]
        exact Submodule.zero_mem _
    | add u v _ _ hu hv =>
        rw [add_mul]
        exact Submodule.add_mem _ hu hv
    | smul c u _ hu =>
        rw [smul_mul_assoc]
        exact Submodule.smul_mem _ c hu
  algebraMap_mem' := by
    intro c
    rw [Algebra.algebraMap_eq_smul_one]
    refine Submodule.smul_mem _ c (Submodule.subset_span ?_)
    exact ⟨[], [], by simp⟩

/-- The four generators lie in the monomial span. -/
theorem generator_mem_monomialSubalgebra (g : Generator) :
    generator k g ∈ monomialSubalgebra k := by
  apply Submodule.subset_span
  fin_cases g
  · exact ⟨[0], [], by simp [wordS, family, s0]⟩
  · exact ⟨[1], [], by simp [wordS, family, s1]⟩
  · exact ⟨[], [0], by simp [wordT, family, t0]⟩
  · exact ⟨[], [1], by simp [wordT, family, t1]⟩

/-- The presented quotient is generated by its four generators. -/
theorem adjoin_range_generator :
    Algebra.adjoin k (Set.range (generator k)) = ⊤ := by
  have hrange : Set.range (generator k) =
      ⇑(quotientMap k) '' Set.range (FreeAlgebra.ι k) := by
    rw [← Set.range_comp]
    rfl
  rw [hrange, ← AlgHom.map_adjoin, FreeAlgebra.adjoin_range_ι,
    Algebra.map_top]
  exact (AlgHom.range_eq_top _).mpr
    (RingQuot.mkAlgHom_surjective k (Relation k))

/-- **Monomial normal form** (checkpoint `B1`): the universal binary
Leavitt algebra is spanned by the monomials `s_α t_β`. -/
theorem span_monomialSet_eq_top :
    Submodule.span k (monomialSet k) = ⊤ := by
  have hle : (⊤ : Subalgebra k (BinaryLeavittAlgebra k)) ≤
      monomialSubalgebra k := by
    rw [← adjoin_range_generator k]
    apply Algebra.adjoin_le
    rintro _ ⟨g, rfl⟩
    exact generator_mem_monomialSubalgebra k g
  rw [Submodule.eq_top_iff']
  intro x
  exact hle (Algebra.mem_top)

end
end BinaryLeavitt
end NonsoficGroupsExist
