import Mathlib.Data.Matrix.Basic
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.Tactic.FinCases

/-!
# The Whitehead commutator identity

This file formalizes Lemma `lem:whitehead` of the manuscript in rank two.
The submonoid `elementary2 A` is generated by the upper and lower elementary
transvections, so membership records an explicit elementary factorization.
-/

namespace NonsoficGroupsExist
namespace Whitehead

variable {A : Type*} [Ring A]

def x12 (a : A) : Matrix (Fin 2) (Fin 2) A := !![1, a; 0, 1]

def x21 (a : A) : Matrix (Fin 2) (Fin 2) A := !![1, 0; a, 1]

/-- The rank-two elementary submonoid over a possibly noncommutative ring. -/
def elementary2 (A : Type*) [Ring A] : Submonoid (Matrix (Fin 2) (Fin 2) A) :=
  Submonoid.closure {M | ∃ a : A, M = x12 a ∨ M = x21 a}

theorem x12_mem (a : A) : x12 a ∈ elementary2 A :=
  Submonoid.subset_closure ⟨a, Or.inl rfl⟩

theorem x21_mem (a : A) : x21 a ∈ elementary2 A :=
  Submonoid.subset_closure ⟨a, Or.inr rfl⟩

/-- The three-transvection word `w(a)` from Lemma `lem:whitehead`. -/
def w (a : Aˣ) : Matrix (Fin 2) (Fin 2) A :=
  x12 (↑a : A) * x21 (-(↑(a⁻¹) : A)) * x12 (↑a : A)

theorem w_eq (a : Aˣ) :
    w a = !![0, (↑a : A); -(↑(a⁻¹) : A), 0] := by
  unfold w x12 x21
  rw [Matrix.mul_fin_two, Matrix.mul_fin_two]
  ext i j
  fin_cases i <;> fin_cases j <;> simp

theorem w_mem (a : Aˣ) : w a ∈ elementary2 A := by
  apply Submonoid.mul_mem
  · exact
      Submonoid.mul_mem (elementary2 A) (x12_mem (↑a : A))
        (x21_mem (-(↑(a⁻¹) : A)))
  · exact x12_mem (↑a : A)

def diagonalPair (a b : A) : Matrix (Fin 2) (Fin 2) A := !![a, 0; 0, b]

/-- The first displayed identity in Lemma `lem:whitehead`. -/
theorem whitehead_diagonal (a : Aˣ) :
    diagonalPair (↑a : A) (↑(a⁻¹) : A) = w a * w (-1 : Aˣ) := by
  rw [w_eq, w_eq, Matrix.mul_fin_two]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [diagonalPair]

theorem whitehead_diagonal_mem (a : Aˣ) :
    diagonalPair (↑a : A) (↑(a⁻¹) : A) ∈ elementary2 A := by
  rw [whitehead_diagonal]
  exact Submonoid.mul_mem (elementary2 A) (w_mem a) (w_mem (-1 : Aˣ))

/-- The second displayed identity in Lemma `lem:whitehead`. -/
theorem whitehead_commutator (a b : Aˣ) :
    diagonalPair (↑(a * b * a⁻¹ * b⁻¹) : A) 1 =
      diagonalPair (↑a : A) (↑(a⁻¹) : A) *
        diagonalPair (↑b : A) (↑(b⁻¹) : A) *
          diagonalPair (↑((b * a)⁻¹) : A) (↑(b * a) : A) := by
  unfold diagonalPair
  rw [Matrix.mul_fin_two, Matrix.mul_fin_two]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [mul_assoc]

theorem whitehead_commutator_mem (a b : Aˣ) :
    diagonalPair (↑(a * b * a⁻¹ * b⁻¹) : A) 1 ∈ elementary2 A := by
  rw [whitehead_commutator]
  have hba :
      diagonalPair (↑((b * a)⁻¹) : A) (↑(b * a) : A) ∈ elementary2 A := by
    simpa using whitehead_diagonal_mem ((b * a)⁻¹)
  apply Submonoid.mul_mem
  · exact
      Submonoid.mul_mem (elementary2 A) (whitehead_diagonal_mem a)
        (whitehead_diagonal_mem b)
  · exact hba

end Whitehead
end NonsoficGroupsExist
