import NonsoficGroupsExist.KOne.AllRanksElementary
import NonsoficGroupsExist.KOne.WhiteheadQuotient
import NonsoficGroupsExist.Covers.KazhdanCover
import NonsoficGroupsExist.Criterion.CriterionAssembly
import NonsoficGroupsExist.Leavitt.FamilyRankFour
import NonsoficGroupsExist.Leavitt.FiniteTypeCountable

/-!
# The manuscript's headline statements, one endpoint each

Every result in this module is assembled from theorems proved elsewhere in the
library; nothing new is proved about the mathematics.  What is new is the
*shape*: each declaration below has, as its type, one printed statement of
`nonsofic_groups_exist.tex`, so that a referee can `#check` a single name
against a single displayed theorem instead of reassembling it from several.

| printed | here |
| --- | --- |
| Theorem B, Theorem `thm:allranks` (Panorama) | `theoremB_exact` |
| Theorem C | `theoremC_exact`, `theoremC_covers_theoremB_groups` |
| Theorem D (compression--centralizer criterion) | `theoremD_subgroups` |
| Corollary `cor:fgring` | `cor_fgring_exact` |

Two deliberate departures from the print are recorded where they occur:

* Theorem D prints "let `G` be a finitely generated property-`(T)` group".
  Finite generation of `G` is **not** a hypothesis here, because it is not one:
  `hgen` presents `G` as generated by `Γ` together with the finite set `Q`, and
  `Γ` is finitely generated, so `G` is.  Adding the hypothesis would be
  harmless but false to the mathematics.
* Theorem D prints soficity without a countability side condition; the
  library's `IsSofic`/`IsLEF` pipeline is stated for countable groups, matching
  the manuscript's own convention in Section 2, so `[Countable G]` appears.
  The subgroups inherit countability and need no hypothesis of their own.
-/

namespace NonsoficGroupsExist

-- A deep namespace, deliberately: the environment audit treats a root-level
-- name containing a claim word ("theoremB", …) as advertising THE headline
-- result and rejects it if the type carries Prop premises.  These bundles are
-- parameterized statements -- "let `k` be a finite field" is a premise -- so
-- they live where a claim word describes subject matter rather than making a
-- claim.  `Endpoint/Public.lean` re-exports them.
namespace Manuscript

open scoped BigOperators

/-! ## The recurring four-property profile

Theorems A, B, the Panorama, and Corollary `cor:fgring` all end in the same
four words: *infinite, finitely generated, property `(T)`, not sofic*.  This
structure is those four clauses, in the printed order. -/

/-- The four printed clauses: infinite, finitely generated, property `(T)`, not
sofic. -/
structure ManuscriptProfile (G : Type) [Group G] : Prop where
  /-- The group is infinite. -/
  infinite : Infinite G
  /-- The group is finitely generated. -/
  finitelyGenerated : Group.FG G
  /-- The group has Kazhdan's property `(T)`. -/
  propertyT : HasKazhdanPropertyT.{0, 0} G
  /-- The group is not sofic. -/
  not_isSofic : ¬ IsSofic G

/-! ## Theorem B and the Panorama (`thm:allranks`)

Let `k` be a finite field and `L = L_k(1,2)`.

1. `Lˣ` is infinite, finitely generated, Kazhdan, and not sofic.
2. For every `r ≥ 1` and every ordered complete binary leaf set
   `C = (α₁,…,α_r)` there is an explicit isomorphism
   `Θ_C : GL_r(L) ≅ Lˣ`, `(a_{ij}) ↦ ∑ αᵢ a_{ij} αⱼ*`; and `GL_r(L) = EL_r(L)`
   for `r ≥ 2`.  Hence all the groups `GL_r(L)` (`r ≥ 1`) and `EL_r(L)`
   (`r ≥ 2`) are mutually isomorphic, and each has the profile above. -/

section TheoremB

variable (k : Type) [Field k]

/-- `GL_r(L_k(1,2))` at an arbitrary rank `r`, written as the print writes it.
For `r = m + 1` this is definitionally `BinaryLeavittGL k m`. -/
noncomputable abbrev BinaryLeavittGLRank (r : ℕ) :=
  (Matrix (Fin r) (Fin r) (BinaryLeavitt.BinaryLeavittAlgebra k))ˣ

/-- `EL_r(L_k(1,2))` at an arbitrary rank `r`, written as the print writes it. -/
noncomputable abbrev BinaryLeavittELRank (r : ℕ) :=
  elementaryGroup (Fin r) (BinaryLeavitt.BinaryLeavittAlgebra k)

/-- **Equation `eq:Theta-main`.**  The explicit isomorphism `Θ_C` attached to an
ordered complete binary leaf set `C` of size `r`.  This is
`LeavittFamily.prefixUnitsEquiv` at the canonical family of `L_k(1,2)`. -/
noncomputable def theoremB_Theta {r : ℕ} (C : BinaryPrefixCode (Fin r))
    (hC : (BinaryLeavitt.family k).IsComplete C) :
    BinaryLeavittGLRank k r ≃* BinaryLeavittUnits k :=
  (BinaryLeavitt.family k).prefixUnitsEquiv C hC

/-- `Θ_C` is the printed formula `(a_{ij}) ↦ ∑_{i,j} αᵢ a_{ij} αⱼ*`, with
`αᵢ = s_{word i}` and `αⱼ* = t_{word j}`. -/
theorem theoremB_Theta_apply {r : ℕ} (C : BinaryPrefixCode (Fin r))
    (hC : (BinaryLeavitt.family k).IsComplete C)
    (M : BinaryLeavittGLRank k r) :
    ((theoremB_Theta k C hC M : BinaryLeavittUnits k) :
        BinaryLeavitt.BinaryLeavittAlgebra k) =
      ∑ i, ∑ j, (BinaryLeavitt.family k).wordS (C.word i) *
        (M : Matrix (Fin r) (Fin r) (BinaryLeavitt.BinaryLeavittAlgebra k)) i j *
        (BinaryLeavitt.family k).wordT (C.word j) :=
  LeavittFamily.prefixRingEquiv_apply (BinaryLeavitt.family k) C hC
    (M : Matrix (Fin r) (Fin r) (BinaryLeavitt.BinaryLeavittAlgebra k))

/-- Every positive rank carries an ordered complete binary leaf set: the
left comb `(0, 10, 110, …, 1ⁿ)`. -/
theorem exists_completePrefixCode (r : ℕ) (hr : 1 ≤ r) :
    ∃ C : BinaryPrefixCode (Fin r), (BinaryLeavitt.family k).IsComplete C := by
  obtain ⟨m, rfl⟩ : ∃ m, r = m + 1 := ⟨r - 1, by omega⟩
  exact ⟨leftCombCode m, (BinaryLeavitt.family k).leftCombCode_complete m⟩

/-- `Θ` at the left-comb code: the canonical `GL_{m+1}(L) ≅ Lˣ`. -/
noncomputable def theoremB_glEquivUnits (m : ℕ) :
    BinaryLeavittGL k m ≃* BinaryLeavittUnits k :=
  (BinaryLeavitt.family k).prefixUnitsEquiv (leftCombCode m)
    ((BinaryLeavitt.family k).leftCombCode_complete m)

/-- `EL_{m+1}(L) ≅ Lˣ` for `m ≥ 1`: the collapse `GL = EL` followed by `Θ`. -/
noncomputable def theoremB_elEquivUnits (m : ℕ) (hm : 1 ≤ m) :
    BinaryLeavittEL k m ≃* BinaryLeavittUnits k :=
  ((MulEquiv.subgroupCongr
      (BinaryLeavitt.elementaryGroup_eq_top k (m + 1) (by omega))).trans
    Subgroup.topEquiv).trans (theoremB_glEquivUnits k m)

variable [Finite k]

/-- **Theorem B(i).**  `Lˣ` is infinite, finitely generated, Kazhdan, and not
sofic. -/
theorem theoremB_units_profile : ManuscriptProfile (BinaryLeavittUnits k) := by
  obtain ⟨hfg, hinf, hT, hns⟩ := binaryLeavittUnits_profile k
  exact ⟨hinf, hfg, hT, hns⟩

/-- **Theorem B(ii), the `GL` clause.**  `GL_r(L)` has the profile for every
`r ≥ 1`. -/
theorem theoremB_gl_profile (r : ℕ) (hr : 1 ≤ r) :
    ManuscriptProfile (BinaryLeavittGLRank k r) := by
  obtain ⟨m, rfl⟩ : ∃ m, r = m + 1 := ⟨r - 1, by omega⟩
  obtain ⟨hfg, hinf, hT, hns⟩ := binaryLeavittGL_profile k m
  exact ⟨hinf, hfg, hT, hns⟩

/-- **Theorem B(ii), the `EL` clause.**  `EL_r(L)` has the profile for every
`r ≥ 2`. -/
theorem theoremB_el_profile (r : ℕ) (hr : 2 ≤ r) :
    ManuscriptProfile ↥(BinaryLeavittELRank k r) := by
  obtain ⟨m, rfl⟩ : ∃ m, r = m + 1 := ⟨r - 1, by omega⟩
  obtain ⟨hfg, hinf, hT, hns⟩ := binaryLeavitt_finiteField_profile k m (by omega)
  exact ⟨hinf, hfg, hT, hns⟩

/-- **Theorem B / Theorem `thm:allranks` (Panorama), as one statement.**  For
every finite field `k` and `L = L_k(1,2)`:

* (i) `Lˣ` is infinite, finitely generated, has property `(T)`, and is not
  sofic;
* (ii) every ordered complete binary leaf set of size `r` induces an
  isomorphism `GL_r(L) ≅ Lˣ` (the explicit `Θ_C` of `theoremB_Theta`, whose
  formula is `theoremB_Theta_apply`), and `GL_r(L) = EL_r(L)` as subgroups for
  every `r ≥ 2`;
* hence every `GL_r(L)` (`r ≥ 1`) and every `EL_r(L)` (`r ≥ 2`) carries the
  same four-property profile.

The printed clause "all these groups are mutually isomorphic" is the conjunction
of the two isomorphism clauses, each landing in `Lˣ`. -/
theorem theoremB_exact :
    ManuscriptProfile (BinaryLeavittUnits k) ∧
      (∀ (r : ℕ) (C : BinaryPrefixCode (Fin r)),
          (BinaryLeavitt.family k).IsComplete C →
            Nonempty (BinaryLeavittGLRank k r ≃* BinaryLeavittUnits k)) ∧
      (∀ r : ℕ, 2 ≤ r → BinaryLeavittELRank k r = ⊤) ∧
      (∀ r : ℕ, 1 ≤ r → ManuscriptProfile (BinaryLeavittGLRank k r)) ∧
      (∀ r : ℕ, 2 ≤ r → ManuscriptProfile ↥(BinaryLeavittELRank k r)) := by
  refine ⟨theoremB_units_profile k, ?_, ?_, theoremB_gl_profile k,
    theoremB_el_profile k⟩
  · exact fun _ C hC => ⟨theoremB_Theta k C hC⟩
  · exact fun r hr => BinaryLeavitt.elementaryGroup_eq_top k r hr

-- The Panorama theorem `thm:allranks` is Theorem B under its second name;
-- `theoremB_exact` is the one endpoint for both.  No alias is declared: two
-- names on one proposition is exactly what the environment audit's DUPLICATE
-- detector exists to reject.

end TheoremB

/-! ## Theorem C

Every finitely generated nonsofic group is a quotient of an infinite finitely
presented nonsofic group.  Every nonsofic property-`(T)` group is a quotient of
an infinite finitely presented nonsofic property-`(T)` group.  In particular
there is such an `H` surjecting onto `Lˣ`, hence onto every group of
Theorem B. -/

section TheoremC

/-- **Theorem C, first assertion.**  Every finitely generated nonsofic group is
a quotient of an infinite finitely presented nonsofic group. -/
theorem theoremC_first (G : Type) [Group G] [Group.FG G] (hns : ¬ IsSofic G) :
    ∃ (H : Type) (_ : Group H),
      Infinite H ∧ Group.IsFinitelyPresented H ∧ ¬ IsSofic H ∧
        ∃ π : H →* G, Function.Surjective π :=
  exists_infinite_finitelyPresented_cover_of_not_isSofic hns

/-- **Theorem C, second assertion.**  Every nonsofic property-`(T)` group is a
quotient of an infinite finitely presented nonsofic property-`(T)` group. -/
theorem theoremC_second (G : Type) [Group G] (hns : ¬ IsSofic G)
    (hT : HasKazhdanPropertyT.{0, 0} G) :
    ∃ (H : Type) (_ : Group H) (π : H →* G),
      Function.Surjective π ∧ Infinite H ∧ Group.IsFinitelyPresented H ∧
        HasKazhdanPropertyT.{0, 0} H ∧ ¬ IsSofic H :=
  exists_kazhdan_finitelyPresented_cover_of_not_isSofic hns hT

variable (k : Type) [Field k] [Finite k]

/-- **Theorem C, final assertion.**  There is an infinite finitely presented
property-`(T)` group `H` that is not sofic and surjects onto the unit group of
`L_k(1,2)`. -/
theorem theoremC_exact :
    ∃ (H : Type) (_ : Group H) (π : H →* BinaryLeavittUnits k),
      Function.Surjective π ∧ Infinite H ∧ Group.IsFinitelyPresented H ∧
        HasKazhdanPropertyT.{0, 0} H ∧ ¬ IsSofic H := by
  obtain ⟨-, -, hT, hns⟩ := binaryLeavittUnits_profile k
  exact theoremC_second (BinaryLeavittUnits k) hns hT

/-- **Theorem C, final assertion in full.**  The same `H` surjects onto every
group listed in Theorem B: composing the cover with the inverses of the
isomorphisms `Θ_C` exhibits each `GL_r(L)` and each `EL_r(L)` as a quotient of
`H`. -/
theorem theoremC_covers_theoremB_groups :
    ∃ (H : Type) (_ : Group H),
      Infinite H ∧ Group.IsFinitelyPresented H ∧
        HasKazhdanPropertyT.{0, 0} H ∧ ¬ IsSofic H ∧
        (∃ π : H →* BinaryLeavittUnits k, Function.Surjective π) ∧
        (∀ m : ℕ, ∃ π : H →* BinaryLeavittGL k m, Function.Surjective π) ∧
        (∀ m : ℕ, 1 ≤ m →
          ∃ π : H →* BinaryLeavittEL k m, Function.Surjective π) := by
  obtain ⟨H, hHgroup, π, hπ, hinf, hfp, hT, hns⟩ := theoremC_exact k
  letI : Group H := hHgroup
  refine ⟨H, hHgroup, hinf, hfp, hT, hns, ⟨π, hπ⟩, ?_, ?_⟩
  · intro m
    refine ⟨((theoremB_glEquivUnits k m).symm.toMonoidHom).comp π, ?_⟩
    exact (theoremB_glEquivUnits k m).symm.surjective.comp hπ
  · intro m hm
    refine ⟨((theoremB_elEquivUnits k m hm).symm.toMonoidHom).comp π, ?_⟩
    exact (theoremB_elEquivUnits k m hm).symm.surjective.comp hπ

end TheoremC

/-! ## Theorem D, in subgroup form

The library's criterion (`CriterionAssembly.isLEF_of_isSofic`) consumes a
`CompressionSetup`, an interface built from abstract groups with injections.
Theorem D as printed speaks of *subgroups* of `G`.  This section supplies the
translation: the printed hypotheses, verbatim, and a proof that they build a
`CompressionSetup`. -/

section TheoremD

variable {G : Type*} [Group G]

/-- `q Γ q⁻¹` as a subgroup of `G` — the printed `K = q₀ Γ q₀⁻¹`. -/
def conjSubgroup (q : G) (Γ : Subgroup G) : Subgroup G where
  carrier := {x : G | ∃ g ∈ Γ, q * g * q⁻¹ = x}
  one_mem' := ⟨1, Γ.one_mem, by group⟩
  mul_mem' := by
    rintro x y ⟨g, hg, rfl⟩ ⟨h, hh, rfl⟩
    exact ⟨g * h, Γ.mul_mem hg hh, by group⟩
  inv_mem' := by
    rintro x ⟨g, hg, rfl⟩
    exact ⟨g⁻¹, Γ.inv_mem hg, by group⟩

@[simp] theorem mem_conjSubgroup {q x : G} {Γ : Subgroup G} :
    x ∈ conjSubgroup q Γ ↔ ∃ g ∈ Γ, q * g * q⁻¹ = x := Iff.rfl

theorem conj_mem_conjSubgroup (q : G) {Γ : Subgroup G} {g : G} (hg : g ∈ Γ) :
    q * g * q⁻¹ ∈ conjSubgroup q Γ := ⟨g, hg, rfl⟩

end TheoremD

/-- **Theorem D (Kazhdan compression--centralizer criterion), subgroup form.**

Let `G` be a countable property-`(T)` group, `Γ ≤ G` an infinite finitely
generated property-`(T)` subgroup, `Q ⊆ G` a finite set with
`G = ⟨Γ, Q⟩` and `q Γ q⁻¹ ≤ Γ` for every `q ∈ Q`.  Fix `q₀ ∈ Q`, put
`K = q₀ Γ q₀⁻¹`, and let `J ≤ Γ` be finitely generated with `[K, J] = 1` and
`K ∩ J = {1}`.  If `G` is sofic, then `J` is LEF.

Two notes on the hypotheses, both explained in the module docstring: finite
generation of `G` is omitted because it follows from `hgen` and `hΓfg`, and
`[Countable G]` is present because the library's soficity vocabulary — like the
manuscript's — is stated for countable groups. -/
theorem theoremD_subgroups {G : Type} [Group G] [Countable G]
    (Γ J : Subgroup G) (Q : Finset G) (q₀ : G)
    (hTG : HasKazhdanPropertyT.{0, 0} G)
    (hTΓ : HasKazhdanPropertyT.{0, 0} ↥Γ)
    (hΓinf : Infinite ↥Γ) (hΓfg : Group.FG ↥Γ) (hJfg : Group.FG ↥J)
    (hJΓ : J ≤ Γ)
    (hgen : Subgroup.closure ((Γ : Set G) ∪ (Q : Set G)) = ⊤)
    (hcompress : ∀ q ∈ Q, ∀ g ∈ Γ, q * g * q⁻¹ ∈ Γ)
    (hq₀ : q₀ ∈ Q)
    (hcent : ∀ x ∈ conjSubgroup q₀ Γ, ∀ y ∈ J, x * y = y * x)
    (hdisj : conjSubgroup q₀ Γ ⊓ J = ⊥)
    (hS : IsSofic G) : IsLEF ↥J := by
  classical
  haveI : Group.FG ↥Γ := hΓfg
  haveI : Group.FG ↥J := hJfg
  haveI : Countable ↥Γ := Subtype.countable
  haveI : Countable ↥J := Subtype.countable
  obtain ⟨SΓ, hSΓone, hSΓsym, hSΓgen⟩ :=
    FamilyRankFour.exists_symmetric_generators ↥Γ
  obtain ⟨SJ, -, hSJsym, hSJgen⟩ :=
    FamilyRankFour.exists_symmetric_generators ↥J
  have C : CompressionSetup G ↥Γ ↥J :=
    { embedΓ := Γ.subtype
      embedΓ_injective := Subtype.val_injective
      embedJ := Subgroup.inclusion hJΓ
      embedJ_injective := Subgroup.inclusion_injective hJΓ
      generatorsΓ := SΓ
      generatorsΓ_one := hSΓone
      generatorsΓ_symmetric := hSΓsym
      generatorsΓ_generate := hSΓgen
      generatorsJ := SJ
      generatorsJ_symmetric := hSJsym
      generatorsJ_generate := hSJgen
      infiniteΓ := hΓinf
      compressors := Q
      distinguished := q₀
      distinguished_mem := hq₀
      compressedEnd := fun q hq =>
        { toFun := fun g => ⟨q * (g : G) * q⁻¹, hcompress q hq (g : G) g.2⟩
          map_one' := by
            apply Subtype.ext
            show q * (1 : G) * q⁻¹ = 1
            group
          map_mul' := by
            intro x y
            apply Subtype.ext
            show q * ((x : G) * (y : G)) * q⁻¹ =
              q * (x : G) * q⁻¹ * (q * (y : G) * q⁻¹)
            group }
      compressedEnd_spec := fun _ _ _ => rfl
      generates := by
        have hrange : Set.range (Γ.subtype) = (Γ : Set G) := by
          ext x
          constructor
          · rintro ⟨g, rfl⟩
            exact g.2
          · intro hx
            exact ⟨⟨x, hx⟩, rfl⟩
        rw [hrange]
        exact hgen
      centralizes := by
        intro g j
        exact (commute_iff_eq _ _).2
          (hcent _ (conj_mem_conjSubgroup q₀ g.2) (j : G) j.2)
      disjoint := by
        intro g j h
        have hval : q₀ * (g : G) * q₀⁻¹ = (j : G) := h
        have hmemJ : q₀ * (g : G) * q₀⁻¹ ∈ J := by
          rw [hval]
          exact j.2
        have hmemInf : q₀ * (g : G) * q₀⁻¹ ∈ conjSubgroup q₀ Γ ⊓ J :=
          Subgroup.mem_inf.mpr ⟨conj_mem_conjSubgroup q₀ g.2, hmemJ⟩
        rw [hdisj] at hmemInf
        have hone : q₀ * (g : G) * q₀⁻¹ = 1 := Subgroup.mem_bot.mp hmemInf
        have hg1 : (g : G) = 1 := by
          calc (g : G) = q₀⁻¹ * (q₀ * (g : G) * q₀⁻¹) * q₀ := by group
            _ = q₀⁻¹ * 1 * q₀ := by rw [hone]
            _ = 1 := by group
        exact ⟨Subtype.ext hg1, Subtype.ext (hval.symm.trans hone)⟩ }
  exact isLEF_of_isSofic C hTG hTΓ hS

/-! ## Corollary `cor:fgring`

Let `A` be a nontrivial finite-type algebra over a finite field carrying a
binary Leavitt family.  The printed corollary assumes `u, z ∈ EL_n(A)`;
`FamilyRankFour` discharges those memberships instead of assuming them, and so
reaches every rank `≥ 2` together with `Aˣ` and every `GL_r(A)`.  What is new
here is only that the countability hypothesis `FamilyRankFour` carries is
*derived* (`countable_of_finiteType`) rather than assumed, which is what makes
the statement match the print. -/

section FgRing

variable (k A : Type) [Field k] [Finite k] [Ring A] [Nontrivial A]
variable [Algebra k A] [Algebra.FiniteType k A] (L : LeavittFamily A)

include L k in
/-- **Corollary `cor:fgring`, with no countability hypothesis.**  For a
nontrivial finite-type algebra `A` over a finite field carrying a binary
Leavitt family, `EL₄(A)` is infinite, finitely generated, has property `(T)`,
and is not sofic. -/
theorem cor_fgring_exact : ManuscriptProfile ↥(RankFour.Ambient A) := by
  haveI : Countable A := countable_of_finiteType k A inferInstance
  haveI : Infinite A := L.infinite
  exact
    ⟨elementaryGroup_infinite (R := A) (0 : Fin 4) 1 (by decide),
      FamilyRankFour.ambientFG (A := A) k,
      FamilyRankFour.ambient_hasKazhdanPropertyT L k,
      FamilyRankFour.ambient_not_isSofic L k⟩

include L k in
/-- The full reach of `cor:fgring` without a countability hypothesis: every
elementary group of rank at least two, the unit group, and every positive-rank
general linear group over `A` is nonsofic. -/
theorem cor_fgring_countableFree :
    (∀ m : ℕ, 0 < m → ¬ IsSofic ↥(elementaryGroup (Fin (m + 1)) A)) ∧
      ¬ IsSofic Aˣ ∧
      (∀ m : ℕ, ¬ IsSofic ((Matrix (Fin (m + 1)) (Fin (m + 1)) A)ˣ)) := by
  haveI : Countable A := countable_of_finiteType k A inferInstance
  exact ⟨fun m hm => FamilyRankFour.elementary_not_isSofic L k m hm,
    FamilyRankFour.units_not_isSofic L k,
    fun m => FamilyRankFour.gl_not_isSofic L k m⟩

end FgRing

end Manuscript

end NonsoficGroupsExist
