import NonsoficGroupsExist.Endpoint.MainResults
import NonsoficGroupsExist.Endpoint.ManuscriptStatements
import NonsoficGroupsExist.Covers.KazhdanCover
import NonsoficGroupsExist.Kazhdan.ShalomFinitePresentation
import NonsoficGroupsExist.Kun.KunDecomposition
import NonsoficGroupsExist.KunThom.KunThomTheorem
import NonsoficGroupsExist.KOne.RefineLoopDischarge
import NonsoficGroupsExist.KOne.ClassicalKOne
import NonsoficGroupsExist.KOne.FactorizationCertificate
import NonsoficGroupsExist.Kazhdan.KazhdanTextbook

/-!
# The public results

The library is organized by the order the mathematics was discovered, which is
not the order anyone should read it in.  This module is the reading path: the
declarations a referee actually needs, each named against the theorem of
`nonsofic_groups_exist.tex` it establishes, and nothing else.  Follow the
imports downward from here.

Nothing is proved in this module.  It re-exports, so that `#check` on any name
below lands on the real statement and its module.

The full statement-by-statement correspondence is `docs/CLAIM_MAP.md`,
generated from the manuscript's margin notes; this module is the short list.

## The headline

* `nonsofic_groups_exist` -- a nonsofic group exists.  Theorem A.
* `countable_nonsofic_groups_exist` -- a countable nonsofic group exists: the
  historical headline, with the same witness.
* `countable_group_without_essentiallyFreeNearAction_exists` -- the negative
  answer to Pestov's Question 5.3, as the formal corollary of the previously
  known Elek--Szabó characterization and the countable nonsofic witness.
* `universalLeavittEL4_not_isSofic` -- the explicit witness: `EL₄` over the
  universal binary Leavitt algebra `L_{𝔽₂}(1,2)`.
* `ambient_full_profile` -- that group is countable, finitely generated,
  infinite, Kazhdan, and not sofic.
* `exists_finitelyPresented_nonsofic_group` -- Theorem C, first assertion.
* `exists_infinite_finitelyPresented_nonsofic_ambient_cover` -- and it covers
  the explicit ambient group.

## One endpoint per printed theorem

The declarations above are the ones the proofs actually produce; their types are
the library's own vocabulary.  `Endpoint/ManuscriptStatements` restates the
headline theorems so that a single name carries a single *printed* statement,
which is what a referee checking the paper against the library wants.

* `theoremB_exact` -- Theorem B, all clauses at once: the four-property profile
  of `Lˣ`, of every `GL_r(L)` (`r ≥ 1`) and of every `EL_r(L)` (`r ≥ 2`),
  together with `GL_r(L) = EL_r(L)` for `r ≥ 2` and, for every ordered complete
  leaf set, the printed formula for the specific isomorphism `theoremB_Theta`.
  Naming that map rather than asserting `Nonempty (GL_r(L) ≃* Lˣ)` is what
  makes the one type carry equation `eq:Theta-main` as well.  The Panorama
  theorem `thm:allranks` is this same statement under the manuscript's other
  name; one declaration serves both.
* `theoremB_Theta`, `theoremB_Theta_apply` -- the isomorphism `Θ_C` of equation
  `eq:Theta-main` and its printed formula `(a_ij) ↦ ∑ αᵢ a_ij αⱼ*`.
* `theoremC_exact`, `theoremC_covers_theoremB_groups` -- Theorem C's final
  assertion: an infinite finitely presented Kazhdan nonsofic group surjecting
  onto `Lˣ`, and hence onto every group of Theorem B.
* `theoremD_subgroups` -- Theorem D in the printed subgroup form, with actual
  `Subgroup G` data rather than the `CompressionSetup` interface, and with the
  printed hypotheses and no others: `G`'s finite generation and `G`'s
  countability are both derived rather than assumed, the latter from property
  `(T)` by `GeneralCornerTheorem.countable_of_hasKazhdanPropertyT`.
* `cor_fgring_printed` -- Corollary `cor:fgring` verbatim: every `m ≥ 2`,
  `n = m + 1`, the printed memberships `u, z ∈ EL_n(A)` as hypotheses, and all
  four printed conclusions about `EL_n(A)`.
* `cor_fgring_exact`, `cor_fgring_countableFree` -- the same corollary with the
  memberships discharged instead of assumed, at rank four and then at every
  rank `≥ 2`, and with no countability hypothesis (`countable_of_finiteType`).
* `ManuscriptProfile` -- the four clauses "infinite, finitely generated,
  property `(T)`, not sofic" that Theorems A, B and `cor:fgring` all end in.

## `K₁` as a group rather than as a membership

* `binaryLeavittStableUnits_eq_top` -- the `K₁` chain in subgroup form.
* `BinaryLeavittWhiteheadK1` -- the quotient `Lˣ / stableUnits`, which is `K₁`
  in Whitehead form; `binaryLeavittWhiteheadK1_subsingleton` proves it trivial.
* `ClassicalGLColim`, `elementaryColim`, `BinaryLeavittClassicalK1` -- `K₁` in
  *classical* form: the stable group `colim_n GL_n(L)` modulo `E_∞(L)`, the
  subgroup generated by the elementary matrices of all finite ranks.
  `binaryLeavittElementaryColim_eq_top` says every stable class is elementary,
  and `binaryLeavittClassicalK1_subsingleton` proves the quotient trivial.
* `countable_of_finiteType` -- a finite-type algebra over a finite field is
  countable, which is what removes the countability hypothesis above.

## The external inputs that are proved here rather than cited

Every theorem the paper cites for its own proofs is proved outright here, so
these are inputs to the *paper* and not to the *library*.

* `KunDecomposition.exists_expanderDecomposition` -- Kun's expander
  decomposition, Theorem 2.9, in the one-way full-sequence form used.
* `KunThomTheorem.isLEF_of_exactProductExpansion` -- the Kun--Thom centralizer
  obstruction, Theorem 2.10.
* `Shalom.exists_finitelyPresented_kazhdan_cover` -- Shalom's theorem: every
  finitely generated Kazhdan group is a quotient of a finitely presented one.
* `finiteFieldElementaryThree_hasKazhdanPropertyT` (in
  `PropertyT/FiniteFieldElementaryPropertyT`)
  -- property `(T)` at rank three, Theorem 5.7, for finite-type algebras over
  every finite field, with the explicit Kazhdan pair of
  `FreeElementaryPropertyT`.  This is the case the paper states and consumes;
  `LeavittRankEquivalence.rankSuccEquiv` spreads it to every rank.  The
  Ershov--Jaikin-Zapirain theorem over an arbitrary finitely generated ring is
  *not* formalized, and nothing here needs it.

The non-LEF witness is likewise internal: no simplicity or finite-presentation
theorem for Thompson's `V` is used (`ThompsonFObstruction`,
`ThompsonWitness`).

## The `K₁` chain

Elementary and unconditional, replacing the localization-sequence input.
Appendix A of the manuscript is this chain written out.

* `BinaryLeavitt.K1_trivial` -- `K₁(L_k(1,2)) = 0` in Whitehead form.
* `BinaryLeavitt.exists_elementaryCertificate` -- that statement with its
  witness in hand: `diag(u,1)` as an explicit list of elementary matrices.
* `BinaryLeavitt.exists_moveList` -- the corner insertion `κ_[0](u)` of every
  unit as an explicit word of cylinder unipotents at the two atoms.
* `BinaryLeavitt.narrowReduction_holds` -- the two-exit elimination behind it.
* `BinaryLeavitt.glTwo_eq_elementary_holds`,
  `BinaryLeavitt.glFour_eq_elementary_holds` -- `GL = EL` at ranks two and four.

## What the definitions mean

An audit of axioms says nothing about whether the statement proved is the
statement intended.  These two discharge the definitional questions that carry
the most weight, as theorems rather than as caveats.

* `hasKazhdanPropertyT_iff_textbook` -- the real-orthogonal, own-universe
  property `(T)` used throughout is the textbook complex-unitary property
  quantified over every universe.
* `isLEF_iff_textbook` -- likewise for local embeddability.

## Trust surface

`NonsoficGroupsExist.Audit` prints the axiom report for these on an ordinary
build.  `scripts/Audit.lean` independently walks the transitive axiom closure
of the whole namespace and fails on anything beyond `propext`,
`Classical.choice`, and `Quot.sound`.
-/

namespace NonsoficGroupsExist.Public

open NonsoficGroupsExist

/-! ### The headline -/

export NonsoficGroupsExist (nonsofic_groups_exist countable_nonsofic_groups_exist
  countable_group_without_essentiallyFreeNearAction_exists
  universalLeavittEL4_not_admitsEssentiallyFreeNearAction
  isSofic_iff_admitsEssentiallyFreeNearAction
  universalLeavittEL4_not_isSofic
  ambient_full_profile exists_finitelyPresented_nonsofic_group
  exists_infinite_finitelyPresented_nonsofic_ambient_cover)

/-! ### Reach of the construction -/

export NonsoficGroupsExist (universalLeavitt_profile binaryLeavitt_finiteField_profile
  binaryLeavittUnits_not_isSofic binaryLeavittGL_not_isSofic
  universalLeavittEL3_not_isSofic)

/-! ### One endpoint per printed theorem -/

export NonsoficGroupsExist.Manuscript (ManuscriptProfile theoremA_exact theoremB_exact
  theoremB_Theta theoremB_Theta_apply theoremC_first
  theoremC_second theoremC_exact theoremC_covers_theoremB_groups
  theoremD_subgroups cor_fgring_printed cor_fgring_exact
  cor_fgring_countableFree)

/-! ### `K₁` as a group, and the countability that `cor:fgring` no longer needs -/

export NonsoficGroupsExist (binaryLeavittStableUnits_eq_top
  BinaryLeavittWhiteheadK1 binaryLeavittWhiteheadK1_subsingleton
  ClassicalGLColim elementaryColim BinaryLeavittClassicalK1
  binaryLeavittElementaryColim_eq_top binaryLeavittClassicalK1_subsingleton
  countable_of_finiteType)

/-! ### Inputs proved rather than cited -/

export NonsoficGroupsExist.KunDecomposition (exists_expanderDecomposition)
export NonsoficGroupsExist.KunThomTheorem (isLEF_of_exactProductExpansion)
export NonsoficGroupsExist.Shalom (exists_finitelyPresented_kazhdan_cover)
export NonsoficGroupsExist (finiteFieldElementaryThree_hasKazhdanPropertyT)
export NonsoficGroupsExist (exists_kazhdan_finitelyPresented_cover_of_not_isSofic)

/-! ### The `K₁` chain -/

export NonsoficGroupsExist.BinaryLeavitt (K1_trivial narrowReduction_holds
  exists_elementaryCertificate exists_moveList
  glTwo_eq_elementary_holds glFour_eq_elementary_holds)

/-! ### The definitions are the textbook ones -/

export NonsoficGroupsExist (hasKazhdanPropertyT_iff_textbook isLEF_iff_textbook)

end NonsoficGroupsExist.Public
