import NonsoficGroupsExist
import Lean.Elab.Command

/-!
# Elaborated signatures of every mapped declaration

`scripts/check.py` verifies that each declaration a margin note names
*exists*.  This script is the next layer: it elaborates every name in
`docs/CLAIM_DECLS.txt` (generated by `scripts/claim_map.py --write`) and
writes its type, pretty-printed by Lean itself, to
`docs/CLAIM_SIGNATURES.md`.  A declaration that keeps its name while losing
a conclusion or gaining a hypothesis changes this file, and CI fails on the
diff -- so a mapped statement cannot be weakened silently.

Run after a build:

    lake env lean scripts/Signatures.lean

then commit the regenerated `docs/CLAIM_SIGNATURES.md`.  CI runs the same
command and requires the committed file to match.
-/

open Lean Elab Command

namespace NonsoficGroupsExist.Signatures

/-- Where the declaration list is read from. -/
def declsPath : System.FilePath := "docs" / "CLAIM_DECLS.txt"

/-- Where the signatures are written to. -/
def outPath : System.FilePath := "docs" / "CLAIM_SIGNATURES.md"

def header : String :=
  "<!-- generated by `lake env lean scripts/Signatures.lean`; do not edit \
by hand -->\n\n\
# Elaborated types of the mapped declarations\n\n\
One entry per declaration named by a manuscript margin note, in the order \
of `docs/CLAIM_DECLS.txt`.  The types are printed by Lean from the \
elaborated environment, so this file records what each mapped declaration \
actually states -- the layer of the correspondence that name resolution \
alone cannot check.\n"

run_cmd do
  let env ← getEnv
  let input ← IO.FS.readFile declsPath
  let names := input.splitOn "\n" |>.map (fun s => s.trimAscii.toString)
    |>.filter (· ≠ "")
  if names.isEmpty then
    throwError "{declsPath}: no declarations listed; \
run `python3 scripts/claim_map.py --write` first"
  let mut sections : Array String := #[header]
  for s in names do
    let n := s.toName
    let some info := env.find? n
      | throwError "mapped declaration `{s}` is not in the environment; \
the lexical index and the elaborated library disagree"
    let fmt ← liftTermElabM <| Lean.Meta.ppExpr info.type
    sections := sections.push
      s!"\n## `{s}`\n\n```lean\n{fmt.pretty 96}\n```\n"
  IO.FS.writeFile outPath (String.join sections.toList)
  logInfo m!"wrote {outPath} ({names.length} declarations)"

end NonsoficGroupsExist.Signatures
